import QCKCore

open QCK

#check QCK.wordMap
#check QCK.wordMap_append
#check QCK.contextNullspace
#check QCK.mem_contextNullspace_iff
#check QCK.contextNullspace_invariant
#check QCK.Canonical
#check QCK.canonicalMap
#check QCK.reducedAction
#check QCK.reducedAction_canonicalMap
#check QCK.reducedObservation
#check QCK.reducedObservation_canonicalMap
#check QCK.canonicalMap_wordMap
#check QCK.allWordSubstitution
#check QCK.Sufficient
#check QCK.ker_le_contextNullspace
#check QCK.canonicalFactor
#check QCK.canonicalFactor_rangeRestrict
#check QCK.canonicalFactor_surjective
#check QCK.Certificate
#check QCK.Certificate.comp
#check QCK.KernelStable
#check QCK.descendedOperation
#check QCK.descendedOperation_intertwines
#check QCK.operation_descends_iff
#check QCK.operation_defect_witness
