import QCKCore
import Mathlib.LinearAlgebra.Dual.Lemmas
import Mathlib.LinearAlgebra.Dimension.RankNullity
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas
import Mathlib.LinearAlgebra.Projection
import Mathlib.LinearAlgebra.Prod
import Lean.Elab.Tactic.Omega
import Mathlib.RingTheory.Finiteness.Basic

namespace QCK

open Module Submodule LinearMap

noncomputable section

universe u v y r

variable {𝕜 : Type u} [Field 𝕜]
variable {V : Type v} [AddCommGroup V] [Module 𝕜 V] [FiniteDimensional 𝕜 V]
variable {Y : Type y} [AddCommGroup Y] [Module 𝕜 Y] [FiniteDimensional 𝕜 Y]
variable {A : Type*} [Fintype A]

/-- The finite-dimensional dual subspace generated by all protected continuation observations. -/
def futureObservableSpan
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    Submodule 𝕜 (Module.Dual 𝕜 V) :=
  ⨆ w : List A, LinearMap.range (C.comp (wordMap S w)).dualMap

/-- One generator-closure step on a subspace of source observables. -/
def closureStep
    (S : A → V →ₗ[𝕜] V)
    (L : Submodule 𝕜 (Module.Dual 𝕜 V)) :
    Submodule 𝕜 (Module.Dual 𝕜 V) :=
  L ⊔ ⨆ a : A, L.map (S a).dualMap

/-- Iterated generator closure, starting from the immediate observation space. -/
def closureIter
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    ℕ → Submodule 𝕜 (Module.Dual 𝕜 V)
  | 0 => LinearMap.range C.dualMap
  | n + 1 => closureStep S (closureIter S C n)

theorem closureIter_le_succ
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) (n : ℕ) :
    closureIter S C n ≤ closureIter S C (n + 1) := by
  change closureIter S C n ≤ closureStep S (closureIter S C n)
  exact le_sup_left

theorem closureIter_mono
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    Monotone (closureIter S C) :=
  monotone_nat_of_le_succ (closureIter_le_succ S C)

theorem futureObservableSpan_generator_closed
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) (a : A) :
    (futureObservableSpan S C).map (S a).dualMap ≤ futureObservableSpan S C := by
  rw [futureObservableSpan, Submodule.map_iSup]
  refine iSup_le ?_
  intro w
  rw [← LinearMap.range_comp]
  rw [LinearMap.dualMap_comp_dualMap]
  simpa [wordMap, LinearMap.comp_assoc] using
    (le_iSup (fun u : List A => LinearMap.range (C.comp (wordMap S u)).dualMap) (a :: w))

theorem closureIter_le_futureObservableSpan
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    ∀ n, closureIter S C n ≤ futureObservableSpan S C
  | 0 => by
      simpa [closureIter, futureObservableSpan, wordMap] using
        (le_iSup (fun w : List A => LinearMap.range (C.comp (wordMap S w)).dualMap) [])
  | n + 1 => by
      rw [closureIter, closureStep]
      refine sup_le (closureIter_le_futureObservableSpan S C n) ?_
      refine iSup_le ?_
      intro a
      exact (Submodule.map_mono (closureIter_le_futureObservableSpan S C n)).trans
        (futureObservableSpan_generator_closed S C a)

theorem wordRange_le_closureIter
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    ∀ w : List A,
      LinearMap.range (C.comp (wordMap S w)).dualMap ≤ closureIter S C w.length
  | [] => by
      simp [closureIter, wordMap]
  | a :: w => by
      rw [List.length_cons, closureIter, closureStep]
      refine le_sup_of_le_right ?_
      refine le_iSup_of_le a ?_
      calc
        LinearMap.range (C.comp (wordMap S (a :: w))).dualMap =
            (LinearMap.range (C.comp (wordMap S w)).dualMap).map (S a).dualMap := by
              rw [← LinearMap.range_comp, LinearMap.dualMap_comp_dualMap]
              rfl
        _ ≤ (closureIter S C w.length).map (S a).dualMap :=
          Submodule.map_mono (wordRange_le_closureIter S C w)

theorem iSup_closureIter_eq_futureObservableSpan
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    (⨆ n : ℕ, closureIter S C n) = futureObservableSpan S C := by
  apply le_antisymm
  · refine iSup_le ?_
    intro n
    exact closureIter_le_futureObservableSpan S C n
  · rw [futureObservableSpan]
    refine iSup_le ?_
    intro w
    exact (wordRange_le_closureIter S C w).trans
      (le_iSup (fun n : ℕ => closureIter S C n) w.length)

theorem closureIter_stabilizes
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    ∃ n, closureIter S C n = futureObservableSpan S C := by
  let chain : ℕ →o Submodule 𝕜 (Module.Dual 𝕜 V) :=
    ⟨closureIter S C, closureIter_mono S C⟩
  have hfg : (futureObservableSpan S C).FG :=
    (Submodule.fg_iff_finiteDimensional _).2 inferInstance
  have hsup : ⨆ n, chain n = futureObservableSpan S C := by
    simpa [chain] using iSup_closureIter_eq_futureObservableSpan S C
  obtain ⟨n, hn⟩ := hfg.stabilizes_of_iSup_eq chain hsup
  exact ⟨n, hn.symm⟩


/-- The future-observable dual space coannihilates exactly the context-stable nullspace. -/
theorem futureObservableSpan_dualCoannihilator
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    (futureObservableSpan S C).dualCoannihilator = contextNullspace S C := by
  ext x
  rw [Submodule.mem_dualCoannihilator, mem_contextNullspace_iff]
  constructor
  · intro hx w
    apply (Module.forall_dual_apply_eq_zero_iff 𝕜 (C (wordMap S w x))).1
    intro ψ
    have hmem :
        (C.comp (wordMap S w)).dualMap ψ ∈ futureObservableSpan S C := by
      apply
        (le_iSup
          (fun u : List A => LinearMap.range (C.comp (wordMap S u)).dualMap) w)
      exact ⟨ψ, rfl⟩
    simpa [LinearMap.dualMap_apply] using
      hx ((C.comp (wordMap S w)).dualMap ψ) hmem
  · intro hx φ hφ
    have hle :
        futureObservableSpan S C ≤
          LinearMap.ker (Module.Dual.eval 𝕜 V x) := by
      rw [futureObservableSpan]
      refine iSup_le ?_
      intro w
      rintro η ⟨ψ, rfl⟩
      rw [LinearMap.mem_ker]
      simp [Module.Dual.eval_apply, LinearMap.dualMap_apply, hx w]
    have hz := hle hφ
    simpa [LinearMap.mem_ker, Module.Dual.eval_apply] using hz

/-- In finite dimension, the future-observable span is the annihilator of the canonical nullspace. -/
theorem futureObservableSpan_eq_dualAnnihilator
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    futureObservableSpan S C = (contextNullspace S C).dualAnnihilator := by
  calc
    futureObservableSpan S C =
        (futureObservableSpan S C).dualCoannihilator.dualAnnihilator :=
      (Subspace.dualCoannihilator_dualAnnihilator_eq).symm
    _ = (contextNullspace S C).dualAnnihilator := by
      rw [futureObservableSpan_dualCoannihilator S C]

/-- Executable finite presentation: evaluate a source state against every retained future observable. -/
def finitePresentation
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    V →ₗ[𝕜] Module.Dual 𝕜 (futureObservableSpan S C) :=
  (futureObservableSpan S C).quotDualCoannihilatorToDual.comp
    (futureObservableSpan S C).dualCoannihilator.mkQ

@[simp]
theorem finitePresentation_apply
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y)
    (x : V) (φ : futureObservableSpan S C) :
    finitePresentation S C x φ = φ.1 x := by
  rfl

/-- The finite presentation forgets exactly the canonical context-stable nullspace. -/
theorem finitePresentation_ker
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    LinearMap.ker (finitePresentation S C) = contextNullspace S C := by
  rw [← futureObservableSpan_dualCoannihilator S C]
  ext x
  rw [LinearMap.mem_ker, Submodule.mem_dualCoannihilator]
  constructor
  · intro hx φ hφ
    have hp :=
      congrArg
        (fun f : Module.Dual 𝕜 (futureObservableSpan S C) => f ⟨φ, hφ⟩) hx
    simpa using hp
  · intro hx
    apply LinearMap.ext
    intro φ
    simpa using hx φ.1 φ.2

/-- The evaluation presentation reaches every linear functional on the finite future-observable space. -/
theorem finitePresentation_surjective
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    Function.Surjective (finitePresentation S C) := by
  exact
    (Subspace.quotDualCoannihilatorToDual_bijective
      (futureObservableSpan S C)).2.comp
      (Submodule.mkQ_surjective _)

/-- The frozen canonical quotient is linearly equivalent to the executable finite presentation. -/
noncomputable def canonicalEquivFinitePresentation
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    Canonical S C ≃ₗ[𝕜] Module.Dual 𝕜 (futureObservableSpan S C) :=
  (Submodule.quotEquivOfEq
      (contextNullspace S C)
      (futureObservableSpan S C).dualCoannihilator
      (futureObservableSpan_dualCoannihilator S C).symm).trans <|
    LinearEquiv.ofBijective
      (futureObservableSpan S C).quotDualCoannihilatorToDual
      (Subspace.quotDualCoannihilatorToDual_bijective
        (futureObservableSpan S C))


/-- The canonical quotient dimension equals the dimension of the retained future-observable space. -/
theorem canonical_finrank_eq_futureObservableSpan
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    Module.finrank 𝕜 (Canonical S C) =
      Module.finrank 𝕜 (futureObservableSpan S C) := by
  calc
    Module.finrank 𝕜 (Canonical S C) =
        Module.finrank 𝕜 (Module.Dual 𝕜 (futureObservableSpan S C)) :=
      (canonicalEquivFinitePresentation S C).finrank_eq
    _ = Module.finrank 𝕜 (futureObservableSpan S C) :=
      Subspace.dual_finrank_eq (K := 𝕜) (V := futureObservableSpan S C)

/-- Every sufficient finite-dimensional linear realization has rank at least the canonical quotient. -/
theorem sufficient_rank_ge_canonical
    {R : Type r} [AddCommGroup R] [Module 𝕜 R] [FiniteDimensional 𝕜 R]
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y)
    (q : V →ₗ[𝕜] R) (hq : Sufficient S C q) :
    Module.finrank 𝕜 (Canonical S C) ≤
      Module.finrank 𝕜 (LinearMap.range q) := by
  exact
    LinearMap.finrank_le_finrank_of_surjective
      (canonicalFactor_surjective S C q hq)

/-- Coordinate diagnostic map retaining current output and output after a proposed source operation. -/
def stackedOperationMap
    {R : Type r} [AddCommGroup R] [Module 𝕜 R]
    (O : V →ₗ[𝕜] R) (Aop : V →ₗ[𝕜] V) :
    V →ₗ[𝕜] R × R :=
  LinearMap.prod O (O.comp Aop)

/-- Additional finite-dimensional rank exposed by a proposed source operation. -/
def operationDefect
    {R : Type r} [AddCommGroup R] [Module 𝕜 R]
    (O : V →ₗ[𝕜] R) (Aop : V →ₗ[𝕜] V) : ℕ :=
  Module.finrank 𝕜 (LinearMap.range (stackedOperationMap O Aop)) -
    Module.finrank 𝕜 (LinearMap.range O)

@[simp]
theorem ker_stackedOperationMap
    {R : Type r} [AddCommGroup R] [Module 𝕜 R]
    (O : V →ₗ[𝕜] R) (Aop : V →ₗ[𝕜] V) :
    LinearMap.ker (stackedOperationMap O Aop) =
      LinearMap.ker O ⊓ (LinearMap.ker O).comap Aop := by
  rw [stackedOperationMap, LinearMap.ker_prod, LinearMap.ker_comp]

/-- Zero coordinate defect is exactly the Core kernel-stability condition. -/
theorem operationDefect_eq_zero_iff
    {R : Type r} [AddCommGroup R] [Module 𝕜 R] [FiniteDimensional 𝕜 R]
    (O : V →ₗ[𝕜] R) (Aop : V →ₗ[𝕜] V) :
    operationDefect O Aop = 0 ↔ KernelStable O Aop := by
  let F : V →ₗ[𝕜] R × R := stackedOperationMap O Aop
  have hk : LinearMap.ker F ≤ LinearMap.ker O := by
    dsimp [F]
    rw [ker_stackedOperationMap]
    exact inf_le_left
  have hkfin :
      Module.finrank 𝕜 (LinearMap.ker F) ≤
        Module.finrank 𝕜 (LinearMap.ker O) :=
    Submodule.finrank_mono hk
  have hO := O.finrank_range_add_finrank_ker
  have hF := F.finrank_range_add_finrank_ker
  have hrange :
      Module.finrank 𝕜 (LinearMap.range O) ≤
        Module.finrank 𝕜 (LinearMap.range F) := by
    omega
  constructor
  · intro hzero
    have hback :
        Module.finrank 𝕜 (LinearMap.range F) ≤
          Module.finrank 𝕜 (LinearMap.range O) := by
      change
        Module.finrank 𝕜 (LinearMap.range F) -
            Module.finrank 𝕜 (LinearMap.range O) = 0 at hzero
      exact Nat.sub_eq_zero_iff_le.mp hzero
    have hrEq :
        Module.finrank 𝕜 (LinearMap.range F) =
          Module.finrank 𝕜 (LinearMap.range O) :=
      le_antisymm hback hrange
    have hkEqFin :
        Module.finrank 𝕜 (LinearMap.ker F) =
          Module.finrank 𝕜 (LinearMap.ker O) := by
      omega
    have hkEq : LinearMap.ker F = LinearMap.ker O :=
      Submodule.eq_of_le_of_finrank_eq hk hkEqFin
    change LinearMap.ker O ≤ (LinearMap.ker O).comap Aop
    have hinf :
        LinearMap.ker O ⊓ (LinearMap.ker O).comap Aop =
          LinearMap.ker O := by
      simpa [F] using hkEq
    exact inf_eq_left.mp hinf
  · intro hstable
    change LinearMap.ker O ≤ (LinearMap.ker O).comap Aop at hstable
    have hkEq : LinearMap.ker F = LinearMap.ker O := by
      dsimp [F]
      rw [ker_stackedOperationMap, inf_eq_left.mpr hstable]
    have hkEqFin :
        Module.finrank 𝕜 (LinearMap.ker F) =
          Module.finrank 𝕜 (LinearMap.ker O) :=
      congrArg (fun K : Submodule 𝕜 V => Module.finrank 𝕜 K) hkEq
    have hrEq :
        Module.finrank 𝕜 (LinearMap.range F) =
          Module.finrank 𝕜 (LinearMap.range O) := by
      omega
    change
      Module.finrank 𝕜 (LinearMap.range F) -
          Module.finrank 𝕜 (LinearMap.range O) = 0
    rw [hrEq, Nat.sub_self]

/-- Positive coordinate defect carries the same separating witness as Core kernel instability. -/
theorem operationDefect_positive_witness
    {R : Type r} [AddCommGroup R] [Module 𝕜 R] [FiniteDimensional 𝕜 R]
    (O : V →ₗ[𝕜] R) (Aop : V →ₗ[𝕜] V)
    (h : 0 < operationDefect O Aop) :
    ∃ v : V, O v = 0 ∧ O (Aop v) ≠ 0 := by
  apply operation_defect_witness O Aop
  intro hstable
  have hz := (operationDefect_eq_zero_iff O Aop).2 hstable
  exact (Nat.ne_of_gt h) hz

/-- Snapshot-safe forgetting: distinctions forgotten by the active interface and every promised future interface. -/
def snapshotSafe
    {ι : Type*} [Fintype ι]
    (N0 : Submodule 𝕜 V) (N : ι → Submodule 𝕜 V) : Submodule 𝕜 V :=
  N0 ⊓ ⨅ i, N i

/-- Snapshot-safe forgetting viewed inside the current active kernel. -/
def snapshotSafeInActive
    {ι : Type*} [Fintype ι]
    (N0 : Submodule 𝕜 V) (N : ι → Submodule 𝕜 V) : Submodule 𝕜 N0 :=
  (snapshotSafe N0 N).comap N0.subtype

/-- Minimum extra linear dimension needed to retain a fixed portfolio of future distinctions. -/
def snapshotReserveFinrank
    {ι : Type*} [Fintype ι]
    (N0 : Submodule 𝕜 V) (N : ι → Submodule 𝕜 V) : ℕ :=
  Module.finrank 𝕜 (N0 ⧸ snapshotSafeInActive N0 N)

theorem snapshotSafe_le_active
    {ι : Type*} [Fintype ι]
    (N0 : Submodule 𝕜 V) (N : ι → Submodule 𝕜 V) :
    snapshotSafe N0 N ≤ N0 :=
  inf_le_left

theorem snapshotSafeInActive_finrank
    {ι : Type*} [Fintype ι]
    (N0 : Submodule 𝕜 V) (N : ι → Submodule 𝕜 V) :
    Module.finrank 𝕜 (snapshotSafeInActive N0 N) =
      Module.finrank 𝕜 (snapshotSafe N0 N) := by
  let f : snapshotSafeInActive N0 N →ₗ[𝕜] snapshotSafe N0 N :=
    { toFun := fun x => ⟨x.1.1, x.2⟩
      map_add' := by intro x y; rfl
      map_smul' := by intro a x; rfl }
  have hf : Function.Bijective f := by
    constructor
    · intro x y h
      have hv : (f x : V) = (f y : V) :=
        congrArg (fun z : snapshotSafe N0 N => (z : V)) h
      apply Subtype.ext
      apply Subtype.ext
      simpa [f] using hv
    · intro y
      refine ⟨⟨⟨y.1, snapshotSafe_le_active N0 N y.2⟩, y.2⟩, ?_⟩
      rfl
  exact (LinearEquiv.ofBijective f hf).finrank_eq

theorem snapshotReserveFinrank_eq_sub
    {ι : Type*} [Fintype ι]
    (N0 : Submodule 𝕜 V) (N : ι → Submodule 𝕜 V) :
    snapshotReserveFinrank N0 N =
      Module.finrank 𝕜 N0 - Module.finrank 𝕜 (snapshotSafe N0 N) := by
  have hq := (snapshotSafeInActive N0 N).finrank_quotient_add_finrank
  have hs := snapshotSafeInActive_finrank N0 N
  rw [snapshotReserveFinrank]
  omega

/-- Any supplementary record whose combined kernel preserves all promised future distinctions
must carry at least the snapshot reserve dimension. -/
theorem snapshotReserve_lower_bound
    {ι : Type*} [Fintype ι]
    {R0 RH : Type*}
    [AddCommGroup R0] [Module 𝕜 R0] [FiniteDimensional 𝕜 R0]
    [AddCommGroup RH] [Module 𝕜 RH] [FiniteDimensional 𝕜 RH]
    (N0 : Submodule 𝕜 V) (N : ι → Submodule 𝕜 V)
    (O0 : V →ₗ[𝕜] R0) (H : V →ₗ[𝕜] RH)
    (hO0 : LinearMap.ker O0 = N0)
    (hcombined :
      LinearMap.ker (LinearMap.prod O0 H) ≤ snapshotSafe N0 N) :
    snapshotReserveFinrank N0 N ≤
      Module.finrank 𝕜 (LinearMap.range H) := by
  have hkerprod :
      LinearMap.ker (LinearMap.prod O0 H) =
        N0 ⊓ LinearMap.ker H := by
    rw [LinearMap.ker_prod, hO0]
  have hprod_le : N0 ⊓ LinearMap.ker H ≤ snapshotSafe N0 N := by
    rw [← hkerprod]
    exact hcombined
  have hdimprod :
      Module.finrank 𝕜 ↥(N0 ⊓ LinearMap.ker H) ≤
        Module.finrank 𝕜 (snapshotSafe N0 N) :=
    Submodule.finrank_mono hprod_le
  have hH := H.finrank_range_add_finrank_ker
  have hsup :=
    Submodule.finrank_sup_add_finrank_inf_eq N0 (LinearMap.ker H)
  have hsup_le :
      Module.finrank 𝕜 ↥(N0 ⊔ LinearMap.ker H) ≤
        Module.finrank 𝕜 V :=
    (N0 ⊔ LinearMap.ker H).finrank_le
  have hN0ker :
      Module.finrank 𝕜 N0 ≤
        Module.finrank 𝕜 ↥(N0 ⊓ LinearMap.ker H) +
          Module.finrank 𝕜 (LinearMap.range H) := by
    omega
  rw [snapshotReserveFinrank_eq_sub N0 N]
  omega

/-- A chosen complement used to project arbitrary source state into the current active kernel. -/
noncomputable def activeComplement (N0 : Submodule 𝕜 V) : Submodule 𝕜 V :=
  Classical.choose (Submodule.exists_isCompl N0)

theorem active_isCompl (N0 : Submodule 𝕜 V) :
    IsCompl N0 (activeComplement N0) :=
  Classical.choose_spec (Submodule.exists_isCompl N0)

/-- An attained snapshot reserve: project into the active kernel, then retain exactly its
quotient by the future-safe subspace. -/
noncomputable def snapshotReserveMap
    {ι : Type*} [Fintype ι]
    (N0 : Submodule 𝕜 V) (N : ι → Submodule 𝕜 V) :
    V →ₗ[𝕜] (N0 ⧸ snapshotSafeInActive N0 N) :=
  (snapshotSafeInActive N0 N).mkQ.comp
    (N0.projectionOnto (activeComplement N0) (active_isCompl N0))

@[simp]
theorem snapshotReserveMap_on_active
    {ι : Type*} [Fintype ι]
    (N0 : Submodule 𝕜 V) (N : ι → Submodule 𝕜 V) (x : N0) :
    snapshotReserveMap N0 N x =
      (snapshotSafeInActive N0 N).mkQ x := by
  simp [snapshotReserveMap, Submodule.projectionOnto_apply_left]

/-- The attained reserve, paired with any active map having kernel N0, forgets exactly
the snapshot-safe distinctions. -/
theorem ker_prod_active_snapshotReserveMap
    {ι : Type*} [Fintype ι]
    {R0 : Type*} [AddCommGroup R0] [Module 𝕜 R0]
    (N0 : Submodule 𝕜 V) (N : ι → Submodule 𝕜 V)
    (O0 : V →ₗ[𝕜] R0) (hO0 : LinearMap.ker O0 = N0) :
    LinearMap.ker (LinearMap.prod O0 (snapshotReserveMap N0 N)) =
      snapshotSafe N0 N := by
  ext x
  constructor
  · intro hx
    have hp := (LinearMap.mem_ker).1 hx
    have hx0 : x ∈ N0 := by
      rw [← hO0, LinearMap.mem_ker]
      exact congrArg Prod.fst hp
    have hxH : snapshotReserveMap N0 N x = 0 := congrArg Prod.snd hp
    let xn : N0 := ⟨x, hx0⟩
    have hxH' : snapshotReserveMap N0 N (xn : V) = 0 := by
      simpa [xn] using hxH
    have hq : (snapshotSafeInActive N0 N).mkQ xn = 0 := by
      rw [← snapshotReserveMap_on_active N0 N xn]
      exact hxH'
    have hxin : xn ∈ snapshotSafeInActive N0 N :=
      (Submodule.Quotient.mk_eq_zero _).mp hq
    exact hxin
  · intro hx
    rw [LinearMap.mem_ker]
    apply Prod.ext
    · change O0 x = 0
      rw [← LinearMap.mem_ker, hO0]
      exact snapshotSafe_le_active N0 N hx
    · change snapshotReserveMap N0 N x = 0
      let xn : N0 := ⟨x, snapshotSafe_le_active N0 N hx⟩
      have hxin : xn ∈ snapshotSafeInActive N0 N := hx
      have hq : (snapshotSafeInActive N0 N).mkQ xn = 0 :=
        (Submodule.Quotient.mk_eq_zero _).2 hxin
      calc
        snapshotReserveMap N0 N x =
            snapshotReserveMap N0 N (xn : V) := by rfl
        _ = (snapshotSafeInActive N0 N).mkQ xn :=
          snapshotReserveMap_on_active N0 N xn
        _ = 0 := hq


/-! ## Maintained optionality (reconciled from qck-core-v1) -/

def snapshotNullspace
    {I : Type*} (N₀ : Submodule 𝕜 V) (future : I → V →ₗ[𝕜] 𝕜) : Submodule 𝕜 V :=
  N₀ ⊓ ⨅ i, LinearMap.ker (future i)

theorem snapshotNullspace_le
    {I : Type*} (N₀ : Submodule 𝕜 V) (future : I → V →ₗ[𝕜] 𝕜) :
    snapshotNullspace N₀ future ≤ N₀ := by
  intro x hx
  exact hx.1

def maintainedNullspace
    {B I : Type*} (S : B → V →ₗ[𝕜] V)
    (N₀ : Submodule 𝕜 V) (future : I → V →ₗ[𝕜] 𝕜) : Submodule 𝕜 V :=
  sInf (Set.range (fun w : List B =>
    (snapshotNullspace N₀ future).comap (wordMap S w)))

theorem maintainedNullspace_le_snapshot
    {B I : Type*} (S : B → V →ₗ[𝕜] V)
    (N₀ : Submodule 𝕜 V) (future : I → V →ₗ[𝕜] 𝕜) :
    maintainedNullspace S N₀ future ≤ snapshotNullspace N₀ future := by
  intro x hx
  have hle : maintainedNullspace S N₀ future ≤
      (snapshotNullspace N₀ future).comap (wordMap S ([] : List B)) := by
    apply sInf_le
    exact ⟨[], rfl⟩
  have h := hle hx
  simpa [wordMap] using h

theorem maintainedNullspace_invariant
    {B I : Type*} (S : B → V →ₗ[𝕜] V)
    (N₀ : Submodule 𝕜 V) (future : I → V →ₗ[𝕜] 𝕜) (a : B) :
    maintainedNullspace S N₀ future ≤
      (maintainedNullspace S N₀ future).comap (S a) := by
  intro x hx
  change S a x ∈ maintainedNullspace S N₀ future
  change S a x ∈ sInf (Set.range (fun w : List B =>
    (snapshotNullspace N₀ future).comap (wordMap S w)))
  have hsub : (Submodule.span 𝕜 {S a x}) ≤
      sInf (Set.range (fun w : List B =>
        (snapshotNullspace N₀ future).comap (wordMap S w))) := by
    apply le_sInf
    intro U hU
    rcases hU with ⟨w, rfl⟩
    apply Submodule.span_le.2
    intro z hz
    simp only [Set.mem_singleton_iff] at hz
    subst z
    have hle : maintainedNullspace S N₀ future ≤
        (snapshotNullspace N₀ future).comap (wordMap S (a :: w)) := by
      apply sInf_le
      exact ⟨a :: w, rfl⟩
    have h := hle hx
    simpa [wordMap] using h
  exact hsub (Submodule.subset_span (Set.mem_singleton (S a x)))

theorem le_maintainedNullspace
    {B I : Type*} (S : B → V →ₗ[𝕜] V)
    (N₀ : Submodule 𝕜 V) (future : I → V →ₗ[𝕜] 𝕜)
    (W : Submodule 𝕜 V)
    (hWsafe : W ≤ snapshotNullspace N₀ future)
    (hWinv : ∀ a, W ≤ W.comap (S a)) :
    W ≤ maintainedNullspace S N₀ future := by
  apply le_sInf
  rintro U ⟨w, rfl⟩
  intro x hx
  induction w generalizing x with
  | nil => simpa [wordMap] using hWsafe hx
  | cons a w ih =>
      change wordMap S w (S a x) ∈ snapshotNullspace N₀ future
      exact ih (hWinv a hx)

theorem maintainedNullspace_le_active
    {B I : Type*} (S : B → V →ₗ[𝕜] V)
    (N₀ : Submodule 𝕜 V) (future : I → V →ₗ[𝕜] 𝕜) :
    maintainedNullspace S N₀ future ≤ N₀ :=
  (maintainedNullspace_le_snapshot S N₀ future).trans
    (snapshotNullspace_le N₀ future)

abbrev CanonicalMaintainedReserve
    {B I : Type*} (S : B → V →ₗ[𝕜] V)
    (N₀ : Submodule 𝕜 V) (future : I → V →ₗ[𝕜] 𝕜) :=
  N₀ ⧸ (maintainedNullspace S N₀ future).comap N₀.subtype


/-- Generic finite-dimensional fact used by reserve quotients: restricting a
subspace to an ambient active subspace does not change its dimension. -/
theorem comap_subtype_finrank
    (N W : Submodule 𝕜 V) (hW : W ≤ N) :
    Module.finrank 𝕜 (W.comap N.subtype) = Module.finrank 𝕜 W := by
  let f : W.comap N.subtype →ₗ[𝕜] W :=
    { toFun := fun x => ⟨x.1.1, x.2⟩
      map_add' := by intro x y; rfl
      map_smul' := by intro a x; rfl }
  have hf : Function.Bijective f := by
    constructor
    · intro x y h
      have hv : (f x : V) = (f y : V) :=
        congrArg (fun z : W => (z : V)) h
      apply Subtype.ext
      apply Subtype.ext
      simpa [f] using hv
    · intro y
      refine ⟨⟨⟨y.1, hW y.2⟩, y.2⟩, ?_⟩
      rfl
  exact (LinearEquiv.ofBijective f hf).finrank_eq

/-- Exact dimension of optionality that must remain recoverable while waiting. -/
def maintainedReserveFinrank
    {B I : Type*} (S : B → V →ₗ[𝕜] V)
    (N₀ : Submodule 𝕜 V) (future : I → V →ₗ[𝕜] 𝕜) : ℕ :=
  Module.finrank 𝕜 (CanonicalMaintainedReserve S N₀ future)

/-- Maintained reserve dimension is precisely the active-kernel dimension
minus the greatest waiting-invariant safely-forgettable dimension. -/
theorem maintainedReserveFinrank_eq_sub
    {B I : Type*} (S : B → V →ₗ[𝕜] V)
    (N₀ : Submodule 𝕜 V) (future : I → V →ₗ[𝕜] 𝕜) :
    maintainedReserveFinrank S N₀ future =
      Module.finrank 𝕜 N₀ -
        Module.finrank 𝕜 (maintainedNullspace S N₀ future) := by
  let M := (maintainedNullspace S N₀ future).comap N₀.subtype
  have hq := M.finrank_quotient_add_finrank
  have hs :
      Module.finrank 𝕜 M =
        Module.finrank 𝕜 (maintainedNullspace S N₀ future) := by
    simpa [M] using
      (comap_subtype_finrank N₀ (maintainedNullspace S N₀ future)
        (maintainedNullspace_le_active S N₀ future))
  rw [maintainedReserveFinrank]
  change
    Module.finrank 𝕜 (N₀ ⧸ M) =
      Module.finrank 𝕜 N₀ -
        Module.finrank 𝕜 (maintainedNullspace S N₀ future)
  omega


/-- An attained maintained reserve: project into the active kernel and retain
exactly the quotient by the greatest waiting-invariant safely-forgettable subspace. -/
noncomputable def maintainedReserveMap
    {B I : Type*} (S : B → V →ₗ[𝕜] V)
    (N₀ : Submodule 𝕜 V) (future : I → V →ₗ[𝕜] 𝕜) :
    V →ₗ[𝕜] CanonicalMaintainedReserve S N₀ future :=
  ((maintainedNullspace S N₀ future).comap N₀.subtype).mkQ.comp
    (N₀.projectionOnto (activeComplement N₀) (active_isCompl N₀))

@[simp]
theorem maintainedReserveMap_on_active
    {B I : Type*} (S : B → V →ₗ[𝕜] V)
    (N₀ : Submodule 𝕜 V) (future : I → V →ₗ[𝕜] 𝕜)
    (x : N₀) :
    maintainedReserveMap S N₀ future x =
      ((maintainedNullspace S N₀ future).comap N₀.subtype).mkQ x := by
  simp [maintainedReserveMap, Submodule.projectionOnto_apply_left]

/-- Pairing any active interface with the attained maintained reserve forgets
exactly the maintained-safe distinctions. -/
theorem ker_prod_active_maintainedReserveMap
    {B I : Type*} {R0 : Type*}
    [AddCommGroup R0] [Module 𝕜 R0]
    (S : B → V →ₗ[𝕜] V)
    (N₀ : Submodule 𝕜 V) (future : I → V →ₗ[𝕜] 𝕜)
    (O0 : V →ₗ[𝕜] R0) (hO0 : LinearMap.ker O0 = N₀) :
    LinearMap.ker (LinearMap.prod O0 (maintainedReserveMap S N₀ future)) =
      maintainedNullspace S N₀ future := by
  ext x
  constructor
  · intro hx
    have hp := (LinearMap.mem_ker).1 hx
    have hx0 : x ∈ N₀ := by
      rw [← hO0, LinearMap.mem_ker]
      exact congrArg Prod.fst hp
    have hxH : maintainedReserveMap S N₀ future x = 0 :=
      congrArg Prod.snd hp
    let xn : N₀ := ⟨x, hx0⟩
    have hxH' : maintainedReserveMap S N₀ future (xn : V) = 0 := by
      simpa [xn] using hxH
    have hq :
        ((maintainedNullspace S N₀ future).comap N₀.subtype).mkQ xn = 0 := by
      rw [← maintainedReserveMap_on_active S N₀ future xn]
      exact hxH'
    have hxin :
        xn ∈ (maintainedNullspace S N₀ future).comap N₀.subtype :=
      (Submodule.Quotient.mk_eq_zero _).mp hq
    exact hxin
  · intro hx
    rw [LinearMap.mem_ker]
    apply Prod.ext
    · change O0 x = 0
      rw [← LinearMap.mem_ker, hO0]
      exact maintainedNullspace_le_active S N₀ future hx
    · change maintainedReserveMap S N₀ future x = 0
      let xn : N₀ := ⟨x, maintainedNullspace_le_active S N₀ future hx⟩
      have hxin :
          xn ∈ (maintainedNullspace S N₀ future).comap N₀.subtype := hx
      have hq :
          ((maintainedNullspace S N₀ future).comap N₀.subtype).mkQ xn = 0 :=
        (Submodule.Quotient.mk_eq_zero _).2 hxin
      calc
        maintainedReserveMap S N₀ future x =
            maintainedReserveMap S N₀ future (xn : V) := by rfl
        _ = ((maintainedNullspace S N₀ future).comap N₀.subtype).mkQ xn :=
          maintainedReserveMap_on_active S N₀ future xn
        _ = 0 := hq


/-- Restrict a waiting action to the active kernel when that kernel is itself
stable under the waiting contract. -/
def restrictedWaitingAction
    {B : Type*} (S : B → V →ₗ[𝕜] V)
    (N₀ : Submodule 𝕜 V)
    (hactive : ∀ a, N₀ ≤ N₀.comap (S a))
    (a : B) : N₀ →ₗ[𝕜] N₀ :=
  LinearMap.codRestrict N₀ ((S a).comp N₀.subtype) (by
    intro x
    exact hactive a x.2)

/-- The maintained-safe kernel remains invariant under the restricted waiting
action, so waiting can be updated entirely inside the reserve quotient. -/
theorem maintainedReserveKernel_invariant
    {B I : Type*} (S : B → V →ₗ[𝕜] V)
    (N₀ : Submodule 𝕜 V) (future : I → V →ₗ[𝕜] 𝕜)
    (hactive : ∀ a, N₀ ≤ N₀.comap (S a))
    (a : B) :
    (maintainedNullspace S N₀ future).comap N₀.subtype ≤
      ((maintainedNullspace S N₀ future).comap N₀.subtype).comap
        (restrictedWaitingAction S N₀ hactive a) := by
  intro x hx
  change S a x.1 ∈ maintainedNullspace S N₀ future
  exact maintainedNullspace_invariant S N₀ future a hx

/-- Canonical self-maintenance dynamics on the maintained reserve. -/
noncomputable def maintainedReserveUpdate
    {B I : Type*} (S : B → V →ₗ[𝕜] V)
    (N₀ : Submodule 𝕜 V) (future : I → V →ₗ[𝕜] 𝕜)
    (hactive : ∀ a, N₀ ≤ N₀.comap (S a))
    (a : B) :
    CanonicalMaintainedReserve S N₀ future →ₗ[𝕜]
      CanonicalMaintainedReserve S N₀ future :=
  let M := (maintainedNullspace S N₀ future).comap N₀.subtype
  M.mapQ M (restrictedWaitingAction S N₀ hactive a)
    (maintainedReserveKernel_invariant S N₀ future hactive a)

@[simp]
theorem maintainedReserveUpdate_mkQ
    {B I : Type*} (S : B → V →ₗ[𝕜] V)
    (N₀ : Submodule 𝕜 V) (future : I → V →ₗ[𝕜] 𝕜)
    (hactive : ∀ a, N₀ ≤ N₀.comap (S a))
    (a : B) (x : N₀) :
    maintainedReserveUpdate S N₀ future hactive a
        (((maintainedNullspace S N₀ future).comap N₀.subtype).mkQ x) =
      ((maintainedNullspace S N₀ future).comap N₀.subtype).mkQ
        (restrictedWaitingAction S N₀ hactive a x) := by
  rfl

end

end QCK
