import QCKCore
import Mathlib.LinearAlgebra.Dual.Lemmas
import Mathlib.LinearAlgebra.Dimension.RankNullity
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas
import Mathlib.RingTheory.Finiteness.Basic

namespace QCK

open Module Submodule LinearMap

noncomputable section

universe u v y

variable {𝕜 : Type u} [Field 𝕜]
variable {V : Type v} [AddCommGroup V] [Module 𝕜 V] [FiniteDimensional 𝕜 V]
variable {Y : Type y} [AddCommGroup Y] [Module 𝕜 Y] [FiniteDimensional 𝕜 Y]
variable {A : Type*} [Fintype A]

/-- The finite-dimensional dual subspace generated by all protected continuation observations. -/
def futureObservableSpan
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    Submodule 𝕜 (Module.Dual 𝕜 V) :=
  ⨆ w : List A, LinearMap.range (C.comp (wordMap S w)).dualMap

/-- One generator-closure step on a subspace of source observables. -/
def closureStep
    (S : A → V →ₗ[𝕜] V)
    (L : Submodule 𝕜 (Module.Dual 𝕜 V)) :
    Submodule 𝕜 (Module.Dual 𝕜 V) :=
  L ⊔ ⨆ a : A, L.map (S a).dualMap

/-- Iterated generator closure, starting from the immediate observation space. -/
def closureIter
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    ℕ → Submodule 𝕜 (Module.Dual 𝕜 V)
  | 0 => LinearMap.range C.dualMap
  | n + 1 => closureStep S (closureIter S C n)

theorem closureIter_le_succ
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) (n : ℕ) :
    closureIter S C n ≤ closureIter S C (n + 1) := by
  change closureIter S C n ≤ closureStep S (closureIter S C n)
  exact le_sup_left

theorem closureIter_mono
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    Monotone (closureIter S C) :=
  monotone_nat_of_le_succ (closureIter_le_succ S C)

theorem futureObservableSpan_generator_closed
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) (a : A) :
    (futureObservableSpan S C).map (S a).dualMap ≤ futureObservableSpan S C := by
  rw [futureObservableSpan, Submodule.map_iSup]
  refine iSup_le ?_
  intro w
  rw [← LinearMap.range_comp]
  rw [LinearMap.dualMap_comp_dualMap]
  simpa [wordMap, LinearMap.comp_assoc] using
    (le_iSup (fun u : List A => LinearMap.range (C.comp (wordMap S u)).dualMap) (a :: w))

theorem closureIter_le_futureObservableSpan
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    ∀ n, closureIter S C n ≤ futureObservableSpan S C
  | 0 => by
      simpa [closureIter, futureObservableSpan, wordMap] using
        (le_iSup (fun w : List A => LinearMap.range (C.comp (wordMap S w)).dualMap) [])
  | n + 1 => by
      rw [closureIter, closureStep]
      refine sup_le (closureIter_le_futureObservableSpan S C n) ?_
      refine iSup_le ?_
      intro a
      exact (Submodule.map_mono (closureIter_le_futureObservableSpan S C n)).trans
        (futureObservableSpan_generator_closed S C a)

theorem wordRange_le_closureIter
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    ∀ w : List A,
      LinearMap.range (C.comp (wordMap S w)).dualMap ≤ closureIter S C w.length
  | [] => by
      simp [closureIter, wordMap]
  | a :: w => by
      rw [List.length_cons, closureIter, closureStep]
      refine le_sup_of_le_right ?_
      refine le_iSup_of_le a ?_
      calc
        LinearMap.range (C.comp (wordMap S (a :: w))).dualMap =
            (LinearMap.range (C.comp (wordMap S w)).dualMap).map (S a).dualMap := by
              rw [← LinearMap.range_comp, LinearMap.dualMap_comp_dualMap]
              rfl
        _ ≤ (closureIter S C w.length).map (S a).dualMap :=
          Submodule.map_mono (wordRange_le_closureIter S C w)

theorem iSup_closureIter_eq_futureObservableSpan
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    (⨆ n : ℕ, closureIter S C n) = futureObservableSpan S C := by
  apply le_antisymm
  · refine iSup_le ?_
    intro n
    exact closureIter_le_futureObservableSpan S C n
  · rw [futureObservableSpan]
    refine iSup_le ?_
    intro w
    exact (wordRange_le_closureIter S C w).trans
      (le_iSup (fun n : ℕ => closureIter S C n) w.length)

theorem closureIter_stabilizes
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    ∃ n, closureIter S C n = futureObservableSpan S C := by
  let chain : ℕ →o Submodule 𝕜 (Module.Dual 𝕜 V) :=
    ⟨closureIter S C, closureIter_mono S C⟩
  have hfg : (futureObservableSpan S C).FG :=
    (Submodule.fg_iff_finiteDimensional _).2 inferInstance
  have hsup : ⨆ n, chain n = futureObservableSpan S C := by
    simpa [chain] using iSup_closureIter_eq_futureObservableSpan S C
  obtain ⟨n, hn⟩ := hfg.stabilizes_of_iSup_eq chain hsup
  exact ⟨n, hn.symm⟩

end

end QCK
