import QCKCore
import Mathlib.LinearAlgebra.Dual.Lemmas
import Mathlib.LinearAlgebra.Dimension.RankNullity
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas
import Mathlib.LinearAlgebra.Prod
import Mathlib.Tactic.Omega
import Mathlib.RingTheory.Finiteness.Basic

namespace QCK

open Module Submodule LinearMap

noncomputable section

universe u v y

variable {𝕜 : Type u} [Field 𝕜]
variable {V : Type v} [AddCommGroup V] [Module 𝕜 V] [FiniteDimensional 𝕜 V]
variable {Y : Type y} [AddCommGroup Y] [Module 𝕜 Y] [FiniteDimensional 𝕜 Y]
variable {A : Type*} [Fintype A]

/-- The finite-dimensional dual subspace generated by all protected continuation observations. -/
def futureObservableSpan
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    Submodule 𝕜 (Module.Dual 𝕜 V) :=
  ⨆ w : List A, LinearMap.range (C.comp (wordMap S w)).dualMap

/-- One generator-closure step on a subspace of source observables. -/
def closureStep
    (S : A → V →ₗ[𝕜] V)
    (L : Submodule 𝕜 (Module.Dual 𝕜 V)) :
    Submodule 𝕜 (Module.Dual 𝕜 V) :=
  L ⊔ ⨆ a : A, L.map (S a).dualMap

/-- Iterated generator closure, starting from the immediate observation space. -/
def closureIter
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    ℕ → Submodule 𝕜 (Module.Dual 𝕜 V)
  | 0 => LinearMap.range C.dualMap
  | n + 1 => closureStep S (closureIter S C n)

theorem closureIter_le_succ
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) (n : ℕ) :
    closureIter S C n ≤ closureIter S C (n + 1) := by
  change closureIter S C n ≤ closureStep S (closureIter S C n)
  exact le_sup_left

theorem closureIter_mono
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    Monotone (closureIter S C) :=
  monotone_nat_of_le_succ (closureIter_le_succ S C)

theorem futureObservableSpan_generator_closed
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) (a : A) :
    (futureObservableSpan S C).map (S a).dualMap ≤ futureObservableSpan S C := by
  rw [futureObservableSpan, Submodule.map_iSup]
  refine iSup_le ?_
  intro w
  rw [← LinearMap.range_comp]
  rw [LinearMap.dualMap_comp_dualMap]
  simpa [wordMap, LinearMap.comp_assoc] using
    (le_iSup (fun u : List A => LinearMap.range (C.comp (wordMap S u)).dualMap) (a :: w))

theorem closureIter_le_futureObservableSpan
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    ∀ n, closureIter S C n ≤ futureObservableSpan S C
  | 0 => by
      simpa [closureIter, futureObservableSpan, wordMap] using
        (le_iSup (fun w : List A => LinearMap.range (C.comp (wordMap S w)).dualMap) [])
  | n + 1 => by
      rw [closureIter, closureStep]
      refine sup_le (closureIter_le_futureObservableSpan S C n) ?_
      refine iSup_le ?_
      intro a
      exact (Submodule.map_mono (closureIter_le_futureObservableSpan S C n)).trans
        (futureObservableSpan_generator_closed S C a)

theorem wordRange_le_closureIter
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    ∀ w : List A,
      LinearMap.range (C.comp (wordMap S w)).dualMap ≤ closureIter S C w.length
  | [] => by
      simp [closureIter, wordMap]
  | a :: w => by
      rw [List.length_cons, closureIter, closureStep]
      refine le_sup_of_le_right ?_
      refine le_iSup_of_le a ?_
      calc
        LinearMap.range (C.comp (wordMap S (a :: w))).dualMap =
            (LinearMap.range (C.comp (wordMap S w)).dualMap).map (S a).dualMap := by
              rw [← LinearMap.range_comp, LinearMap.dualMap_comp_dualMap]
              rfl
        _ ≤ (closureIter S C w.length).map (S a).dualMap :=
          Submodule.map_mono (wordRange_le_closureIter S C w)

theorem iSup_closureIter_eq_futureObservableSpan
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    (⨆ n : ℕ, closureIter S C n) = futureObservableSpan S C := by
  apply le_antisymm
  · refine iSup_le ?_
    intro n
    exact closureIter_le_futureObservableSpan S C n
  · rw [futureObservableSpan]
    refine iSup_le ?_
    intro w
    exact (wordRange_le_closureIter S C w).trans
      (le_iSup (fun n : ℕ => closureIter S C n) w.length)

theorem closureIter_stabilizes
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    ∃ n, closureIter S C n = futureObservableSpan S C := by
  let chain : ℕ →o Submodule 𝕜 (Module.Dual 𝕜 V) :=
    ⟨closureIter S C, closureIter_mono S C⟩
  have hfg : (futureObservableSpan S C).FG :=
    (Submodule.fg_iff_finiteDimensional _).2 inferInstance
  have hsup : ⨆ n, chain n = futureObservableSpan S C := by
    simpa [chain] using iSup_closureIter_eq_futureObservableSpan S C
  obtain ⟨n, hn⟩ := hfg.stabilizes_of_iSup_eq chain hsup
  exact ⟨n, hn.symm⟩


/-- The future-observable dual space coannihilates exactly the context-stable nullspace. -/
theorem futureObservableSpan_dualCoannihilator
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    (futureObservableSpan S C).dualCoannihilator = contextNullspace S C := by
  ext x
  rw [Submodule.mem_dualCoannihilator, mem_contextNullspace_iff]
  constructor
  · intro hx w
    apply (Module.forall_dual_apply_eq_zero_iff 𝕜 (C (wordMap S w x))).1
    intro ψ
    have hmem :
        (C.comp (wordMap S w)).dualMap ψ ∈ futureObservableSpan S C := by
      apply
        (le_iSup
          (fun u : List A => LinearMap.range (C.comp (wordMap S u)).dualMap) w)
      exact ⟨ψ, rfl⟩
    simpa [LinearMap.dualMap_apply] using
      hx ((C.comp (wordMap S w)).dualMap ψ) hmem
  · intro hx φ hφ
    have hle :
        futureObservableSpan S C ≤
          LinearMap.ker (Module.Dual.eval 𝕜 V x) := by
      rw [futureObservableSpan]
      refine iSup_le ?_
      intro w
      rintro η ⟨ψ, rfl⟩
      rw [LinearMap.mem_ker]
      simp [Module.Dual.eval_apply, LinearMap.dualMap_apply, hx w]
    have hz := hle hφ
    simpa [LinearMap.mem_ker, Module.Dual.eval_apply] using hz

/-- In finite dimension, the future-observable span is the annihilator of the canonical nullspace. -/
theorem futureObservableSpan_eq_dualAnnihilator
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    futureObservableSpan S C = (contextNullspace S C).dualAnnihilator := by
  calc
    futureObservableSpan S C =
        (futureObservableSpan S C).dualCoannihilator.dualAnnihilator :=
      (Subspace.dualCoannihilator_dualAnnihilator_eq).symm
    _ = (contextNullspace S C).dualAnnihilator := by
      rw [futureObservableSpan_dualCoannihilator S C]

/-- Executable finite presentation: evaluate a source state against every retained future observable. -/
def finitePresentation
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    V →ₗ[𝕜] Module.Dual 𝕜 (futureObservableSpan S C) :=
  (futureObservableSpan S C).quotDualCoannihilatorToDual.comp
    (futureObservableSpan S C).dualCoannihilator.mkQ

@[simp]
theorem finitePresentation_apply
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y)
    (x : V) (φ : futureObservableSpan S C) :
    finitePresentation S C x φ = φ.1 x := by
  rfl

/-- The finite presentation forgets exactly the canonical context-stable nullspace. -/
theorem finitePresentation_ker
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    LinearMap.ker (finitePresentation S C) = contextNullspace S C := by
  rw [← futureObservableSpan_dualCoannihilator S C]
  ext x
  rw [LinearMap.mem_ker, Submodule.mem_dualCoannihilator]
  constructor
  · intro hx φ hφ
    have hp :=
      congrArg
        (fun f : Module.Dual 𝕜 (futureObservableSpan S C) => f ⟨φ, hφ⟩) hx
    simpa using hp
  · intro hx
    apply LinearMap.ext
    intro φ
    simpa using hx φ.1 φ.2

/-- The evaluation presentation reaches every linear functional on the finite future-observable space. -/
theorem finitePresentation_surjective
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    Function.Surjective (finitePresentation S C) := by
  exact
    (Subspace.quotDualCoannihilatorToDual_bijective
      (futureObservableSpan S C)).2.comp
      (Submodule.mkQ_surjective _)

/-- The frozen canonical quotient is linearly equivalent to the executable finite presentation. -/
noncomputable def canonicalEquivFinitePresentation
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    Canonical S C ≃ₗ[𝕜] Module.Dual 𝕜 (futureObservableSpan S C) :=
  (Submodule.quotEquivOfEq
      (contextNullspace S C)
      (futureObservableSpan S C).dualCoannihilator
      (futureObservableSpan_dualCoannihilator S C).symm).trans <|
    LinearEquiv.ofBijective
      (futureObservableSpan S C).quotDualCoannihilatorToDual
      (Subspace.quotDualCoannihilatorToDual_bijective
        (futureObservableSpan S C))


/-- The canonical quotient dimension equals the dimension of the retained future-observable space. -/
theorem canonical_finrank_eq_futureObservableSpan
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y) :
    Module.finrank 𝕜 (Canonical S C) =
      Module.finrank 𝕜 (futureObservableSpan S C) := by
  calc
    Module.finrank 𝕜 (Canonical S C) =
        Module.finrank 𝕜 (Module.Dual 𝕜 (futureObservableSpan S C)) :=
      (canonicalEquivFinitePresentation S C).finrank_eq
    _ = Module.finrank 𝕜 (futureObservableSpan S C) :=
      Subspace.dual_finrank_eq

/-- Every sufficient finite-dimensional linear realization has rank at least the canonical quotient. -/
theorem sufficient_rank_ge_canonical
    {R : Type r} [AddCommGroup R] [Module 𝕜 R] [FiniteDimensional 𝕜 R]
    (S : A → V →ₗ[𝕜] V) (C : V →ₗ[𝕜] Y)
    (q : V →ₗ[𝕜] R) (hq : Sufficient S C q) :
    Module.finrank 𝕜 (Canonical S C) ≤
      Module.finrank 𝕜 (LinearMap.range q) := by
  exact
    LinearMap.finrank_le_finrank_of_surjective
      (canonicalFactor_surjective S C q hq)

/-- Coordinate diagnostic map retaining current output and output after a proposed source operation. -/
def stackedOperationMap
    {R : Type r} [AddCommGroup R] [Module 𝕜 R]
    (O : V →ₗ[𝕜] R) (Aop : V →ₗ[𝕜] V) :
    V →ₗ[𝕜] R × R :=
  LinearMap.prod O (O.comp Aop)

/-- Additional finite-dimensional rank exposed by a proposed source operation. -/
def operationDefect
    {R : Type r} [AddCommGroup R] [Module 𝕜 R]
    (O : V →ₗ[𝕜] R) (Aop : V →ₗ[𝕜] V) : ℕ :=
  Module.finrank 𝕜 (LinearMap.range (stackedOperationMap O Aop)) -
    Module.finrank 𝕜 (LinearMap.range O)

@[simp]
theorem ker_stackedOperationMap
    {R : Type r} [AddCommGroup R] [Module 𝕜 R]
    (O : V →ₗ[𝕜] R) (Aop : V →ₗ[𝕜] V) :
    LinearMap.ker (stackedOperationMap O Aop) =
      LinearMap.ker O ⊓ (LinearMap.ker O).comap Aop := by
  rw [stackedOperationMap, LinearMap.ker_prod, LinearMap.ker_comp]

/-- Zero coordinate defect is exactly the Core kernel-stability condition. -/
theorem operationDefect_eq_zero_iff
    {R : Type r} [AddCommGroup R] [Module 𝕜 R] [FiniteDimensional 𝕜 R]
    (O : V →ₗ[𝕜] R) (Aop : V →ₗ[𝕜] V) :
    operationDefect O Aop = 0 ↔ KernelStable O Aop := by
  let F : V →ₗ[𝕜] R × R := stackedOperationMap O Aop
  have hk : LinearMap.ker F ≤ LinearMap.ker O := by
    dsimp [F]
    rw [ker_stackedOperationMap]
    exact inf_le_left
  have hkfin :
      Module.finrank 𝕜 (LinearMap.ker F) ≤
        Module.finrank 𝕜 (LinearMap.ker O) :=
    Submodule.finrank_mono hk
  have hO := O.finrank_range_add_finrank_ker
  have hF := F.finrank_range_add_finrank_ker
  have hrange :
      Module.finrank 𝕜 (LinearMap.range O) ≤
        Module.finrank 𝕜 (LinearMap.range F) := by
    omega
  constructor
  · intro hzero
    have hback :
        Module.finrank 𝕜 (LinearMap.range F) ≤
          Module.finrank 𝕜 (LinearMap.range O) := by
      change
        Module.finrank 𝕜 (LinearMap.range F) -
            Module.finrank 𝕜 (LinearMap.range O) = 0 at hzero
      exact Nat.sub_eq_zero_iff_le.mp hzero
    have hrEq :
        Module.finrank 𝕜 (LinearMap.range F) =
          Module.finrank 𝕜 (LinearMap.range O) :=
      le_antisymm hback hrange
    have hkEqFin :
        Module.finrank 𝕜 (LinearMap.ker F) =
          Module.finrank 𝕜 (LinearMap.ker O) := by
      omega
    have hkEq : LinearMap.ker F = LinearMap.ker O :=
      Submodule.eq_of_le_of_finrank_eq hk hkEqFin
    change LinearMap.ker O ≤ (LinearMap.ker O).comap Aop
    have hinf :
        LinearMap.ker O ⊓ (LinearMap.ker O).comap Aop =
          LinearMap.ker O := by
      simpa [F] using hkEq
    exact inf_eq_left.mp hinf
  · intro hstable
    change LinearMap.ker O ≤ (LinearMap.ker O).comap Aop at hstable
    have hkEq : LinearMap.ker F = LinearMap.ker O := by
      dsimp [F]
      rw [ker_stackedOperationMap, inf_eq_left.mpr hstable]
    have hkEqFin :
        Module.finrank 𝕜 (LinearMap.ker F) =
          Module.finrank 𝕜 (LinearMap.ker O) :=
      congrArg (Module.finrank 𝕜) hkEq
    have hrEq :
        Module.finrank 𝕜 (LinearMap.range F) =
          Module.finrank 𝕜 (LinearMap.range O) := by
      omega
    change
      Module.finrank 𝕜 (LinearMap.range F) -
          Module.finrank 𝕜 (LinearMap.range O) = 0
    rw [hrEq, Nat.sub_self]

/-- Positive coordinate defect carries the same separating witness as Core kernel instability. -/
theorem operationDefect_positive_witness
    {R : Type r} [AddCommGroup R] [Module 𝕜 R] [FiniteDimensional 𝕜 R]
    (O : V →ₗ[𝕜] R) (Aop : V →ₗ[𝕜] V)
    (h : 0 < operationDefect O Aop) :
    ∃ v : V, O v = 0 ∧ O (Aop v) ≠ 0 := by
  apply operation_defect_witness O Aop
  intro hstable
  have hz := (operationDefect_eq_zero_iff O Aop).2 hstable
  exact (Nat.ne_of_gt h) hz

end

end QCK
