r"""Equality-completion audit for the Good-row A/B renewal abstraction.

Earlier partial verifiers represented unspecified labels by different names and then
used a literal function table.  That can overstate a contradiction: if two equations
have the same (row,input), their outputs may be *forced equal* rather than inconsistent.
Likewise row injectivity can force two inputs equal when their outputs coincide.

This verifier computes the least equality closure generated by:
  1. the source equations and A/B transition identifications;
  2. functionality: same row+input => equal outputs;
  3. row injectivity: same row+output => equal inputs.
It rejects only when that forced closure violates a source-backed inequality, Good/Bad
colour separation, or the unique-fixer law.  Thus SAT means the partial equations have
an equality completion; it is still not a full E677 magma or counterexample.
"""
from __future__ import annotations
from itertools import product
import json
from renewal_block_scope_boundary import UF


def close_equalities(uf:UF,cells:list[tuple[str,str,str,str]],good:set[str],bad:set[str],ineq:list[tuple[str,str,str]]):
    """Congruence closure for one binary partial function with bijective left rows."""
    changed=True
    while changed:
        changed=False
        # Functionality within rows.
        by_in={}
        for r,x,y,_ in cells:
            key=(uf.find(r),uf.find(x)); yy=uf.find(y)
            old=by_in.get(key)
            if old is None: by_in[key]=yy
            elif uf.find(old)!=yy:
                uf.union(old,yy); changed=True
        # Left-row injectivity.
        by_out={}
        for r,x,y,_ in cells:
            key=(uf.find(r),uf.find(y)); xx=uf.find(x)
            old=by_out.get(key)
            if old is None: by_out[key]=xx
            elif uf.find(old)!=xx:
                uf.union(old,xx); changed=True
    G={uf.find(x) for x in good}; B={uf.find(x) for x in bad}
    if G&B: return False,'colour-conflict'
    for a,b,why in ineq:
        if uf.find(a)==uf.find(b): return False,why
    return True,'closed'


def build(word:str,shapes:str,enforce_unique_fixer=True):
    n=len(word); uf=UF(); cells=[]; good=set(); bad=set(); ineq=[]
    def v(k,i):
        s=f'{k}{i}'; uf.add(s); return s
    for i in range(n):
        r,g,b,x,z,a,h,w,q=[v(k,i) for k in ('r','g','b','x','z','a','h','w','q')]
        good|={r,g,z,h}; bad|={b,x}
        if shapes[i]=='S':
            uf.union(b,x); uf.union(a,z)
        else:
            ineq.append((b,x,'long-entry-exit-distinct'))
        cells += [
            (r,g,b,'entry'), (r,x,z,'exit'),
            (r,b,a,'entry-factor'), (a,r,h,'hinge'), (b,h,g,'return'),
            (r,z,w,'factor-1'), (w,r,q,'factor-2'), (z,q,x,'tau-companion'),
        ]
        j=(i+1)%n
        if word[i]=='A':
            uf.union(z,v('r',j)); uf.union(q,v('g',j)); uf.union(x,v('b',j)); good.add(q)
        else:
            uf.union(w,v('r',j)); uf.union(r,v('g',j)); uf.union(q,v('b',j)); good.add(w); bad.add(q)

    ok,reason=close_equalities(uf,cells,good,bad,ineq)
    if not ok:return {'sat':False,'reason':reason}

    if enforce_unique_fixer:
        # Closure may itself create fixed cells.  Bad inputs cannot have one; Good
        # inputs may have exactly one row class.  A missing Good fixer can be supplied
        # by a fresh row in a completion, so only forced multiplicity is checked here.
        G={uf.find(x) for x in good}; B={uf.find(x) for x in bad}
        fixers={x:set() for x in G|B}
        for r,x,y,_ in cells:
            rr,xx,yy=uf.find(r),uf.find(x),uf.find(y)
            if xx==yy and xx in fixers:fixers[xx].add(rr)
        if any(fixers[x] for x in B):return {'sat':False,'reason':'bad-has-forced-fixer'}
        if any(len(fixers[x])>1 for x in G):return {'sat':False,'reason':'good-has-forced-multiple-fixers'}

    return {'sat':True,'reason':'equality-completable-partial-system',
            'classes':len({uf.find(x) for x in uf.p})}


def main(max_len=5):
    rows=[]
    for n in range(1,max_len+1):
        for letters in product('AB',repeat=n):
            word=''.join(letters)
            for ss in product('SL',repeat=n):
                shapes=''.join(ss)
                b=build(word,shapes,False); f=build(word,shapes,True)
                rows.append({'word':word,'shapes':shapes,'base_sat':b['sat'],'fixer_sat':f['sat'],
                             'base_reason':b['reason'],'fixer_reason':f['reason']})
    words=sorted({r['word'] for r in rows},key=lambda x:(len(x),x))
    survivors={w:any(r['fixer_sat'] for r in rows if r['word']==w) for w in words}
    excluded=[w for w,v in survivors.items() if not v]
    old_scope_stable={'A','AB','BA'}
    revived=sorted(old_scope_stable-set(excluded),key=lambda x:(len(x),x))
    out={
      'max_len':max_len,'typed_cases':len(rows),
      'base_sat':sum(r['base_sat'] for r in rows),'fixer_sat':sum(r['fixer_sat'] for r in rows),
      'globally_excluded_transition_words':excluded,
      'surviving_transition_words':sum(survivors.values()),
      'previously_claimed_scope_stable':sorted(old_scope_stable),
      'revived_by_equality_completion':revived,
      'examples_for_previous_targets':{w:[r for r in rows if r['word']==w and r['fixer_sat']][:4] for w in sorted(old_scope_stable)},
      'scope':'equality-completed source-backed SHORT/LONG partial Good-row renewal equations; not full E677 and not a magma counterexample',
    }
    if revived:
        out['residual']='Distinct-label semantics caused false exclusions. Withdraw revived A/B word obstructions; retain equality completion as a verifier requirement and move to richer mixed-renewal equations without those claims.'
    else:
        out['residual']='Scope-stable exclusions survive equality completion; derive them symbolically from forced equalities before promotion.'
    print(json.dumps(out,indent=2,sort_keys=True))
    print('RENEWAL_EQUALITY_COMPLETION_BOUNDARY_VERIFIED')

if __name__=='__main__':main()