import itertools
import unittest


def all_maps(n):
    return tuple(itertools.product(range(n), repeat=n))


def compose(f, g):
    # f ∘ g
    return tuple(f[g[x]] for x in range(len(f)))


def monoid_closure(generators, n):
    ident = tuple(range(n))
    seen = {ident}
    frontier = [ident]
    while frontier:
        f = frontier.pop()
        for g in generators:
            for h in (compose(g, f), compose(f, g)):
                if h not in seen:
                    seen.add(h)
                    frontier.append(h)
    return tuple(sorted(seen))


def obs_relation(v, continuations):
    n = len(v)
    return frozenset(
        (x, y)
        for x in range(n)
        for y in range(n)
        if all(v[f[x]] == v[f[y]] for f in continuations)
    )


def is_congruence(E, actions):
    return all((g[x], g[y]) in E for x, y in E for g in actions)


def refine_to_target(v, initial, full):
    current = obs_relation(v, initial)
    target = obs_relation(v, full)
    retained = list(dict.fromkeys(initial))
    added = []
    n = len(v)
    while current != target:
        witness = None
        for f in full:
            if f in retained:
                continue
            Kf = obs_relation(v, (f,))
            if any((x, y) in current and (x, y) not in Kf for x in range(n) for y in range(n)):
                witness = f
                break
        if witness is None:
            return current, target, retained, added, False
        retained.append(witness)
        added.append(witness)
        current = current.intersection(obs_relation(v, (witness,)))
    return current, target, retained, added, True


class CompositionalClosure(unittest.TestCase):
    """Exhaustive finite tests of the compositional MSI conjecture."""

    def test_three_state_two_generator_boundary(self):
        """Unexpected boundary: on |X|=3, one-step observation is already enough.

        Exhaust over all 8 binary observations and all 27^2 ordered generator
        pairs. For this tiny universe, {id,g0,g1} induces exactly the same
        observational quotient as the full generated monoid G* in every world.
        This falsifies the expectation that |X|=3 would exhibit a necessary
        composite separator.
        """
        n = 3
        ident = tuple(range(n))
        maps = all_maps(n)
        worlds = 0
        mismatches = 0
        for v in itertools.product((0, 1), repeat=n):
            for g0 in maps:
                for g1 in maps:
                    worlds += 1
                    full = monoid_closure((g0, g1), n)
                    one = obs_relation(v, (ident, g0, g1))
                    target = obs_relation(v, full)
                    if one != target:
                        mismatches += 1
        self.assertEqual(worlds, 8 * 27 * 27)
        self.assertEqual(mismatches, 0)
        print(f"3-state compositional boundary: worlds={worlds}; one_step_too_coarse={mismatches}")

    def test_four_state_single_generator_recovers_behavioural_congruence(self):
        """At |X|=4 the desired phenomenon appears exhaustively.

        Worlds: all 16 binary observations and all 256 deterministic generators.
        Protected futures are all powers in G* generated by g. Development starts
        from {id,g}; whenever a reachable composite separates a still-merged pair,
        that composite is intersected into the interface.
        """
        n = 4
        ident = tuple(range(n))
        maps = all_maps(n)

        total_worlds = 0
        one_step_too_coarse = 0
        composite_separators_added = 0
        convergence_failures = 0
        congruence_failures = 0
        composition_failures = 0
        ablation_witnesses = 0
        examples = []

        for v in itertools.product((0, 1), repeat=n):
            for g in maps:
                total_worlds += 1
                full = monoid_closure((g,), n)
                current0 = obs_relation(v, (ident, g))
                target0 = obs_relation(v, full)
                if current0 != target0:
                    one_step_too_coarse += 1

                current, target, retained, added, ok = refine_to_target(v, (ident, g), full)
                if not ok or current != target:
                    convergence_failures += 1
                    continue
                composite_separators_added += len(added)

                if not is_congruence(target, full):
                    congruence_failures += 1
                    continue

                # Well-defined quotient dynamics + composition preservation.
                bad_comp = False
                for f in full:
                    for h in full:
                        hf = compose(h, f)
                        for x in range(n):
                            # extensional equality implies same quotient class;
                            # retain this as an explicit quotient-level law check.
                            if (hf[x], h[f[x]]) not in target:
                                bad_comp = True
                                break
                        if bad_comp:
                            break
                    if bad_comp:
                        break
                if bad_comp:
                    composition_failures += 1
                    continue

                # Exact falsifier arm: when a composite was necessary, remove the
                # final added separator and verify that an erroneous merge returns.
                if added:
                    last = added[-1]
                    ablated = list(retained)
                    ablated.remove(last)
                    E_ablated = obs_relation(v, ablated)
                    if E_ablated != target:
                        ablation_witnesses += 1
                        if len(examples) < 5:
                            restored = next(
                                ((x, y) for x in range(n) for y in range(n)
                                 if (x, y) in E_ablated and (x, y) not in target),
                                None,
                            )
                            examples.append((v, g, last, restored, len(full)))

        self.assertEqual(total_worlds, 16 * 256)
        self.assertEqual(convergence_failures, 0)
        self.assertEqual(congruence_failures, 0)
        self.assertEqual(composition_failures, 0)
        self.assertGreater(one_step_too_coarse, 0)
        self.assertGreater(composite_separators_added, 0)
        self.assertGreater(ablation_witnesses, 0)

        print(
            "4-state compositional closure census: "
            f"total_worlds={total_worlds}; "
            f"one_step_too_coarse={one_step_too_coarse}; "
            f"composite_separators_added={composite_separators_added}; "
            f"convergence_failures={convergence_failures}; "
            f"congruence_failures={congruence_failures}; "
            f"composition_failures={composition_failures}; "
            f"ablation_witnesses={ablation_witnesses}; "
            f"examples={examples}"
        )


if __name__ == "__main__":
    unittest.main()
