import itertools
import unittest


def partitions(xs):
    xs = tuple(xs)
    if not xs:
        yield ()
        return
    first, rest = xs[0], xs[1:]
    for p in partitions(rest):
        yield (frozenset((first,)),) + p
        for i in range(len(p)):
            q = list(p)
            q[i] = frozenset(set(q[i]) | {first})
            yield tuple(q)


def canon_partition(p):
    blocks = [tuple(sorted(b)) for b in p]
    return tuple(sorted(blocks))


def eq_from_partition(p):
    block_of = {}
    for i, b in enumerate(p):
        for x in b:
            block_of[x] = i
    return lambda x, y: block_of[x] == block_of[y]


def refines(p_new, p_old):
    e_old = eq_from_partition(p_old)
    for b in p_new:
        for x in b:
            for y in b:
                if not e_old(x, y):
                    return False
    return True


def invariant(p, g):
    e = eq_from_partition(p)
    xs = sorted({x for b in p for x in b})
    return all((not e(x, y)) or e(g[x], g[y]) for x in xs for y in xs)


def orbit(g, x):
    out = []
    seen = set()
    y = x
    while y not in seen:
        seen.add(y)
        out.append(y)
        y = g[y]
    return frozenset(out)


def action_closure(g):
    n = len(g)
    ident = tuple(range(n))
    seen = {ident}
    cur = ident
    while True:
        cur = tuple(g[cur[x]] for x in range(n))
        if cur in seen:
            return seen
        seen.add(cur)


def apply_map(f, x):
    return f[x]


class DifferenceTest(unittest.TestCase):
    """Minimal exhaustive consequential-distinction experiment.

    Base world X={00,01,10,11} encoded 0..3.
    Old observation is the first bit, and the only nontrivial old action flips
    the first bit. Thus the complete old action closure cannot expose the second
    bit. A certified residual says 00 and 01 must differ.

    The controller is given only (old action, old quotient, residual pair). It
    constructs a separator from the two action-orbits generated by the residual
    endpoints. No candidate feature menu or target feature identity is supplied.
    """

    def run_world(self, perm):
        X = tuple(range(4))
        inv = {perm[i]: i for i in X}

        g0 = (2, 3, 0, 1)
        g = tuple(perm[g0[inv[z]]] for z in X)

        old_blocks0 = ({0, 1}, {2, 3})
        old_p = tuple(frozenset(perm[z] for z in b) for b in old_blocks0)
        old_eq = eq_from_partition(old_p)

        x, y = perm[0], perm[1]
        self.assertTrue(old_eq(x, y))

        def old_obs(z):
            return 0 if z in old_p[0] else 1

        closure = action_closure(g)
        self.assertTrue(all(old_obs(apply_map(a, x)) == old_obs(apply_map(a, y))
                            for a in closure))

        target0 = (0, 1, 0, 1)
        target = tuple(target0[inv[z]] for z in X)
        self.assertNotEqual(target[x], target[y])

        ox, oy = orbit(g, x), orbit(g, y)
        self.assertTrue(ox.isdisjoint(oy))
        self.assertEqual(ox | oy, frozenset(X))
        delta = tuple(0 if z in ox else 1 for z in X)
        self.assertNotEqual(delta[x], delta[y])

        self.assertTrue(all(old_obs(apply_map(a, x)) == old_obs(apply_map(a, y))
                            for a in closure))

        all_parts = {canon_partition(p): p for p in partitions(X)}
        lawful = []
        for p in all_parts.values():
            if refines(p, old_p) and not eq_from_partition(p)(x, y) and invariant(p, g):
                lawful.append(p)
        self.assertTrue(lawful)

        min_blocks = min(len(p) for p in lawful)
        coarsest = {canon_partition(p) for p in lawful if len(p) == min_blocks}
        self.assertEqual(len(coarsest), 1)

        new_groups = {}
        for z in X:
            new_groups.setdefault((old_obs(z), delta[z]), set()).add(z)
        new_p = tuple(frozenset(v) for v in new_groups.values())
        self.assertIn(canon_partition(new_p), coarsest)

        old_factorable = []
        for lut in itertools.product((0, 1), repeat=2):
            f = tuple(lut[old_obs(z)] for z in X)
            old_factorable.append(f)
        self.assertNotIn(target, old_factorable)

        same = all(delta[z] == target[z] for z in X)
        flipped = all((1 - delta[z]) == target[z] for z in X)
        self.assertTrue(same or flipped)
        compiled_target = tuple(delta[z] if same else 1 - delta[z] for z in X)
        self.assertEqual(compiled_target, target)

        self.assertTrue(old_eq(x, y))
        self.assertNotEqual(compiled_target[x], compiled_target[y])
        self.assertNotEqual(target[x], target[y])

        return {
            "perm": perm,
            "closure_size": len(closure),
            "residual": (x, y),
            "generated_delta": delta,
            "lawful_repairs": len(lawful),
            "coarsest_blocks": min_blocks,
            "target": target,
        }

    def test_all_24_relabellings_repeat_same_developmental_law(self):
        results = []
        for perm in itertools.permutations(range(4)):
            results.append(self.run_world(perm))

        self.assertEqual(len(results), 24)
        self.assertGreater(len({r["generated_delta"] for r in results}), 1)
        self.assertTrue(all(r["coarsest_blocks"] == 4 for r in results))

        print("DIFFERENCE TEST PASS")
        print(f"worlds=24/24; old_closure_size={results[0]['closure_size']}; "
              f"unique_surface_deltas={len({r['generated_delta'] for r in results})}; "
              f"coarsest_blocks=4")
        print("base_example=", results[0])


if __name__ == '__main__':
    unittest.main()
