from __future__ import annotations

import argparse
import ast
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MEMORY_GRAPH = ROOT / "kaggle" / "src" / "metalogic_arc3" / "memory_graph.py"
CRYSTAL_LAWS = ROOT / "kaggle" / "src" / "metalogic_arc3" / "crystal_laws.py"
TRACE_CAPABILITIES = ROOT / "kaggle" / "src" / "metalogic_arc3" / "trace_capabilities.py"
RUNTIME = ROOT / "kaggle" / "src" / "metalogic_arc3" / "runtime.py"
MEMORY_CONTROLLER = ROOT / "kaggle" / "src" / "metalogic_arc3" / "memory_controller.py"
CONTINUATION_CORE = ROOT / "kaggle/src/metalogic_arc3/continuation_core.py"
DEVELOPMENTAL_CONTROLLER = ROOT / "kaggle/src/metalogic_arc3/developmental_controller.py"
RESIDUAL_EXPLORATION = ROOT / "kaggle/src/metalogic_arc3/residual_exploration.py"
ADAPTER = ROOT / "kaggle" / "src" / "metalogic_arc3" / "agent_template.py"
PROVENANCE = ROOT / "kaggle" / "provenance" / "sources.json"
DEFAULT_OUTPUT = ROOT / "kaggle" / "agent" / "my_agent.py"


def clean_module(text: str, remove: tuple[str, ...] = ()) -> str:
    # Match the vendored module, not an exact list of imported symbols.
    vendored = set()
    for statement in remove:
        node = ast.parse(statement).body[0]
        if not isinstance(node, ast.ImportFrom):
            raise ValueError("vendored declarations must be from-imports")
        vendored.add((node.level, node.module))
    skipped: set[int] = set()
    for node in ast.parse(text).body:
        if not isinstance(node, ast.ImportFrom):
            continue
        hoisted = node.module == "__future__" and all(
            alias.name == "annotations" for alias in node.names
        )
        if hoisted or (node.level, node.module) in vendored:
            skipped.update(range(node.lineno - 1, node.end_lineno))
    return "".join(line for i, line in enumerate(text.splitlines(keepends=True))
                   if i not in skipped).strip() + "\n"


def render() -> str:
    provenance = json.loads(PROVENANCE.read_text())
    header = (
        '"""Generated self-contained ARC-AGI-3 competition agent.\n'
        "Source of truth: modular files under kaggle/src/. Do not edit this file by hand.\n"
        '"""\n'
        "from __future__ import annotations\n\n"
        f"BUILD_PROVENANCE = {provenance!r}\n\n"
    )
    memory_graph = clean_module(MEMORY_GRAPH.read_text())
    crystal_laws = clean_module(CRYSTAL_LAWS.read_text())
    trace_capabilities = clean_module(TRACE_CAPABILITIES.read_text())
    runtime = clean_module(
        RUNTIME.read_text(),
        remove=("from .trace_capabilities import TRACE_CAPABILITY_DATA\n",),
    )
    memory_controller = clean_module(
        MEMORY_CONTROLLER.read_text(),
        remove=(
            "from .memory_graph import ActionKey, ArcMemoryGraph, ContextKey\n",
            "from .crystal_laws import ArcCrystalLawBridge, ArcLawBinding, LawAnswer, VerifiedLawStore\n",
            "from .runtime import ActionToken, Observation, OnlineController, normalize_frame\n",
        ),
    )
    continuation_core = clean_module(CONTINUATION_CORE.read_text())
    developmental_controller = clean_module(
        DEVELOPMENTAL_CONTROLLER.read_text(),
        remove=(
            "from .continuation_core import ProtectedContinuationMachine",
            "from .memory_controller import MemoryGraphController",
            "from .runtime import ActionToken",
        ),
    )
    residual_exploration = clean_module(
        RESIDUAL_EXPLORATION.read_text(),
        remove=("from .developmental_controller import ProgressMemory",
                "from .runtime import ActionToken"),
    )
    adapter = clean_module(
        ADAPTER.read_text(),
        remove=("from .residual_exploration import ResidualController\n",),
    )
    return (
        header + memory_graph + "\n" + crystal_laws + "\n" + trace_capabilities + "\n" + runtime
        + "\n" + memory_controller + "\n" + continuation_core
        + "\n" + developmental_controller + "\n" + residual_exploration + "\n" + adapter
    )


def build(output: Path) -> Path:
    output.parent.mkdir(parents=True, exist_ok=True)
    source = render()
    remaining = [node for node in ast.walk(ast.parse(source))
                 if isinstance(node, ast.ImportFrom) and node.level]
    if remaining:
        raise ValueError("standalone agent contains unvendored relative imports")
    compile(source, str(output), "exec")
    output.write_text(source)
    return output


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    path = build(args.output)
    print(path)


if __name__ == "__main__":
    main()
