from __future__ import annotations

import argparse
import ast
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MEMORY_GRAPH = ROOT / "kaggle" / "src" / "metalogic_arc3" / "memory_graph.py"
RUNTIME = ROOT / "kaggle" / "src" / "metalogic_arc3" / "runtime.py"
MEMORY_CONTROLLER = ROOT / "kaggle" / "src" / "metalogic_arc3" / "memory_controller.py"
CAUSAL_AFFORDANCE = ROOT / "kaggle" / "src" / "metalogic_arc3" / "causal_affordance.py"
RECURRENCE_FACTOR = ROOT / "kaggle" / "src" / "metalogic_arc3" / "recurrence_factor.py"
CONSEQUENCE_CONTROLLER = ROOT / "kaggle" / "src" / "metalogic_arc3" / "consequence_controller.py"
CERTIFIED_MEMORY = ROOT / "kaggle" / "src" / "metalogic_arc3" / "certified_memory.py"
REQUALIFICATION_CONTROLLER = ROOT / "kaggle" / "src" / "metalogic_arc3" / "requalification_controller.py"
ADAPTER = ROOT / "kaggle" / "src" / "metalogic_arc3" / "agent_template.py"
PROVENANCE = ROOT / "kaggle" / "provenance" / "sources.json"
DEFAULT_OUTPUT = ROOT / "kaggle" / "agent" / "my_agent.py"


def clean_module(text: str, remove: tuple[str, ...] = ()) -> str:
    vendored = set()
    for statement in remove:
        node = ast.parse(statement).body[0]
        if not isinstance(node, ast.ImportFrom):
            raise ValueError("vendored declarations must be from-imports")
        vendored.add((node.level, node.module))
    skipped: set[int] = set()
    for node in ast.parse(text).body:
        if not isinstance(node, ast.ImportFrom):
            continue
        hoisted = node.module == "__future__" and all(
            alias.name == "annotations" for alias in node.names
        )
        if hoisted or (node.level, node.module) in vendored:
            skipped.update(range(node.lineno - 1, node.end_lineno))
    return "".join(line for i, line in enumerate(text.splitlines(keepends=True))
                   if i not in skipped).strip() + "\n"


def render() -> str:
    provenance = json.loads(PROVENANCE.read_text())
    sources = (
        MEMORY_GRAPH,
        RUNTIME,
        MEMORY_CONTROLLER,
        CAUSAL_AFFORDANCE,
        RECURRENCE_FACTOR,
        CONSEQUENCE_CONTROLLER,
        CERTIFIED_MEMORY,
        REQUALIFICATION_CONTROLLER,
        ADAPTER,
    )
    source_hashes = {path.name: hashlib.sha256(path.read_bytes()).hexdigest()
                     for path in sources}
    header = (
        '\"\"\"Generated self-contained ARC-AGI-3 competition agent.\n'
        "Source of truth: modular files under kaggle/src/. Do not edit this file by hand.\n"
        '\"\"\"\n'
        "from __future__ import annotations\n\n"
        f"BUILD_PROVENANCE = {provenance!r}\n\n"
        f"BUILD_SOURCE_SHA256 = {source_hashes!r}\n\n"
    )
    memory_graph = clean_module(MEMORY_GRAPH.read_text())
    runtime = clean_module(RUNTIME.read_text())
    memory_controller = clean_module(
        MEMORY_CONTROLLER.read_text(),
        remove=(
            "from .memory_graph import ActionKey, ArcMemoryGraph, ContextKey\n",
            "from .runtime import ActionToken, Observation, OnlineController, normalize_frame\n",
        ),
    )
    causal_affordance = clean_module(CAUSAL_AFFORDANCE.read_text())
    recurrence_factor = clean_module(
        RECURRENCE_FACTOR.read_text(),
        remove=("from .memory_graph import ActionKey\n",),
    )
    consequence_controller = clean_module(
        CONSEQUENCE_CONTROLLER.read_text(),
        remove=(
            "from .causal_affordance import AffordanceMemory, effect_signature\n",
            "from .memory_controller import MemoryGraphController\n",
            "from .memory_graph import ActionKey\n",
            "from .runtime import ActionToken, Observation, normalize_frame\n",
            "from .recurrence_factor import RecurrenceFactor\n",
        ),
    )
    certified_memory = clean_module(
        CERTIFIED_MEMORY.read_text(),
        remove=(
            "from .memory_graph import (\n    ActionKey,\n    ArcMemoryGraph,\n    CapabilityKey,\n    ContextKey,\n    ProgramKey,\n    _jsonable,\n)\n",
        ),
    )
    requalification_controller = clean_module(
        REQUALIFICATION_CONTROLLER.read_text(),
        remove=(
            "from .certified_memory import CertifiedArcMemoryGraph, Checkpoint\n",
            "from .consequence_controller import ConsequenceController, effect_signature, settled_grid\n",
            "from .memory_graph import ActionKey, ProgramKey\n",
            "from .runtime import ActionToken, Observation, normalize_frame\n",
        ),
    )
    adapter = clean_module(
        ADAPTER.read_text(),
        remove=("from .requalification_controller import CertifiedConsequenceController\n",),
    )
    return header + "\n".join((
        memory_graph,
        runtime,
        memory_controller,
        causal_affordance,
        recurrence_factor,
        consequence_controller,
        certified_memory,
        requalification_controller,
        adapter,
    ))


def build(output: Path) -> Path:
    output.parent.mkdir(parents=True, exist_ok=True)
    source = render()
    remaining = [node for node in ast.walk(ast.parse(source))
                 if isinstance(node, ast.ImportFrom) and node.level]
    if remaining:
        raise ValueError("standalone agent contains unvendored relative imports")
    compile(source, str(output), "exec")
    output.write_text(source)
    return output


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    path = build(args.output)
    print(path)


if __name__ == "__main__":
    main()
