from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MEMORY_GRAPH = ROOT / "kaggle" / "src" / "metalogic_arc3" / "memory_graph.py"
RUNTIME = ROOT / "kaggle" / "src" / "metalogic_arc3" / "runtime.py"
MEMORY_CONTROLLER = ROOT / "kaggle" / "src" / "metalogic_arc3" / "memory_controller.py"
ADAPTER = ROOT / "kaggle" / "src" / "metalogic_arc3" / "agent_template.py"
PROVENANCE = ROOT / "kaggle" / "provenance" / "sources.json"
DEFAULT_OUTPUT = ROOT / "kaggle" / "agent" / "my_agent.py"


def clean_module(text: str, remove: tuple[str, ...] = ()) -> str:
    text = text.replace("from __future__ import annotations\n\n", "", 1)
    for line in remove:
        text = text.replace(line, "")
    return text.rstrip() + "\n"


def render() -> str:
    provenance = json.loads(PROVENANCE.read_text())
    header = (
        '"""Generated self-contained ARC-AGI-3 competition agent.\n'
        "Source of truth: modular files under kaggle/src/. Do not edit this file by hand.\n"
        '"""\n'
        "from __future__ import annotations\n\n"
        f"BUILD_PROVENANCE = {provenance!r}\n\n"
    )
    memory_graph = clean_module(MEMORY_GRAPH.read_text())
    runtime = clean_module(RUNTIME.read_text())
    memory_controller = clean_module(
        MEMORY_CONTROLLER.read_text(),
        remove=(
            "from .memory_graph import ActionKey, ArcMemoryGraph, ContextKey\n",
            "from .runtime import ActionToken, Observation, OnlineController, normalize_frame\n",
        ),
    )
    adapter = clean_module(
        ADAPTER.read_text(),
        remove=("from .memory_controller import MemoryGraphController\n",),
    )
    return header + memory_graph + "\n" + runtime + "\n" + memory_controller + "\n" + adapter


def build(output: Path) -> Path:
    output.parent.mkdir(parents=True, exist_ok=True)
    source = render()
    compile(source, str(output), "exec")
    output.write_text(source)
    return output


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    path = build(args.output)
    print(path)


if __name__ == "__main__":
    main()
