import CapabilityGeneratedFutureExactness

namespace CapabilityGeneratedFutureCarrier

open RequirementLandscapeCompletion
open CapabilityGeneratedFutureInterface
open CapabilityGeneratedFutureExactness

/-- The future carrier at a stage is not the ambient capability-index type.
    It is exactly the subtype of indices whose capabilities are inhabited. -/
def GeneratedFuture {I : Type} (Cap : I → Type) :=
  {i : I // generatedReachable Cap i}

/-- After verified completion, recompute the carrier from the completed
    capability family itself. -/
def GeneratedFutureAfter {I : Type} {Cap : I → Type}
    (L : RequirementLandscape I Cap) :=
  {i : I // generatedReachableAfter L i}

/-- Every old future canonically embeds into the recomputed future carrier. -/
def embedOldFuture
    {I : Type} {Cap : I → Type}
    (L : RequirementLandscape I Cap) :
    GeneratedFuture Cap → GeneratedFutureAfter L :=
  fun f => ⟨f.1, old_generated_futures_embed L f.2⟩

/-- Recomputing the carrier never identifies two distinct old futures. -/
theorem embedOldFuture_injective
    {I : Type} {Cap : I → Type}
    (L : RequirementLandscape I Cap) :
    Function.Injective (embedOldFuture L) := by
  intro x y h
  apply Subtype.ext
  exact congrArg Subtype.val h

/-- A verified residual constructs a future directly in the next carrier. -/
def residualFuture
    {I : Type} {Cap : I → Type}
    (L : RequirementLandscape I Cap) {i : I}
    (hres : residualDemand L i) : GeneratedFutureAfter L :=
  ⟨i, (generated_after_iff_old_or_residual L).2 (Or.inr hres)⟩

/-- The future generated by a genuine residual is outside the image of every
    old future.  This is type-level carrier growth, not merely a changed
    reachability predicate on a fixed future set. -/
theorem residualFuture_not_in_old_image
    {I : Type} {Cap : I → Type}
    (L : RequirementLandscape I Cap) {i : I}
    (hres : residualDemand L i) :
    ¬ ∃ f : GeneratedFuture Cap,
      embedOldFuture L f = residualFuture L hres := by
  rintro ⟨f, hEq⟩
  have hval : f.1 = i := congrArg Subtype.val hEq
  have hold : generatedReachable Cap i := by
    rw [← hval]
    exact f.2
  exact hres.2 hold

/-- Therefore any residual makes the new future carrier strictly larger than
    the embedded old carrier in the precise sense of exhibiting a next-stage
    element outside the old image. -/
theorem residual_strictly_grows_future_carrier
    {I : Type} {Cap : I → Type}
    (L : RequirementLandscape I Cap) {i : I}
    (hres : residualDemand L i) :
    ∃ fnew : GeneratedFutureAfter L,
      ¬ ∃ fold : GeneratedFuture Cap,
        embedOldFuture L fold = fnew := by
  exact ⟨residualFuture L hres, residualFuture_not_in_old_image L hres⟩

/-- The next carrier has no mysterious generators: every next-stage future is
    either the embedding of an old future, or its index is a derived residual. -/
theorem next_future_is_old_image_or_residual
    {I : Type} {Cap : I → Type}
    (L : RequirementLandscape I Cap)
    (f : GeneratedFutureAfter L) :
    (∃ fold : GeneratedFuture Cap, embedOldFuture L fold = f) ∨
      residualDemand L f.1 := by
  rcases (generated_after_iff_old_or_residual L).1 f.2 with hold | hres
  · left
    refine ⟨⟨f.1, hold⟩, ?_⟩
    apply Subtype.ext
    rfl
  · exact Or.inr hres

/-- Under requirement ablation, every next-stage future comes from the old
    carrier: there is no carrier growth. -/
theorem ablated_carrier_is_covered_by_old_image
    {I : Type} {Cap : I → Type}
    (f : GeneratedFutureAfter
      (erasedLandscape : RequirementLandscape I Cap)) :
    ∃ fold : GeneratedFuture Cap,
      embedOldFuture (erasedLandscape : RequirementLandscape I Cap) fold = f := by
  rcases next_future_is_old_image_or_residual
      (erasedLandscape : RequirementLandscape I Cap) f with hold | hres
  · exact hold
  · exact False.elim hres.1

namespace Witness

open CapabilityGeneratedFutureExactness.Witness

def newCarrierFuture : GeneratedFutureAfter L :=
  residualFuture L new_residual

theorem new_future_outside_old_carrier :
    ¬ ∃ f : GeneratedFuture Cap,
      embedOldFuture L f = newCarrierFuture := by
  exact residualFuture_not_in_old_image L new_residual

theorem carrier_strictly_grows :
    ∃ fnew : GeneratedFutureAfter L,
      ¬ ∃ fold : GeneratedFuture Cap,
        embedOldFuture L fold = fnew := by
  exact residual_strictly_grows_future_carrier L new_residual

end Witness

#check GeneratedFuture
#check GeneratedFutureAfter
#check embedOldFuture
#check embedOldFuture_injective
#check residualFuture
#check residualFuture_not_in_old_image
#check residual_strictly_grows_future_carrier
#check next_future_is_old_image_or_residual
#check ablated_carrier_is_covered_by_old_image
#check Witness.new_future_outside_old_carrier
#check Witness.carrier_strictly_grows

end CapabilityGeneratedFutureCarrier
