import ConsequentialCompletionCoupling

namespace CapabilityGeneratedFutureInterface

open RequirementLandscapeCompletion
open ConsequentialCompletionCoupling

/-- Cycle 14 removes the need to supply a separate map from capability indices
    into a future carrier.  The capability index itself is the canonical future
    generated by the current capability family. -/
def canonicalFutureInterface (I : Type) : FutureInterface I I where
  futureOf := fun i => i

/-- A future exists exactly when its generating capability is currently
    inhabited.  No external future basis or naming map is supplied. -/
def generatedReachable
    {I : Type} (Cap : I → Type) : I → Prop :=
  fun i => Nonempty (Cap i)

/-- After verifier-driven completion, the future interface is recomputed from
    the completed capability family itself. -/
def generatedReachableAfter
    {I : Type} {Cap : I → Type}
    (L : RequirementLandscape I Cap) : I → Prop :=
  fun i => Nonempty (completeLandscape L i)

/-- The canonical interface agrees exactly with capability-derived
    reachability before completion. -/
theorem canonical_before_iff_generated
    {I : Type} {Cap : I → Type} {i : I} :
    reachableBefore (Cap := Cap) (canonicalFutureInterface I) i ↔
      generatedReachable Cap i := by
  constructor
  · rintro ⟨j, hj, hji⟩
    cases hji
    exact hj
  · intro hi
    exact ⟨i, hi, rfl⟩

/-- The same canonical interface agrees exactly with the future set induced by
    the completed capability family. -/
theorem canonical_after_iff_generated
    {I : Type} {Cap : I → Type}
    (L : RequirementLandscape I Cap) {i : I} :
    reachableAfter (canonicalFutureInterface I) L i ↔
      generatedReachableAfter L i := by
  constructor
  · rintro ⟨j, hj, hji⟩
    cases hji
    exact hj
  · intro hi
    exact ⟨i, hi, rfl⟩

/-- Every old generated future embeds into the next generated future set. -/
theorem old_generated_futures_embed
    {I : Type} {Cap : I → Type}
    (L : RequirementLandscape I Cap) {i : I} :
    generatedReachable Cap i → generatedReachableAfter L i := by
  rintro ⟨h⟩
  exact ⟨includeOld h⟩

/-- A verifier-required absent capability produces a genuinely new future:
    absent in the old generated interface, present in the recomputed one. -/
theorem residual_generates_genuinely_new_future
    {I : Type} {Cap : I → Type}
    (L : RequirementLandscape I Cap) {i : I}
    (hreq : L.required i) (habs : ¬ Nonempty (Cap i)) :
    ¬ generatedReachable Cap i ∧ generatedReachableAfter L i := by
  exact ⟨habs, every_required_absence_is_filled L hreq habs⟩

/-- Causal ablation: erase the requirement signal and the generated future
    disappears again. -/
theorem ablation_erases_generated_future
    {I : Type} {Cap : I → Type}
    (L : RequirementLandscape I Cap) {i : I}
    (hreq : L.required i) (habs : ¬ Nonempty (Cap i)) :
    ¬ generatedReachableAfter
      (erasedLandscape : RequirementLandscape I Cap) i := by
  exact erasing_requirements_blocks_genesis L ⟨hreq, habs⟩

/-- Once the canonical future is generated, it can refine an identity that was
    valid under the old capability-derived future set.  The future naming map
    is not an input: it is definitionally the capability index. -/
theorem generated_capability_can_refine_identity
    {X I : Type} {Cap : I → Type}
    (observe : I → X → Bool)
    (L : RequirementLandscape I Cap)
    {i : I} {x y : X}
    (hbefore : EquivalentUnder (generatedReachable Cap) observe x y)
    (hreq : L.required i)
    (habs : ¬ Nonempty (Cap i))
    (hsep : observe i x ≠ observe i y) :
    EquivalentUnder (generatedReachable Cap) observe x y ∧
    ¬ EquivalentUnder (generatedReachableAfter L) observe x y := by
  constructor
  · exact hbefore
  · intro hafter
    exact hsep (hafter i (every_required_absence_is_filled L hreq habs))

namespace Witness

inductive Idx where | probe deriving DecidableEq
inductive State where | left | right deriving DecidableEq

abbrev EmptyCap : Idx → Type := fun _ => Empty

def L : RequirementLandscape Idx EmptyCap where
  required := fun _ => True

def observe : Idx → State → Bool
  | .probe, .left => false
  | .probe, .right => true

theorem absent : ¬ Nonempty (EmptyCap Idx.probe) := by
  intro h
  rcases h with ⟨h⟩
  exact nomatch h

theorem required : L.required Idx.probe := trivial

theorem before_equivalent :
    EquivalentUnder (generatedReachable EmptyCap)
      observe State.left State.right := by
  intro i hi
  rcases hi with ⟨hi⟩
  exact nomatch hi

theorem separates :
    observe Idx.probe State.left ≠ observe Idx.probe State.right := by
  decide

theorem generated_future_is_new :
    ¬ generatedReachable EmptyCap Idx.probe ∧
      generatedReachableAfter L Idx.probe := by
  exact residual_generates_genuinely_new_future L required absent

theorem generated_future_refines_identity :
    EquivalentUnder (generatedReachable EmptyCap)
        observe State.left State.right ∧
    ¬ EquivalentUnder (generatedReachableAfter L)
        observe State.left State.right := by
  exact generated_capability_can_refine_identity
    observe L before_equivalent required absent separates

theorem ablation_removes_future :
    ¬ generatedReachableAfter
      (erasedLandscape : RequirementLandscape Idx EmptyCap) Idx.probe := by
  exact ablation_erases_generated_future L required absent

end Witness

#check canonicalFutureInterface
#check canonical_before_iff_generated
#check canonical_after_iff_generated
#check old_generated_futures_embed
#check residual_generates_genuinely_new_future
#check ablation_erases_generated_future
#check generated_capability_can_refine_identity
#check Witness.generated_future_is_new
#check Witness.generated_future_refines_identity
#check Witness.ablation_removes_future

end CapabilityGeneratedFutureInterface
