import NewConsequenceInducesHypothesisUniverse
import DevelopmentAsOperationalJoin

namespace ConsequenceSelectedResidualForcesOperationalJoin

open VerifierOutcomeCannotIdentifyExactContextGrammar
open NewConsequenceSeparatesContextGrammar
open VersionSpaceInducesDecidingContext
open NewConsequenceInducesHypothesisUniverse
open DevelopmentAsOperationalJoin

/-- Operational evidence remembers where a verifier observation was made and
    the profile returned there.  The profile is not interpreted as hidden
    syntax. -/
abbrev OperationalEvidence := Bool × (Bool → Prop)

/-- The evidence already retained before asking the consequence-selected next
    question. -/
def currentEvidence : OperationalEvidence :=
  (true, currentProfile)

/-- The next evidence item is not supplied to the repair operator.  Its context
    is the splitter induced by current version-space ambiguity, and its profile
    is the verifier result returned at that induced context. -/
def nextEvidence : OperationalEvidence :=
  (generatedDecidingContext.1, observedNextProfile)

/-- Current consequence image: at this stage only the already observed evidence
    item is retained. -/
def currentImage : Image OperationalEvidence :=
  fun e => e = currentEvidence

/-- Residual extraction is state-sensitive.  The consequence-selected evidence
    is required exactly while it is absent.  Once realized, this residual
    extinguishes itself. -/
def consequenceRequired (I : Image OperationalEvidence) : Image OperationalEvidence :=
  fun e => ¬ I nextEvidence ∧ e = nextEvidence

/-- The version-space geometry, rather than a supplied candidate query, fixes
    the next observation site in this witness. -/
theorem next_evidence_uses_induced_deciding_context :
    nextEvidence.1 = generatedDecidingContext.1 := by
  rfl

theorem next_context_is_forced_by_current_ambiguity :
    (∃ G₁ G₂ : VersionSpace, G₁.1 ≠ G₂.1) ∧
    (∀ d : DecidingContext, d.1 = nextEvidence.1) := by
  constructor
  · exact ⟨negVersion, constVersion, version_space_contains_distinct_grammars⟩
  · intro d
    simpa [nextEvidence] using deciding_context_is_unique d

/-- The returned verifier profile is genuinely deciding: it retains one
    currently compatible hypothesis and rejects another. -/
theorem returned_profile_is_information_gaining :
    RefinedCompatible observedNextProfile grammarNeg ∧
    Compatible grammarConst ∧
    ¬ RefinedCompatible observedNextProfile grammarConst := by
  exact ⟨neg_survives_refined_universe,
    const_was_currently_compatible,
    const_eliminated_by_new_consequence⟩

/-- Because the consequence-selected site differs from the current site, the
    resulting evidence item is genuinely absent from the current operational
    image. -/
theorem next_evidence_absent_before :
    ¬ currentImage nextEvidence := by
  intro h
  have hctx : nextEvidence.1 = currentEvidence.1 := congrArg Prod.fst h
  simp [nextEvidence, currentEvidence, generatedDecidingContext] at hctx

/-- Hence the state-sensitive residual extractor emits the newly observed
    evidence at the current state. -/
theorem current_residual_requires_next_evidence :
    consequenceRequired currentImage nextEvidence := by
  exact ⟨next_evidence_absent_before, rfl⟩

theorem current_residual_not_contained :
    ¬ ImageLe (consequenceRequired currentImage) currentImage := by
  intro hcontained
  exact next_evidence_absent_before
    (hcontained nextEvidence current_residual_requires_next_evidence)

/-- The developmental successor is the generic operational join.  No repair
    kind, raw syntax, target carrier, or hand-written target image is supplied
    here. -/
def firstSuccessor : Image OperationalEvidence :=
  develop consequenceRequired currentImage

/-- The derived residual necessarily causes strict developmental growth. -/
theorem consequence_selected_residual_forces_strict_growth :
    firstSuccessor ≠ currentImage := by
  exact residual_not_contained_implies_not_fixed
    consequenceRequired currentImage current_residual_not_contained

/-- The least join realizes the evidence generated by the selected context and
    verifier response. -/
theorem successor_realizes_derived_evidence :
    firstSuccessor nextEvidence := by
  exact Or.inr current_residual_requires_next_evidence

/-- The generic join theorem gives minimality of the end-to-end successor. -/
theorem successor_is_least_admissible :
    AdmissibleSuccessor currentImage
      (consequenceRequired currentImage) firstSuccessor ∧
    (∀ J, AdmissibleSuccessor currentImage
      (consequenceRequired currentImage) J → ImageLe firstSuccessor J) := by
  exact join_is_least_admissible_successor
    currentImage (consequenceRequired currentImage)

/-- Once the generated evidence has been realized, that same residual is no
    longer emitted. -/
theorem repaired_residual_is_contained :
    ImageLe (consequenceRequired firstSuccessor) firstSuccessor := by
  intro e hreq
  exact False.elim (hreq.1 successor_realizes_derived_evidence)

/-- Therefore the repaired state is a fixed point with respect to this resolved
    residual.  Future development requires a genuinely new residual exposed by
    the changed consequence state. -/
theorem repaired_state_fixed_for_resolved_residual :
    develop consequenceRequired firstSuccessor = firstSuccessor := by
  exact (develop_fixed_iff_residual_closed consequenceRequired firstSuccessor).2
    repaired_residual_is_contained

/-- End-to-end theorem: current consequence leaves ambiguity; ambiguity induces
    the deciding context; the returned verifier consequence changes the viable
    hypothesis set; absence of that induced evidence becomes the residual;
    generic development adds its least operational join; and satisfying it
    extinguishes that residual.

    Remaining boundary: the external verifier/world supplies the actual result
    at the induced context, and the Bool witness carrier remains fixed. -/
theorem consequence_selected_residual_forces_least_operational_development :
    (∃ G₁ G₂ : VersionSpace, G₁.1 ≠ G₂.1) ∧
    (∀ d : DecidingContext, d.1 = nextEvidence.1) ∧
    RefinedCompatible observedNextProfile grammarNeg ∧
    Compatible grammarConst ∧
    ¬ RefinedCompatible observedNextProfile grammarConst ∧
    (¬ ImageLe (consequenceRequired currentImage) currentImage) ∧
    firstSuccessor ≠ currentImage ∧
    firstSuccessor nextEvidence ∧
    (∀ J, AdmissibleSuccessor currentImage
      (consequenceRequired currentImage) J → ImageLe firstSuccessor J) ∧
    develop consequenceRequired firstSuccessor = firstSuccessor := by
  exact ⟨
    ⟨negVersion, constVersion, version_space_contains_distinct_grammars⟩,
    next_context_is_forced_by_current_ambiguity.2,
    neg_survives_refined_universe,
    const_was_currently_compatible,
    const_eliminated_by_new_consequence,
    current_residual_not_contained,
    consequence_selected_residual_forces_strict_growth,
    successor_realizes_derived_evidence,
    successor_is_least_admissible.2,
    repaired_state_fixed_for_resolved_residual⟩

#check next_context_is_forced_by_current_ambiguity
#check returned_profile_is_information_gaining
#check next_evidence_absent_before
#check current_residual_requires_next_evidence
#check current_residual_not_contained
#check consequence_selected_residual_forces_strict_growth
#check successor_realizes_derived_evidence
#check successor_is_least_admissible
#check repaired_residual_is_contained
#check repaired_state_fixed_for_resolved_residual
#check consequence_selected_residual_forces_least_operational_development

end ConsequenceSelectedResidualForcesOperationalJoin
