import VerifierOutcomeCannotIdentifyExactHypothesisUniverse

namespace ConsequenceRefinesHypothesisUniverse

open VerifierOutcomeCannotIdentifyExactContextGrammar
open NewConsequenceSeparatesContextGrammar
open VersionSpaceInducesDecidingContext

/-- The refinement operator is consequence-driven: it receives only the newly
    observed verifier profile at the consequence-selected deciding context.  It
    is not given a privileged grammar or a distinguished grammar pair. -/
def RefinedBy (newProfile : Bool → Prop) : ContextGrammar Bool → Prop :=
  fun G =>
    Compatible G ∧
    OutcomeProfile G verifier generatedDecidingContext.1 = newProfile

/-- In the witness world the new verifier observation is produced at the
    consequence-selected deciding context.  The refinement operator above sees
    only this profile, not the generating grammar. -/
def observedNewProfile : Bool → Prop :=
  OutcomeProfile grammarNeg verifier generatedDecidingContext.1

/-- The next admissible hypothesis space is generated from current compatibility
    plus the new verifier consequence. -/
def NextHypothesisSpace : ContextGrammar Bool → Prop :=
  RefinedBy observedNewProfile

/-- The current consequence admits the negation grammar. -/
theorem neg_is_currently_admissible : Compatible grammarNeg := by
  rfl

/-- The current consequence also admits the constant grammar, so the current
    hypothesis space is genuinely ambiguous. -/
theorem const_is_currently_admissible : Compatible grammarConst := by
  exact same_outcome_profile.symm

/-- The consequence-selected context separates the two surviving witness
    grammars. -/
theorem generated_context_separates_witnesses :
    OutcomeProfile grammarNeg verifier generatedDecidingContext.1 ≠
      OutcomeProfile grammarConst verifier generatedDecidingContext.1 := by
  intro hprofiles
  have hpoint := congrFun hprofiles true
  have hneg : OutcomeProfile grammarNeg verifier generatedDecidingContext.1 true := by
    simpa [generatedDecidingContext] using neg_grammar_reaches_true_from_false
  have hconst : OutcomeProfile grammarConst verifier generatedDecidingContext.1 true :=
    hpoint.mp hneg
  exact const_grammar_cannot_reach_true_from_false (by
    simpa [generatedDecidingContext] using hconst)

/-- The world that generated the new verifier profile remains admissible after
    consequence-driven refinement. -/
theorem neg_survives_refinement : NextHypothesisSpace grammarNeg := by
  exact ⟨neg_is_currently_admissible, rfl⟩

/-- A hypothesis that was observationally indistinguishable before the new
    consequence is now excluded by that consequence. -/
theorem const_is_rejected_by_refinement : ¬ NextHypothesisSpace grammarConst := by
  intro h
  exact generated_context_separates_witnesses h.2.symm

/-- Consequence-driven refinement preserves every old constraint. -/
theorem refinement_preserves_current_constraints :
    ∀ G, NextHypothesisSpace G → Compatible G := by
  intro G h
  exact h.1

/-- The new consequence strictly refines the current admissible hypothesis
    universe: no candidate is added, and at least one previously admissible
    candidate is removed. -/
theorem new_consequence_strictly_refines_hypothesis_universe :
    (∀ G, NextHypothesisSpace G → Compatible G) ∧
    (∃ G, Compatible G ∧ ¬ NextHypothesisSpace G) := by
  exact ⟨
    refinement_preserves_current_constraints,
    ⟨grammarConst, const_is_currently_admissible, const_is_rejected_by_refinement⟩⟩

/-- The next hypothesis universe is generated by observable data only: current
    consequence compatibility and the new verifier profile at the induced
    deciding context.  No exact hidden universe is reconstructed. -/
theorem consequence_generates_next_admissible_hypothesis_space :
    NextHypothesisSpace = RefinedBy observedNewProfile ∧
    NextHypothesisSpace grammarNeg ∧
    ¬ NextHypothesisSpace grammarConst ∧
    (∀ G, NextHypothesisSpace G → Compatible G) := by
  exact ⟨rfl, neg_survives_refinement, const_is_rejected_by_refinement,
    refinement_preserves_current_constraints⟩

#check generated_context_separates_witnesses
#check new_consequence_strictly_refines_hypothesis_universe
#check consequence_generates_next_admissible_hypothesis_space

end ConsequenceRefinesHypothesisUniverse
