import ConsequenceSelectsObligationGenerator

universe u v

namespace ConsequenceCompilesObligationGenerator

open GenericResidualCompletion
open ResidualGeneratesNextObligation
open ConsequenceSelectsObligationGenerator

/-- A verifier consequence over currently realized token pairs compiles directly
    into the obligation-forming rule.  No generator identity, candidate pool, or
    repair-kind tag is supplied. -/
def compileGenerator
    {S : CapabilityState.{u,v}}
    (C : RealizedToken S → RealizedToken S → Bool) : Generator S where
  forms := fun left right => C left right = true

/-- Erasing verifier consequence yields a compiled generator that forms no
    obligations at all. -/
def erasedConsequence
    {S : CapabilityState.{u,v}} : RealizedToken S → RealizedToken S → Bool :=
  fun _ _ => false

/-- The all-false consequence has an empty generated obligation carrier. -/
theorem erased_consequence_generates_no_obligations
    {S : CapabilityState.{u,v}} :
    ¬ Nonempty (GeneratedObligation S (compileGenerator (erasedConsequence (S := S)))) := by
  intro h
  rcases h with ⟨o⟩
  simp [compileGenerator, erasedConsequence] at o.admissible

/-- Changing only verifier consequence changes the generated language even
    though the compilation mechanism itself is unchanged. -/
theorem changing_consequence_changes_generated_language
    {S : CapabilityState.{u,v}} (left right : RealizedToken S) :
    (compileGenerator (fun _ _ => true)).forms left right ∧
    ¬ (compileGenerator (fun _ _ => false)).forms left right := by
  simp [compileGenerator]

/-- Once a lower residual has been repaired, acceptance of the newly available
    target token paired with a retained anchor directly produces a higher
    obligation.  There is no intermediate search over generator identities. -/
def consequenceGeneratedObligation
    {S : CapabilityState.{u,v}} (r : VerifiedResidual S)
    {anchor : S.Obligation} (hanchor : S.Realize anchor)
    (C : RealizedToken (complete S (generatedDemand r)) →
      RealizedToken (complete S (generatedDemand r)) → Bool)
    (haccept : C (generatedTargetToken r) (retainedToken hanchor) = true) :
    GeneratedObligation (complete S (generatedDemand r)) (compileGenerator C) where
  left := generatedTargetToken r
  right := retainedToken hanchor
  admissible := haccept

/-- Fresh obligations generated by compiled consequence begin unrealized and can
    therefore be returned by the verifier as structured residuals. -/
def consequenceGeneratedResidual
    {S : CapabilityState.{u,v}} (r : VerifiedResidual S)
    {anchor : S.Obligation} (hanchor : S.Realize anchor)
    (C : RealizedToken (complete S (generatedDemand r)) →
      RealizedToken (complete S (generatedDemand r)) → Bool)
    (haccept : C (generatedTargetToken r) (retainedToken hanchor) = true) :
    VerifiedResidual
      (generatedState (complete S (generatedDemand r)) (compileGenerator C)) where
  target := consequenceGeneratedObligation r hanchor C haccept
  unrealized := by
    intro h
    rcases h with ⟨h⟩
    exact Empty.elim h

/-- End-to-end theorem: lower verified failure creates the token needed by a
    verifier consequence; the consequence itself compiles into the next
    obligation-forming rule; its accepted pair becomes a genuinely fresh
    residual; and the unchanged semantic-kind-blind free completion repairs it.

    This removes the externally supplied generator pool from the previous
    theorem.  The binary token-pair signature is still supplied, so this does
    not claim unrestricted ontology invention. -/
theorem consequence_compiles_next_obligation_language
    {S : CapabilityState.{u,v}} (r : VerifiedResidual S)
    {anchor : S.Obligation} (hanchor : S.Realize anchor)
    (C : RealizedToken (complete S (generatedDemand r)) →
      RealizedToken (complete S (generatedDemand r)) → Bool)
    (haccept : C (generatedTargetToken r) (retainedToken hanchor) = true) :
    (¬ Nonempty (TargetAnchored S r.target anchor)) ∧
    Nonempty
      ((complete
        (generatedState (complete S (generatedDemand r)) (compileGenerator C))
        (generatedDemand
          (consequenceGeneratedResidual r hanchor C haccept))).Realize
        (consequenceGeneratedResidual r hanchor C haccept).target) ∧
    (¬ Nonempty
      (GeneratedObligation
        (complete S (generatedDemand r))
        (compileGenerator
          (erasedConsequence
            (S := complete S (generatedDemand r)))))) ∧
    (¬ Nonempty
      (TargetAnchored (complete S (erasedDemand S)) r.target anchor)) := by
  refine ⟨target_cannot_generate_next_obligation_before_repair r, ?_, ?_,
    lower_failure_ablation_blocks_next_obligation_genesis r⟩
  · exact failure_forces_target_realization
      (consequenceGeneratedResidual r hanchor C haccept)
  · exact erased_consequence_generates_no_obligations

#check compileGenerator
#check erased_consequence_generates_no_obligations
#check changing_consequence_changes_generated_language
#check consequenceGeneratedObligation
#check consequenceGeneratedResidual
#check consequence_compiles_next_obligation_language

end ConsequenceCompilesObligationGenerator
