import GenericResidualCompletion
import ResidualGeneratesNextObligation
import ConsequenceDeterminesSelection

universe u v

namespace ConsequenceSelectsObligationGenerator

open GenericResidualCompletion
open ResidualGeneratesNextObligation
open ConsequenceDeterminesSelection

/-- Anonymous candidate for forming higher obligations from two currently
    realized tokens.  No identity/composition/coherence tag is present. -/
structure Generator (S : CapabilityState.{u,v}) where
  forms : RealizedToken S → RealizedToken S → Prop

/-- An obligation generated by a selected candidate. -/
structure GeneratedObligation
    (S : CapabilityState.{u,v}) (G : Generator S) where
  left : RealizedToken S
  right : RealizedToken S
  admissible : G.forms left right

/-- Fresh generated obligations begin unrealized. -/
def generatedState
    (S : CapabilityState.{u,v}) (G : Generator S) : CapabilityState where
  Obligation := GeneratedObligation S G
  Realize := fun _ => Empty

/-- The verifier judges anonymous generators by consequence.  Soundness means
    every accepted generator can form the particular token pair exposed by the
    current residual geometry. -/
structure GeneratorVerdict
    (S : CapabilityState.{u,v})
    (left right : RealizedToken S) where
  accepts : Generator S → Bool
  sound : ∀ G, accepts G = true → G.forms left right

/-- Under a unique verifier consequence, candidate ordering and identity do not
    choose the generator: the consequence predicate does. -/
theorem consequence_selects_generator
    {S : CapabilityState.{u,v}}
    {left right : RealizedToken S}
    (V : GeneratorVerdict S left right)
    (pool : List (Generator S)) (seed : Generator S)
    (hmem : seed ∈ pool)
    (huniq : UniqueSeparator V.accepts seed) :
    selectByConsequence V.accepts pool = some seed := by
  exact unique_separator_selected V.accepts pool seed hmem huniq

/-- Once the lower residual has been repaired, an accepted generator can form a
    genuinely new higher obligation from the newly available target token and a
    retained anchor. -/
def generatedHigherObligation
    {S : CapabilityState.{u,v}} (r : VerifiedResidual S)
    {anchor : S.Obligation} (hanchor : S.Realize anchor)
    (G : Generator (complete S (generatedDemand r)))
    (hforms : G.forms (generatedTargetToken r) (retainedToken hanchor)) :
    GeneratedObligation (complete S (generatedDemand r)) G where
  left := generatedTargetToken r
  right := retainedToken hanchor
  admissible := hforms

/-- The verifier can now expose a residual over the consequence-selected
    generated obligation. -/
def generatedHigherResidual
    {S : CapabilityState.{u,v}} (r : VerifiedResidual S)
    {anchor : S.Obligation} (hanchor : S.Realize anchor)
    (G : Generator (complete S (generatedDemand r)))
    (hforms : G.forms (generatedTargetToken r) (retainedToken hanchor)) :
    VerifiedResidual (generatedState (complete S (generatedDemand r)) G) where
  target := generatedHigherObligation r hanchor G hforms
  unrealized := by
    intro h
    rcases h with ⟨h⟩
    exact Empty.elim h

/-- End-to-end theorem: consequence selects an anonymous generator; verifier
    soundness supplies its admissible higher obligation; the same generic
    residual-completion operator repairs the resulting higher residual.  If the
    consequence channel is erased, no generator is selected; if the lower
    residual is erased, the target token needed by every such higher obligation
    remains unavailable. -/
theorem consequence_selects_how_next_necessity_is_formed
    {S : CapabilityState.{u,v}} (r : VerifiedResidual S)
    {anchor : S.Obligation} (hanchor : S.Realize anchor)
    (pool : List (Generator (complete S (generatedDemand r))))
    (seed : Generator (complete S (generatedDemand r)))
    (V : GeneratorVerdict
      (complete S (generatedDemand r))
      (generatedTargetToken r)
      (retainedToken hanchor))
    (hmem : seed ∈ pool)
    (huniq : UniqueSeparator V.accepts seed) :
    selectByConsequence V.accepts pool = some seed ∧
    Nonempty
      ((complete
        (generatedState (complete S (generatedDemand r)) seed)
        (generatedDemand
          (generatedHigherResidual r hanchor seed (V.sound seed huniq.1)))).Realize
        (generatedHigherResidual r hanchor seed (V.sound seed huniq.1)).target) ∧
    selectByConsequence (fun _ : Generator (complete S (generatedDemand r)) => false) pool = none ∧
    (¬ Nonempty
      (TargetAnchored (complete S (erasedDemand S)) r.target anchor)) := by
  refine ⟨consequence_selects_generator V pool seed hmem huniq, ?_,
    no_consequence_no_selection pool,
    lower_failure_ablation_blocks_next_obligation_genesis r⟩
  exact failure_forces_target_realization
    (generatedHigherResidual r hanchor seed (V.sound seed huniq.1))

#check consequence_selects_generator
#check generatedHigherObligation
#check generatedHigherResidual
#check consequence_selects_how_next_necessity_is_formed

end ConsequenceSelectsObligationGenerator
