import AnonymousInteractionConvergenceKernel

namespace DevelopmentalRetentionInducesInteractionOrientation

open DevelopmentAsOperationalJoin
open AnonymousInteractionConvergenceKernel

/-- Strict consequential retention is preservation plus genuine growth.  No
    clock, timestamp, ordered history, or semantic role is part of the notion. -/
def StrictRetains (M N : Memory) : Prop :=
  ImageLe M N ∧ M ≠ N

/-- Preservation plus strict gain orients the pair of states: the reverse
    strict-retention relation is impossible. -/
theorem strict_retention_is_asymmetric {M N : Memory}
    (hMN : StrictRetains M N) :
    ¬ StrictRetains N M := by
  intro hNM
  apply hMN.2
  funext e
  apply propext
  constructor
  · exact hMN.1 e
  · exact hNM.1 e

/-- Mere difference cannot orient development.  If preservation is erased,
    `M ≠ N` contains exactly the same information as `N ≠ M`. -/
theorem bare_change_without_preservation_is_symmetric (M N : Memory) :
    (M ≠ N) ↔ (N ≠ M) := by
  constructor
  · intro h h'
    exact h h'.symm
  · intro h h'
    exact h h'.symm

/-- `e` precedes `f` when repeated application of the same frozen developmental
    step first acquires `e`, while `f` is still absent, and only the next step
    acquires `f`.  The chronology is therefore read from development itself. -/
def AcquisitionPrecedes
    (W : InteractionWorld) (M : Memory) (e f : Evidence) : Prop :=
  ¬ M e ∧
  step W M e ∧
  ¬ step W M f ∧
  step W (step W M) f

/-- A fixed point cannot generate any new acquisition precedence. -/
theorem fixed_state_has_no_acquisition_precedence
    (W : InteractionWorld) (M : Memory)
    (hFixed : step W M = M) (e f : Evidence) :
    ¬ AcquisitionPrecedes W M e f := by
  intro h
  have hOld : M e := by
    simpa only [hFixed] using h.2.1
  exact h.1 hOld

/-- Acquisition precedence is irreflexive without requiring a primitive time
    order: one item cannot both be present and absent after the same step. -/
theorem acquisition_precedence_irreflexive
    (W : InteractionWorld) (M : Memory) (e : Evidence) :
    ¬ AcquisitionPrecedes W M e e := by
  intro h
  exact h.2.2.1 h.2.1

/-- Each key is represented only by the response evidence supplied by the
    interaction world. -/
def responseEvidence (W : InteractionWorld) (q : Key) : Evidence :=
  (q, W.respond q)

/-- Development itself orients keys by the order in which their response
    evidence becomes consequentially retained under repeated frozen steps. -/
def developmentalOrientation
    (W : InteractionWorld) (M : Memory) (q r : Key) : Prop :=
  AcquisitionPrecedes W M (responseEvidence W q) (responseEvidence W r)

/-- Operational first-coordinate equivalence for a Prop-valued interaction. -/
def RowEquivalent
    (R : Key → Key → Prop) (x y : Key) : Prop :=
  ∀ z, R x z ↔ R y z

/-- Operational second-coordinate equivalence for a Prop-valued interaction. -/
def ColEquivalent
    (R : Key → Key → Prop) (x y : Key) : Prop :=
  ∀ z, R z x ↔ R z y

/-- The first serial transition is strict retention generated by the frozen
    interaction kernel. -/
theorem serial_s0_strictly_retained_by_s1 : StrictRetains s0 s1 := by
  constructor
  · simpa [s1] using step_preserves serialWorld s0
  · exact serial_step0_strict

/-- The second serial transition is another strict retention step under the
    same unchanged kernel. -/
theorem serial_s1_strictly_retained_by_s2 : StrictRetains s1 s2 := by
  constructor
  · simpa [s2] using step_preserves serialWorld s1
  · exact serial_step1_strict

/-- The world-generated residual really requires the first response at the
    empty state; this is not arbitrary internal growth. -/
theorem serial_e0_required_s0 : Required serialWorld s0 e0 := by
  exact ⟨Key.k0, serial_k0_available_s0, serial_e0_absent_s0, rfl⟩

/-- After the first response has been retained, the world-generated residual
    requires the newly reachable second response. -/
theorem serial_e1_required_s1 : Required serialWorld s1 e1 := by
  exact ⟨Key.k1, serial_k1_available_s1, serial_e1_absent_s1, rfl⟩

/-- No external event ordering is supplied: two applications of `step` itself
    establish that the acquisition of `e0` precedes the acquisition of `e1`. -/
theorem serial_e0_precedes_e1 :
    AcquisitionPrecedes serialWorld s0 e0 e1 := by
  refine ⟨serial_e0_absent_s0, ?_, ?_, ?_⟩
  · simpa [s1] using serial_e0_in_s1
  · simpa [s1] using serial_e1_absent_s1
  · simpa [s1, s2] using serial_e1_in_s2

/-- The same frozen mechanism continues: `e1` precedes `e2` one level later. -/
theorem serial_e1_precedes_e2 :
    AcquisitionPrecedes serialWorld s1 e1 e2 := by
  refine ⟨serial_e1_absent_s1, ?_, ?_, ?_⟩
  · simpa [s2] using serial_e1_in_s2
  · simpa [s2] using serial_e2_absent_s2
  · simpa [s2, s3] using serial_e2_in_s3

/-- The derived chronology is directional: the second acquisition cannot
    precede the first in the same developmental trajectory. -/
theorem serial_e1_does_not_precede_e0 :
    ¬ AcquisitionPrecedes serialWorld s0 e1 e0 := by
  intro h
  have hIn : s1 e1 := by
    simpa [s1] using h.2.1
  exact serial_e1_absent_s1 hIn

/-- `e0` does not jump over `e1` to precede `e2` in one developmental cycle. -/
theorem serial_e0_does_not_precede_e2 :
    ¬ AcquisitionPrecedes serialWorld s0 e0 e2 := by
  intro h
  have hIn : s2 e2 := by
    simpa [s1, s2] using h.2.2.2
  exact serial_e2_absent_s2 hIn

/-- Since `e1` is not acquired by the first step, it cannot be the first member
    of any acquisition-precedence edge rooted at `s0`. -/
theorem serial_e1_precedes_nothing_from_s0 (f : Evidence) :
    ¬ AcquisitionPrecedes serialWorld s0 e1 f := by
  intro h
  have hIn : s1 e1 := by
    simpa [s1] using h.2.1
  exact serial_e1_absent_s1 hIn

/-- Likewise `e2` is unavailable too early to originate a precedence edge from
    the initial state. -/
theorem serial_e2_precedes_nothing_from_s0 (f : Evidence) :
    ¬ AcquisitionPrecedes serialWorld s0 e2 f := by
  intro h
  have hIn : s1 e2 := by
    simpa [s1] using h.2.1
  exact serial_e2_absent_s1 hIn

theorem serial_k0_precedes_k1 :
    developmentalOrientation serialWorld s0 Key.k0 Key.k1 := by
  simpa [developmentalOrientation, responseEvidence, serialWorld, e0, e1] using
    serial_e0_precedes_e1

theorem serial_k0_does_not_precede_k0 :
    ¬ developmentalOrientation serialWorld s0 Key.k0 Key.k0 := by
  simpa [developmentalOrientation, responseEvidence, serialWorld, e0] using
    acquisition_precedence_irreflexive serialWorld s0 e0

theorem serial_k0_does_not_precede_k2 :
    ¬ developmentalOrientation serialWorld s0 Key.k0 Key.k2 := by
  simpa [developmentalOrientation, responseEvidence, serialWorld, e0, e2] using
    serial_e0_does_not_precede_e2

theorem serial_k1_does_not_precede_k0 :
    ¬ developmentalOrientation serialWorld s0 Key.k1 Key.k0 := by
  simpa [developmentalOrientation, responseEvidence, serialWorld, e0, e1] using
    serial_e1_precedes_nothing_from_s0 e0

theorem serial_k1_does_not_precede_k2 :
    ¬ developmentalOrientation serialWorld s0 Key.k1 Key.k2 := by
  simpa [developmentalOrientation, responseEvidence, serialWorld, e1, e2] using
    serial_e1_precedes_nothing_from_s0 e2

theorem serial_k2_does_not_precede_k0 :
    ¬ developmentalOrientation serialWorld s0 Key.k2 Key.k0 := by
  simpa [developmentalOrientation, responseEvidence, serialWorld, e0, e2] using
    serial_e2_precedes_nothing_from_s0 e0

theorem serial_k2_does_not_precede_k1 :
    ¬ developmentalOrientation serialWorld s0 Key.k2 Key.k1 := by
  simpa [developmentalOrientation, responseEvidence, serialWorld, e1, e2] using
    serial_e2_precedes_nothing_from_s0 e1

theorem serial_k2_does_not_precede_k2 :
    ¬ developmentalOrientation serialWorld s0 Key.k2 Key.k2 := by
  simpa [developmentalOrientation, responseEvidence, serialWorld, e2] using
    acquisition_precedence_irreflexive serialWorld s0 e2

/-- The acquisition-derived relation has a genuine directional operational role
    split: `k0` and `k2` have the same incoming profile but different outgoing
    profiles, witnessed by the later acquisition of `k1`. -/
theorem acquisition_precedence_induces_directional_role :
    ColEquivalent (developmentalOrientation serialWorld s0) Key.k0 Key.k2 ∧
    ¬ RowEquivalent (developmentalOrientation serialWorld s0) Key.k0 Key.k2 := by
  constructor
  · intro z
    cases z with
    | k0 =>
        constructor
        · intro h
          exact False.elim (serial_k0_does_not_precede_k0 h)
        · intro h
          exact False.elim (serial_k0_does_not_precede_k2 h)
    | k1 =>
        constructor
        · intro h
          exact False.elim (serial_k1_does_not_precede_k0 h)
        · intro h
          exact False.elim (serial_k1_does_not_precede_k2 h)
    | k2 =>
        constructor
        · intro h
          exact False.elim (serial_k2_does_not_precede_k0 h)
        · intro h
          exact False.elim (serial_k2_does_not_precede_k2 h)
  · intro hEq
    have h := (hEq Key.k1).1 serial_k0_precedes_k1
    exact serial_k2_does_not_precede_k1 h

/-- The same retention event that creates the first acquisition-precedence edge
    also changes the reachable interaction space: `k1` is impossible before the
    step and available after it. -/
theorem first_strict_retention_exposes_new_interaction :
    ¬ Available serialWorld s0 Key.k1 ∧
    Available serialWorld s1 Key.k1 := by
  exact ⟨serial_k1_unavailable_s0, serial_k1_available_s1⟩

/-- At the eventual fixed point, repeating the same developmental mechanism can
    induce no further acquisition chronology. -/
theorem serial_fixed_point_has_no_new_precedence (e f : Evidence) :
    ¬ AcquisitionPrecedes serialWorld s3 e f := by
  exact fixed_state_has_no_acquisition_precedence serialWorld s3 serial_s3_fixed e f

/-- Bedrock assumption-deletion result.  No static `before`, timestamp, stage
    index, or externally ordered history is supplied.  Repeated application of
    the already frozen interaction kernel creates strict retained-state growth;
    that growth has an asymmetric acquisition order, induces a directional
    operational role, and the same retained consequence exposes a previously
    unavailable interaction.  The world response and unlock relation remain
    external boundaries. -/
theorem development_itself_generates_asymmetry_enabling_next_interaction :
    StrictRetains s0 s1 ∧
    StrictRetains s1 s2 ∧
    Required serialWorld s0 e0 ∧
    Required serialWorld s1 e1 ∧
    AcquisitionPrecedes serialWorld s0 e0 e1 ∧
    AcquisitionPrecedes serialWorld s1 e1 e2 ∧
    ¬ AcquisitionPrecedes serialWorld s0 e1 e0 ∧
    (ColEquivalent (developmentalOrientation serialWorld s0) Key.k0 Key.k2 ∧
      ¬ RowEquivalent (developmentalOrientation serialWorld s0) Key.k0 Key.k2) ∧
    ¬ Available serialWorld s0 Key.k1 ∧
    Available serialWorld s1 Key.k1 ∧
    (∀ e f, ¬ AcquisitionPrecedes serialWorld s3 e f) := by
  exact ⟨
    serial_s0_strictly_retained_by_s1,
    serial_s1_strictly_retained_by_s2,
    serial_e0_required_s0,
    serial_e1_required_s1,
    serial_e0_precedes_e1,
    serial_e1_precedes_e2,
    serial_e1_does_not_precede_e0,
    acquisition_precedence_induces_directional_role,
    serial_k1_unavailable_s0,
    serial_k1_available_s1,
    serial_fixed_point_has_no_new_precedence⟩

#check strict_retention_is_asymmetric
#check bare_change_without_preservation_is_symmetric
#check fixed_state_has_no_acquisition_precedence
#check serial_e0_precedes_e1
#check serial_e1_precedes_e2
#check acquisition_precedence_induces_directional_role
#check first_strict_retention_exposes_new_interaction
#check serial_fixed_point_has_no_new_precedence
#check development_itself_generates_asymmetry_enabling_next_interaction

end DevelopmentalRetentionInducesInteractionOrientation
