universe u v

namespace GenericResidualCompletion

/-- A capability state exposes only a family of obligations and the currently
    available realizers of each obligation.  The completion mechanism is not
    told whether an obligation means identity, composition, coherence, a proof,
    a program, or any other semantic kind. -/
structure CapabilityState where
  Obligation : Type u
  Realize : Obligation → Type v

/-- A verifier-certified residual names one obligation that the present state
    cannot realize.  This is the minimal structured information retained from
    failure. -/
structure VerifiedResidual (S : CapabilityState) where
  target : S.Obligation
  unrealized : ¬ Nonempty (S.Realize target)

/-- A verifier-certified demand is a predicate on obligations. -/
structure CertifiedDemand (S : CapabilityState) where
  demanded : S.Obligation → Prop

/-- The residual itself induces exactly one demand; no semantic repair class is
    supplied to the completion operator. -/
def generatedDemand {S : CapabilityState} (r : VerifiedResidual S) :
    CertifiedDemand S where
  demanded := fun o => o = r.target

/-- Ablation removes the residual-to-demand link. -/
def erasedDemand (S : CapabilityState) : CertifiedDemand S where
  demanded := fun _ => False

/-- Free witness completion: retain every old realizer and adjoin one formal
    realizer at every verifier-demanded obligation. -/
inductive CompletedRealize
    (S : CapabilityState) (D : CertifiedDemand S) :
    S.Obligation → Type v where
  | old {o} : S.Realize o → CompletedRealize S D o
  | forced {o} : D.demanded o → CompletedRealize S D o

/-- Completion changes neither the obligation language nor its semantic names;
    it changes only which obligations are inhabited. -/
def complete (S : CapabilityState) (D : CertifiedDemand S) : CapabilityState where
  Obligation := S.Obligation
  Realize := CompletedRealize S D

/-- Every old realization survives. -/
def includeOld {S : CapabilityState} {D : CertifiedDemand S}
    {o : S.Obligation} (h : S.Realize o) :
    (complete S D).Realize o :=
  CompletedRealize.old h

/-- Every certified demand obtains a realization. -/
def forcedRealizer {S : CapabilityState} {D : CertifiedDemand S}
    {o : S.Obligation} (h : D.demanded o) :
    (complete S D).Realize o :=
  CompletedRealize.forced h

/-- The certified residual's target is exactly generated by its own demand. -/
theorem target_is_generated_demand
    {S : CapabilityState} (r : VerifiedResidual S) :
    (generatedDemand r).demanded r.target := rfl

/-- The generic completion realizes the residual target. -/
theorem failure_forces_target_realization
    {S : CapabilityState} (r : VerifiedResidual S) :
    Nonempty ((complete S (generatedDemand r)).Realize r.target) := by
  exact ⟨forcedRealizer (target_is_generated_demand r)⟩

/-- The added witness is genuinely new. -/
theorem failure_forces_genuinely_new_realization
    {S : CapabilityState} (r : VerifiedResidual S) :
    (¬ Nonempty (S.Realize r.target)) ∧
    Nonempty ((complete S (generatedDemand r)).Realize r.target) := by
  exact ⟨r.unrealized, failure_forces_target_realization r⟩

/-- No unrelated absent obligation becomes inhabited. -/
theorem no_unrelated_realization
    {S : CapabilityState} (r : VerifiedResidual S)
    {o : S.Obligation} (hne : o ≠ r.target)
    (holdNone : ¬ Nonempty (S.Realize o)) :
    ¬ Nonempty ((complete S (generatedDemand r)).Realize o) := by
  intro h
  rcases h with ⟨h⟩
  cases h with
  | old oldh => exact holdNone ⟨oldh⟩
  | forced hd => exact hne hd

/-- Causal ablation: erase the structured residual and the missing realization
    remains missing. -/
theorem erasing_failure_signal_blocks_genesis
    {S : CapabilityState} (r : VerifiedResidual S) :
    ¬ Nonempty ((complete S (erasedDemand S)).Realize r.target) := by
  intro h
  rcases h with ⟨h⟩
  cases h with
  | old oldh => exact r.unrealized ⟨oldh⟩
  | forced hd => exact hd

/-- Any target realization family interpreting the old witnesses and every
    certified forced witness receives a canonical map from the completion. -/
def lift
    {S : CapabilityState} {D : CertifiedDemand S}
    (H : S.Obligation → Type v)
    (oldMap : ∀ {o}, S.Realize o → H o)
    (forcedMap : ∀ {o}, D.demanded o → H o) :
    ∀ {o}, CompletedRealize S D o → H o
  | _, .old h => oldMap h
  | _, .forced h => forcedMap h

/-- The free completion is unique on generators. -/
theorem lift_unique
    {S : CapabilityState} {D : CertifiedDemand S}
    (H : S.Obligation → Type v)
    (oldMap : ∀ {o}, S.Realize o → H o)
    (forcedMap : ∀ {o}, D.demanded o → H o)
    (f : ∀ {o}, CompletedRealize S D o → H o)
    (hold : ∀ {o} (h : S.Realize o), f (CompletedRealize.old h) = oldMap h)
    (hforced : ∀ {o} (h : D.demanded o),
      f (CompletedRealize.forced h) = forcedMap h) :
    ∀ {o} (h : CompletedRealize S D o),
      f h = lift H oldMap forcedMap h := by
  intro o h
  cases h with
  | old oldh => exact hold oldh
  | forced hd => exact hforced hd

/-- End-to-end seed theorem: for every verifier-certified unrealized obligation,
    the same semantic-kind-blind operator freely adds exactly the demanded
    realization, preserves old realizations, introduces nothing unrelated, and
    loses the gain under residual ablation. -/
theorem verified_failure_generates_least_required_structure
    {S : CapabilityState} (r : VerifiedResidual S) :
    (¬ Nonempty (S.Realize r.target)) ∧
    Nonempty ((complete S (generatedDemand r)).Realize r.target) ∧
    (¬ Nonempty ((complete S (erasedDemand S)).Realize r.target)) := by
  exact ⟨r.unrealized,
    failure_forces_target_realization r,
    erasing_failure_signal_blocks_genesis r⟩

/-- A deliberately coarse failure channel carries no residual geometry. -/
inductive TwoObligation where
  | left
  | right
  deriving DecidableEq

/-- Bare failure cannot determine two distinct required obligations: any
    selector seeing only the same Unit-valued failure signal must return the
    same target in both cases.  Structured residual information is therefore
    necessary for generic repair selection. -/
theorem bare_failure_bit_is_insufficient :
    ¬ ∃ choose : Unit → TwoObligation,
      choose () = TwoObligation.left ∧
      choose () = TwoObligation.right := by
  rintro ⟨choose, hleft, hright⟩
  have h : TwoObligation.left = TwoObligation.right := hleft.symm.trans hright
  cases h

#check target_is_generated_demand
#check failure_forces_target_realization
#check failure_forces_genuinely_new_realization
#check no_unrelated_realization
#check erasing_failure_signal_blocks_genesis
#check lift_unique
#check verified_failure_generates_least_required_structure
#check bare_failure_bit_is_insufficient

end GenericResidualCompletion
