import Std

namespace IdentityForcedAsMinimalCompletion

universe u v w

/-- The rock-bottom substrate: objects and directed transport only. -/
structure RawDirectedSubstrate where
  Obj : Type u
  Hom : Obj → Obj → Type v

/-- A verifier-certified requirement that selected objects must support self-transport.
    The certificate is intentionally opaque here: the completion depends only on which
    requirements have actually been certified. -/
structure CertifiedIdentityDemand (S : RawDirectedSubstrate) where
  demanded : S.Obj → Prop

/-- The free/minimal completion generated by a certified identity demand.
    It retains every old transport and adds exactly one formal constructor for each
    demanded self-transport, and nothing else. -/
inductive CompletedHom (S : RawDirectedSubstrate) (D : CertifiedIdentityDemand S) :
    S.Obj → S.Obj → Type (max v u) where
  | old {x y} : S.Hom x y → CompletedHom S D x y
  | forcedId {x} : D.demanded x → CompletedHom S D x x

/-- The completed directed substrate has the same objects. -/
def complete (S : RawDirectedSubstrate) (D : CertifiedIdentityDemand S) : RawDirectedSubstrate where
  Obj := S.Obj
  Hom := CompletedHom S D

/-- No old capability is discarded by completion. -/
def includeOld {S : RawDirectedSubstrate} {D : CertifiedIdentityDemand S}
    {x y : S.Obj} : S.Hom x y → (complete S D).Hom x y :=
  CompletedHom.old

/-- Every certified identity demand is satisfied after completion. -/
def satisfyDemand {S : RawDirectedSubstrate} {D : CertifiedIdentityDemand S}
    {x : S.Obj} (hx : D.demanded x) : Nonempty ((complete S D).Hom x x) :=
  ⟨CompletedHom.forcedId hx⟩

/-- The universal eliminator: any interpretation that preserves all old arrows and
    supplies witnesses for certified identities extends canonically to the completion. -/
def lift
    {S : RawDirectedSubstrate} {D : CertifiedIdentityDemand S}
    (H : S.Obj → S.Obj → Type w)
    (oldMap : ∀ {x y}, S.Hom x y → H x y)
    (idMap : ∀ {x}, D.demanded x → H x x) :
    ∀ {x y}, CompletedHom S D x y → H x y
  | _, _, CompletedHom.old h => oldMap h
  | _, _, CompletedHom.forcedId hx => idMap hx

@[simp] theorem lift_old
    {S : RawDirectedSubstrate} {D : CertifiedIdentityDemand S}
    (H : S.Obj → S.Obj → Type w)
    (oldMap : ∀ {x y}, S.Hom x y → H x y)
    (idMap : ∀ {x}, D.demanded x → H x x)
    {x y : S.Obj} (h : S.Hom x y) :
    lift H oldMap idMap (CompletedHom.old h) = oldMap h := rfl

@[simp] theorem lift_forcedId
    {S : RawDirectedSubstrate} {D : CertifiedIdentityDemand S}
    (H : S.Obj → S.Obj → Type w)
    (oldMap : ∀ {x y}, S.Hom x y → H x y)
    (idMap : ∀ {x}, D.demanded x → H x x)
    {x : S.Obj} (hx : D.demanded x) :
    lift H oldMap idMap (CompletedHom.forcedId hx) = idMap hx := rfl

/-- Initiality/leastness: an interpretation out of the completion is uniquely determined
    once its behavior on old transports and demanded identities is fixed. -/
theorem lift_unique
    {S : RawDirectedSubstrate} {D : CertifiedIdentityDemand S}
    (H : S.Obj → S.Obj → Type w)
    (oldMap : ∀ {x y}, S.Hom x y → H x y)
    (idMap : ∀ {x}, D.demanded x → H x x)
    (f : ∀ {x y}, CompletedHom S D x y → H x y)
    (hold : ∀ {x y} (h : S.Hom x y), f (CompletedHom.old h) = oldMap h)
    (hid : ∀ {x} (hx : D.demanded x), f (CompletedHom.forcedId hx) = idMap hx) :
    ∀ {x y} (h : CompletedHom S D x y), f h = lift H oldMap idMap h := by
  intro x y h
  cases h with
  | old h => exact hold h
  | forcedId hx => exact hid hx

/-- Completion does not invent an arrow between distinct endpoints unless one already
    existed in the raw substrate. -/
theorem no_new_transport_between_distinct
    {S : RawDirectedSubstrate} {D : CertifiedIdentityDemand S}
    {x y : S.Obj} (hne : x ≠ y)
    (holdNone : ¬ Nonempty (S.Hom x y)) :
    ¬ Nonempty ((complete S D).Hom x y) := by
  intro h
  rcases h with ⟨h⟩
  cases h with
  | old oldh => exact holdNone ⟨oldh⟩
  | forcedId hx => exact hne rfl

/-- At an undemanded point, completion adds no self-transport; any self-transport after
    completion must therefore have been present already. -/
theorem no_uncertified_self_transport_from_nothing
    {S : RawDirectedSubstrate} {D : CertifiedIdentityDemand S}
    {x : S.Obj}
    (hnot : ¬ D.demanded x)
    (holdNone : ¬ Nonempty (S.Hom x x)) :
    ¬ Nonempty ((complete S D).Hom x x) := by
  intro h
  rcases h with ⟨h⟩
  cases h with
  | old oldh => exact holdNone ⟨oldh⟩
  | forcedId hx => exact hnot hx

/-- A concrete witness that certified consequence can force identity as a genuine new
    capability rather than reveal an identity that was already present. -/
def emptySelf : RawDirectedSubstrate where
  Obj := Unit
  Hom := fun _ _ => Empty

def demandUnit : CertifiedIdentityDemand emptySelf where
  demanded := fun _ => True

theorem demanded_identity_is_genuinely_adjoined :
    (¬ Nonempty (emptySelf.Hom () ())) ∧
    Nonempty ((complete emptySelf demandUnit).Hom () ()) := by
  constructor
  · intro h
    rcases h with ⟨h⟩
    exact Empty.elim h
  · exact satisfyDemand trivial

/-- The complete criterion established here: certified obstruction does not derive an
    old identity; it forces the free, least extension satisfying exactly that demand. -/
def IdentityAsMinimalForcedCompletion : Prop :=
  (∀ (S : RawDirectedSubstrate) (D : CertifiedIdentityDemand S)
      (x : S.Obj), D.demanded x → Nonempty ((complete S D).Hom x x)) ∧
  (∀ (S : RawDirectedSubstrate) (D : CertifiedIdentityDemand S)
      (x y : S.Obj), x ≠ y → ¬ Nonempty (S.Hom x y) →
        ¬ Nonempty ((complete S D).Hom x y))

theorem identity_as_minimal_forced_completion : IdentityAsMinimalForcedCompletion := by
  constructor
  · intro S D x hx
    exact satisfyDemand hx
  · intro S D x y hne holdNone
    exact no_new_transport_between_distinct hne holdNone

#check satisfyDemand
#check lift_unique
#check no_new_transport_between_distinct
#check no_uncertified_self_transport_from_nothing
#check demanded_identity_is_genuinely_adjoined
#check identity_as_minimal_forced_completion

end IdentityForcedAsMinimalCompletion
