import KernelPurificationCycle2

namespace KernelPurificationCycle3

open IdentityForcedAsMinimalCompletion
open FailureForcesCompositionCompletion
open KernelPurificationCycle
open KernelPurificationCycle2

universe u v z

/-- Purified constructive kernel: an indexed family of retained structure plus
    an indexed proposition of consequence-forced generators.  No transport,
    identity, composition, endpoint, or failure vocabulary occurs here. -/
inductive FreeAdjoin {I : Type u}
    (Old : I → Type v) (Gen : I → Prop) : I → Type v where
  | old {i : I} : Old i → FreeAdjoin Old Gen i
  | forced {i : I} : Gen i → FreeAdjoin Old Gen i

/-- Every retained inhabitant survives generic free adjunction. -/
def freeRetain {I : Type u} {Old : I → Type v} {Gen : I → Prop}
    {i : I} : Old i → FreeAdjoin Old Gen i :=
  FreeAdjoin.old

/-- Every certified generator is realized by generic free adjunction. -/
def freeGenerate {I : Type u} {Old : I → Type v} {Gen : I → Prop}
    {i : I} : Gen i → FreeAdjoin Old Gen i :=
  FreeAdjoin.forced

/-- Universal eliminator: interpreting old structure and forced generators is
    sufficient to interpret the completed family. -/
def freeLift {I : Type u}
    {Old : I → Type v} {Gen : I → Prop}
    (H : I → Type z)
    (oldMap : ∀ {i : I}, Old i → H i)
    (genMap : ∀ {i : I}, Gen i → H i) :
    ∀ {i : I}, FreeAdjoin Old Gen i → H i
  | _, .old h => oldMap h
  | _, .forced g => genMap g

theorem freeLift_old {I : Type u}
    {Old : I → Type v} {Gen : I → Prop}
    (H : I → Type z)
    (oldMap : ∀ {i : I}, Old i → H i)
    (genMap : ∀ {i : I}, Gen i → H i)
    {i : I} (h : Old i) :
    freeLift H oldMap genMap (FreeAdjoin.old h) = oldMap h := rfl

theorem freeLift_forced {I : Type u}
    {Old : I → Type v} {Gen : I → Prop}
    (H : I → Type z)
    (oldMap : ∀ {i : I}, Old i → H i)
    (genMap : ∀ {i : I}, Gen i → H i)
    {i : I} (g : Gen i) :
    freeLift H oldMap genMap (FreeAdjoin.forced g) = genMap g := rfl

/-- Pointwise uniqueness of the generic extension once its action on retained
    structure and new generators is fixed. -/
theorem freeLift_unique {I : Type u}
    {Old : I → Type v} {Gen : I → Prop}
    (H : I → Type z)
    (oldMap : ∀ {i : I}, Old i → H i)
    (genMap : ∀ {i : I}, Gen i → H i)
    (f : ∀ {i : I}, FreeAdjoin Old Gen i → H i)
    (hold : ∀ {i : I} (h : Old i), f (FreeAdjoin.old h) = oldMap h)
    (hgen : ∀ {i : I} (g : Gen i), f (FreeAdjoin.forced g) = genMap g) :
    ∀ {i : I} (q : FreeAdjoin Old Gen i),
      f q = freeLift H oldMap genMap q := by
  intro i q
  cases q with
  | old h => exact hold h
  | forced g => exact hgen g

/-- Transport-indexed data is only one interpretation of the generic family. -/
def TransportIndex (S : RawDirectedSubstrate) := S.Obj × S.Obj

def oldTransportFamily (S : RawDirectedSubstrate) : TransportIndex S → Type :=
  fun p => S.Hom p.1 p.2

def demandedGeneratorFamily
    (S : RawDirectedSubstrate) (D : CertifiedTransportDemand S) :
    TransportIndex S → Prop :=
  fun p => D.demanded p.1 p.2

/-- Existing transport completion compiles into the purified free-adjoin kernel. -/
def transportToFree
    {S : RawDirectedSubstrate} {D : CertifiedTransportDemand S}
    {x y : S.Obj} :
    CompletedTransportHom S D x y →
      FreeAdjoin (oldTransportFamily S) (demandedGeneratorFamily S D) (x, y)
  | .old h => .old h
  | .forced g => .forced g

/-- And every generic free-adjoin term at a transport index decodes back. -/
def freeToTransport
    {S : RawDirectedSubstrate} {D : CertifiedTransportDemand S}
    {x y : S.Obj} :
    FreeAdjoin (oldTransportFamily S) (demandedGeneratorFamily S D) (x, y) →
      CompletedTransportHom S D x y
  | .old h => .old h
  | .forced g => .forced g

theorem transport_free_roundtrip
    {S : RawDirectedSubstrate} {D : CertifiedTransportDemand S}
    {x y : S.Obj} (h : CompletedTransportHom S D x y) :
    freeToTransport (transportToFree h) = h := by
  cases h <;> rfl

theorem free_transport_roundtrip
    {S : RawDirectedSubstrate} {D : CertifiedTransportDemand S}
    {x y : S.Obj}
    (h : FreeAdjoin (oldTransportFamily S) (demandedGeneratorFamily S D) (x, y)) :
    transportToFree (freeToTransport h) = h := by
  cases h <;> rfl

/-- Explicit two-sided equivalence data, stated without importing any extra
    equivalence notation: transport completion and generic free adjunction
    translate into each other with both round trips equal to identity. -/
theorem transport_completion_is_generic_free_adjoin
    {S : RawDirectedSubstrate} {D : CertifiedTransportDemand S}
    {x y : S.Obj} :
    (∀ h : CompletedTransportHom S D x y,
      freeToTransport (transportToFree h) = h) ∧
    (∀ h : FreeAdjoin (oldTransportFamily S) (demandedGeneratorFamily S D) (x, y),
      transportToFree (freeToTransport h) = h) := by
  exact ⟨transport_free_roundtrip, free_transport_roundtrip⟩

/-- A demanded transport is generated by the generic kernel, with transport
    appearing only in the indexing interpretation. -/
theorem demanded_transport_is_generic_generation
    {S : RawDirectedSubstrate} {D : CertifiedTransportDemand S}
    {x y : S.Obj} (hxy : D.demanded x y) :
    Nonempty
      (FreeAdjoin (oldTransportFamily S) (demandedGeneratorFamily S D) (x, y)) := by
  exact ⟨FreeAdjoin.forced hxy⟩

/-- Cycle-3 decision: identity and composition completions both factor through
    a kernel whose primitives contain neither concept and not even transport. -/
theorem transport_specific_completion_falls_off
    {S : RawDirectedSubstrate}
    (i : FailureForcesIdentityCompletion.FailedContinuation S)
    (c : FailureForcesCompositionCompletion.FailedComposition S) :
    Nonempty
      (FreeAdjoin (oldTransportFamily S) (demandedGeneratorFamily S (identityDemand i))
        (i.start, i.start)) ∧
    Nonempty
      (FreeAdjoin (oldTransportFamily S) (demandedGeneratorFamily S (compositionDemand c))
        (c.source, c.target)) := by
  constructor
  · exact demanded_transport_is_generic_generation
      (endpoint_is_demanded (fromIdentityFailure i))
  · exact demanded_transport_is_generic_generation
      (endpoint_is_demanded (fromCompositionFailure c))

#check freeLift_unique
#check transport_completion_is_generic_free_adjoin
#check demanded_transport_is_generic_generation
#check transport_specific_completion_falls_off

end KernelPurificationCycle3
