import KernelPurificationCycle3

namespace KernelPurificationCycle4

open KernelPurificationCycle3

universe u v z

/-- Negative/constraining polarity of consequential repair: this is the exact
    algebraic fragment used by the MSI extensional kernel. -/
structure MeetRepair (L : Type u) where
  meet : L → L → L
  top : L
  idem : ∀ a, meet a a = a
  comm : ∀ a b, meet a b = meet b a
  assoc : ∀ a b c, meet (meet a b) c = meet a (meet b c)
  top_right : ∀ a, meet a top = a

/-- Refinement order generated by meet. -/
def Refines {L : Type u} (M : MeetRepair L) (a b : L) : Prop :=
  M.meet a b = a

theorem meet_refines_left {L : Type u} (M : MeetRepair L) (a b : L) :
    Refines M (M.meet a b) a := by
  unfold Refines
  rw [M.assoc, M.idem]

theorem meet_refines_right {L : Type u} (M : MeetRepair L) (a b : L) :
    Refines M (M.meet a b) b := by
  unfold Refines
  rw [M.assoc, M.idem]

/-- Universal property of negative repair: `meet a b` is the greatest retained
    refinement satisfying both the old interface state and the new verified
    constraint. -/
theorem meet_is_universal_constraint_repair
    {L : Type u} (M : MeetRepair L) (a b x : L)
    (hxa : Refines M x a) (hxb : Refines M x b) :
    Refines M x (M.meet a b) := by
  unfold Refines at hxa hxb ⊢
  rw [← M.assoc, hxa, hxb]

/-- The positive/generative polarity is exactly the generic free adjunction
    purified in Cycle 3.  It is universal in the opposite variance: maps out of
    the repair are uniquely determined by maps from retained structure and from
    consequence-forced generators. -/
theorem free_adjoin_is_universal_generator_repair
    {I : Type u} {Old : I → Type v} {Gen : I → Prop}
    (H : I → Type z)
    (oldMap : ∀ {i : I}, Old i → H i)
    (genMap : ∀ {i : I}, Gen i → H i)
    (f : ∀ {i : I}, FreeAdjoin Old Gen i → H i)
    (hold : ∀ {i : I} (h : Old i), f (FreeAdjoin.old h) = oldMap h)
    (hgen : ∀ {i : I} (g : Gen i), f (FreeAdjoin.forced g) = genMap g) :
    ∀ {i : I} (q : FreeAdjoin Old Gen i),
      f q = freeLift H oldMap genMap q := by
  exact freeLift_unique H oldMap genMap f hold hgen

/-- What fuses in Cycle 4 is not the concrete operations `meet` and
    `FreeAdjoin`; it is their universal-repair law.  Verified consequence has
    two polarities: constrain an over-permissive identification state, or
    generate structure whose absence blocks continuation. -/
structure UniversalRepairWitness : Prop where
  negative_universal :
    ∀ (L : Type) (M : MeetRepair L) (a b x : L),
      Refines M x a → Refines M x b → Refines M x (M.meet a b)
  positive_universal :
    ∀ (I : Type) (Old : I → Type) (Gen : I → Prop)
      (H : I → Type)
      (oldMap : ∀ {i : I}, Old i → H i)
      (genMap : ∀ {i : I}, Gen i → H i)
      (f : ∀ {i : I}, FreeAdjoin Old Gen i → H i),
      (∀ {i : I} (h : Old i), f (FreeAdjoin.old h) = oldMap h) →
      (∀ {i : I} (g : Gen i), f (FreeAdjoin.forced g) = genMap g) →
      ∀ {i : I} (q : FreeAdjoin Old Gen i),
        f q = freeLift H oldMap genMap q

/-- Cycle-4 decision: the common surviving abstraction is universal repair,
    while destructive refinement and constructive adjunction remain distinct
    polarities rather than being falsely identified as the same operation. -/
theorem consequential_repair_has_two_universal_polarities :
    UniversalRepairWitness := by
  constructor
  · intro L M a b x hxa hxb
    exact meet_is_universal_constraint_repair M a b x hxa hxb
  · intro I Old Gen H oldMap genMap f hold hgen i q
    exact free_adjoin_is_universal_generator_repair H oldMap genMap f hold hgen q

/-- A one-point adversarial witness that the two polarities are not literally
    interchangeable: meet-repair can strictly remove a Boolean permission,
    whereas free adjunction never deletes an old inhabitant. -/
def boolMeet : MeetRepair Bool where
  meet := (· && ·)
  top := true
  idem := by intro a; cases a <;> rfl
  comm := by intro a b; cases a <;> cases b <;> rfl
  assoc := by intro a b c; cases a <;> cases b <;> cases c <;> rfl
  top_right := by intro a; cases a <;> rfl

theorem negative_polarity_can_remove :
    boolMeet.meet true false = false := rfl

theorem positive_polarity_retains_old
    {I : Type u} {Old : I → Type v} {Gen : I → Prop}
    {i : I} (h : Old i) : Nonempty (FreeAdjoin Old Gen i) := by
  exact ⟨FreeAdjoin.old h⟩

/-- Therefore purification does not collapse the two directions into one
    concrete constructor.  What hardens is the deeper law: every justified
    change is characterized by a universal property, with polarity determined
    by whether consequence removes unsupported freedom or requires a missing
    generator. -/
theorem cycle4_polarity_obstruction :
    boolMeet.meet true false = false ∧
    (∀ (I : Type) (Old : I → Type) (Gen : I → Prop) (i : I),
      Old i → Nonempty (FreeAdjoin Old Gen i)) := by
  constructor
  · rfl
  · intro I Old Gen i h
    exact positive_polarity_retains_old h

#check meet_is_universal_constraint_repair
#check free_adjoin_is_universal_generator_repair
#check consequential_repair_has_two_universal_polarities
#check cycle4_polarity_obstruction

end KernelPurificationCycle4
