import KernelPurificationCycle10
import ReachabilityGeneratesConsequence

namespace KernelPurificationCycle11

open KernelPurificationCycle9
open KernelPurificationCycle10
open VerifiedConsequenceGenesis

universe u v w z

/-- The consequential requirement is synthesized from the interaction failure
    itself.  It is not passed to this cycle as a separate target predicate. -/
def failureConsequence
    {S : ReachabilityGeneratesConsequence.DirectedSubstrate}
    (r : ReachabilityGeneratesConsequence.DirectedFailure S) : S.Obj → Prop :=
  ReachabilityGeneratesConsequence.generatedProbe r

/-- The failure-generated consequence holds at the source and fails at the
    reached state, entirely by reflexive transport plus certified no-return. -/
theorem failure_consequence_separates
    {S : ReachabilityGeneratesConsequence.DirectedSubstrate}
    (r : ReachabilityGeneratesConsequence.DirectedFailure S) :
    failureConsequence r r.left ∧ ¬ failureConsequence r r.right := by
  exact ReachabilityGeneratesConsequence.directed_failure_generates_consequence r

/-- If the current representation collapses the failure endpoints, the
    consequence generated from the failure cannot factor through that
    representation.  No required consequence `c` is supplied. -/
theorem interaction_failure_forces_nonfactorization
    {S : ReachabilityGeneratesConsequence.DirectedSubstrate}
    {R : Type w} (q : S.Obj → R)
    (r : ReachabilityGeneratesConsequence.DirectedFailure S)
    (hcollapse : q r.left = q r.right) :
    ¬ FactorsThrough q (failureConsequence r) := by
  intro hfactor
  have hconst : failureConsequence r r.left = failureConsequence r r.right :=
    factorsThrough_implies_fiber_constancy q (failureConsequence r)
      hfactor r.left r.right hcollapse
  have hsep := failure_consequence_separates r
  have hright : failureConsequence r r.right := by
    exact Eq.mp hconst hsep.1
  exact hsep.2 hright

/-- Therefore the canonical full failed-pair support from Cycle 10 is nonempty
    for a consequence that was itself generated by the verifier-visible
    interaction failure. -/
theorem failure_generated_nonfactor_support_nonempty
    {S : ReachabilityGeneratesConsequence.DirectedSubstrate}
    {R : Type w} (q : S.Obj → R)
    (r : ReachabilityGeneratesConsequence.DirectedFailure S)
    (hcollapse : q r.left = q r.right) :
    Nonempty (ResidualIndex q (failureConsequence r)) := by
  exact nonfactorization_support_nonempty q (failureConsequence r)
    (interaction_failure_forces_nonfactorization q r hcollapse)

/-- The actual interaction pair is one member of the canonical support, but it
    is not selected as an input to the extension: the support contains every
    pair on which the representation loses the failure-generated consequence. -/
def interactionSupportWitness
    {S : ReachabilityGeneratesConsequence.DirectedSubstrate}
    {R : Type w} (q : S.Obj → R)
    (r : ReachabilityGeneratesConsequence.DirectedFailure S)
    (hcollapse : q r.left = q r.right) :
    ResidualIndex q (failureConsequence r) := by
  refine ⟨(r.left, r.right), hcollapse, ?_⟩
  intro heqv
  have hsep := failure_consequence_separates r
  exact hsep.2 (heqv.mp hsep.1)

/-- Existing consequence coordinates may be retained provided they are already
    representation-mediated. -/
def OldLanguageMediated
    {S : ReachabilityGeneratesConsequence.DirectedSubstrate}
    {I : Type v} {R : Type w}
    (L : ConsequenceLanguage S.Obj I) (q : S.Obj → R) : Prop :=
  LanguageFactorsThrough L q

/-- No candidate consequence, failed-pair selector, or new-coordinate identity
    is supplied: the interaction failure generates the required consequence;
    collapse generates the full non-factorization support; that support
    generates the new coordinate family. -/
theorem interaction_failure_generates_residual_language
    {S : ReachabilityGeneratesConsequence.DirectedSubstrate}
    {I : Type v} {R : Type w}
    (L : ConsequenceLanguage S.Obj I) (q : S.Obj → R)
    (r : ReachabilityGeneratesConsequence.DirectedFailure S)
    (hfactor : OldLanguageMediated L q)
    (hcollapse : q r.left = q r.right) :
    Nonempty (ResidualIndex q (failureConsequence r)) ∧
    (∀ p : ResidualIndex q (failureConsequence r),
      (∀ i : I,
        L.observe i ≠
          ResidualGeneratedProbeGenesis.generatedProbe (residualOfSupport p)) ∧
      (¬ (extendFromNonfactorSupport L q (failureConsequence r)).observe
          (Sum.inr p) p.1.1 ∧
        (extendFromNonfactorSupport L q (failureConsequence r)).observe
          (Sum.inr p) p.1.2)) := by
  exact global_nonfactorization_generates_residual_language
    L q (failureConsequence r) hfactor
    (interaction_failure_forces_nonfactorization q r hcollapse)

/-- Exact ablation on the source of consequence genesis: if reverse transport
    exists, the same transport-derived return observation cannot separate the
    two interaction endpoints, so this particular failure-generated
    non-factorization certificate disappears. -/
theorem reverse_transport_blocks_this_generated_consequence
    (S : ReachabilityGeneratesConsequence.DirectedSubstrate)
    (left right : S.Obj)
    (hback : Nonempty (S.Hom right left)) :
    ¬ (ReachabilityGeneratesConsequence.returnProbe S left left ∧
       ¬ ReachabilityGeneratesConsequence.returnProbe S left right) := by
  exact ReachabilityGeneratesConsequence.reverse_transport_erases_generated_separation
    S left right hback

/-- Cycle-11 decision: the required proposition is not an irreducible input in
    this interaction regime.  A verifier-certified reached-then-cannot-return
    event synthesizes the consequence that exposes the representation failure,
    after which Cycles 9-10 generate the residual language freely. -/
theorem supplied_required_consequence_eliminated_for_directed_failure
    {S : ReachabilityGeneratesConsequence.DirectedSubstrate}
    {I : Type v} {R : Type w}
    (L : ConsequenceLanguage S.Obj I) (q : S.Obj → R)
    (r : ReachabilityGeneratesConsequence.DirectedFailure S)
    (hfactor : OldLanguageMediated L q)
    (hcollapse : q r.left = q r.right) :
    (failureConsequence r r.left ∧ ¬ failureConsequence r r.right) ∧
    Nonempty (ResidualIndex q (failureConsequence r)) ∧
    Nonempty
      (Sum I (ResidualIndex q (failureConsequence r))) := by
  constructor
  · exact failure_consequence_separates r
  constructor
  · exact failure_generated_nonfactor_support_nonempty q r hcollapse
  · exact ⟨Sum.inr (interactionSupportWitness q r hcollapse)⟩

#check failure_consequence_separates
#check interaction_failure_forces_nonfactorization
#check failure_generated_nonfactor_support_nonempty
#check interactionSupportWitness
#check interaction_failure_generates_residual_language
#check reverse_transport_blocks_this_generated_consequence
#check supplied_required_consequence_eliminated_for_directed_failure

end KernelPurificationCycle11
