import Std

namespace ReachabilityGeneratesConsequence

universe u v

/-- Primitive directed substrate: objects, type-valued directed transport,
    and only reflexive transport.  No composition, observation basis,
    consequence family, endpoint equality test, or category is assumed. -/
structure DirectedSubstrate where
  Obj : Type u
  Hom : Obj → Obj → Type v
  refl : (x : Obj) → Hom x x

abbrev Probe (S : DirectedSubstrate) := S.Obj → Prop

/-- An interaction has reached `right` from `left`, but reverse transport
    back to `left` is verifier-certified impossible. -/
structure DirectedFailure (S : DirectedSubstrate) where
  left : S.Obj
  right : S.Obj
  forward : Nonempty (S.Hom left right)
  noBack : ¬ Nonempty (S.Hom right left)

/-- Generic transport-only probe synthesized from the failure: can the
    current point return to the failure's source?  This uses only `Hom`
    and the source already present in the failure; no equality test. -/
def returnProbe (S : DirectedSubstrate) (source : S.Obj) : Probe S :=
  fun z => Nonempty (S.Hom z source)

/-- The probe generated by this particular failed interaction. -/
def generatedProbe {S : DirectedSubstrate} (r : DirectedFailure S) : Probe S :=
  returnProbe S r.left

/-- Consequentiality is generated from the failure endpoints themselves:
    a probe matters when it holds at the source and fails at the reached
    point.  No externally supplied consequence predicate occurs. -/
def generatedCriterion {S : DirectedSubstrate}
    (r : DirectedFailure S) (p : Probe S) : Prop :=
  p r.left ∧ ¬ p r.right

/-- Reflexivity certifies the generated return probe at the source. -/
theorem generatedProbe_holds_at_source
    {S : DirectedSubstrate} (r : DirectedFailure S) :
    generatedProbe r r.left := by
  exact ⟨S.refl r.left⟩

/-- The verifier-certified missing reverse transport makes the same
    generated probe fail at the reached point. -/
theorem generatedProbe_fails_at_reached
    {S : DirectedSubstrate} (r : DirectedFailure S) :
    ¬ generatedProbe r r.right := by
  simpa [generatedProbe, returnProbe] using r.noBack

/-- End-to-end consequence genesis from directed failure alone. -/
theorem directed_failure_generates_consequence
    {S : DirectedSubstrate} (r : DirectedFailure S) :
    generatedCriterion r (generatedProbe r) := by
  exact ⟨generatedProbe_holds_at_source r, generatedProbe_fails_at_reached r⟩

/-- The forward interaction is retained in the same certificate: this is
    genuinely a reached-then-cannot-return asymmetry, not an arbitrary pair. -/
theorem interaction_and_generated_consequence
    {S : DirectedSubstrate} (r : DirectedFailure S) :
    Nonempty (S.Hom r.left r.right) ∧
      generatedCriterion r (generatedProbe r) := by
  exact ⟨r.forward, directed_failure_generates_consequence r⟩

/-- Exact ablation: if reverse transport exists, the transport-generated
    return probe cannot separate source from reached point. -/
theorem reverse_transport_erases_generated_separation
    (S : DirectedSubstrate) (left right : S.Obj)
    (hback : Nonempty (S.Hom right left)) :
    ¬ (returnProbe S left left ∧ ¬ returnProbe S left right) := by
  intro h
  exact h.2 hback

/-- There is no need for `DecidableEq S.Obj`: transport alone supplies the
    separating observation.  The theorem signature records that boundary. -/
theorem no_endpoint_equality_required
    {S : DirectedSubstrate} (r : DirectedFailure S) :
    generatedProbe r r.left ∧ ¬ generatedProbe r r.right := by
  exact ⟨generatedProbe_holds_at_source r, generatedProbe_fails_at_reached r⟩

end ReachabilityGeneratesConsequence

#check ReachabilityGeneratesConsequence.generatedProbe_holds_at_source
#check ReachabilityGeneratesConsequence.generatedProbe_fails_at_reached
#check ReachabilityGeneratesConsequence.directed_failure_generates_consequence
#check ReachabilityGeneratesConsequence.interaction_and_generated_consequence
#check ReachabilityGeneratesConsequence.reverse_transport_erases_generated_separation
#check ReachabilityGeneratesConsequence.no_endpoint_equality_required
