import Std

/-!
Residual-generated probe genesis.

This experiment removes the pre-indexed successor hierarchy from the local
developmental law.  The controller receives no candidate pool and contains no
"first missing index" rule.  Instead an ordered verified residual `(left,right)`
constructs its own separating probe directly: membership/equality with the
residual's right endpoint.

The local theorem is unconditional: every genuine residual generates a probe
that separates its endpoints.  Development retains old probes and adjoins
exactly that generated probe.  A step is strict exactly when that generated
probe was not already present.

For repeated development, any unboundedness premise is kept explicit as a
fresh-residual source.  Thus infinity is not hidden in the developmental law:
continued strict growth requires the environment/verifier to keep presenting
residuals whose generated probes are genuinely new.
-/

namespace ResidualGeneratedProbeGenesis

universe u

abbrev Probe (Ω : Type u) := Ω → Prop
abbrev Knowledge (Ω : Type u) := Probe Ω → Prop

/-- An ordered residual certified to contain two genuinely distinct states. -/
structure Residual (Ω : Type u) where
  left : Ω
  right : Ω
  distinct : left ≠ right

/-- The residual itself generates a separating observation.  No probe identity
    or candidate list is supplied to the controller. -/
def generatedProbe {Ω : Type u} (r : Residual Ω) : Probe Ω :=
  fun z => z = r.right

/-- A genuine residual's generated observation rejects its left endpoint and
    accepts its right endpoint. -/
theorem generatedProbe_separates {Ω : Type u} (r : Residual Ω) :
    ¬ generatedProbe r r.left ∧ generatedProbe r r.right := by
  constructor
  · intro h
    exact r.distinct h
  · rfl

/-- Development retains all existing observations and adjoins exactly the
    observation generated by the current residual. -/
def develop {Ω : Type u} (K : Knowledge Ω) (r : Residual Ω) : Knowledge Ω :=
  fun p => K p ∨ p = generatedProbe r

/-- Every old observation survives a residual-generated developmental step. -/
theorem retained {Ω : Type u} (K : Knowledge Ω) (r : Residual Ω)
    (p : Probe Ω) (hp : K p) : develop K r p :=
  Or.inl hp

/-- The observation generated by the residual is present after development. -/
theorem generated_present {Ω : Type u} (K : Knowledge Ω) (r : Residual Ω) :
    develop K r (generatedProbe r) :=
  Or.inr rfl

/-- If the generated observation was absent, the residual forces a genuinely
    new developmental state. -/
theorem strict_of_generated_fresh {Ω : Type u} (K : Knowledge Ω) (r : Residual Ω)
    (hfresh : ¬ K (generatedProbe r)) :
    develop K r ≠ K := by
  intro h
  have hpoint := congrFun h (generatedProbe r)
  have hiff : develop K r (generatedProbe r) ↔ K (generatedProbe r) :=
    iff_of_eq hpoint
  exact hfresh (hiff.mp (generated_present K r))

/-- Conversely, if the generated observation is already present, replaying the
    same residual changes nothing. -/
theorem fixed_of_generated_present {Ω : Type u} (K : Knowledge Ω) (r : Residual Ω)
    (hpresent : K (generatedProbe r)) :
    develop K r = K := by
  funext p
  apply propext
  constructor
  · intro h
    rcases h with hp | heq
    · exact hp
    · rw [heq]
      exact hpresent
  · intro hp
    exact Or.inl hp

/-- Exact local boundary: a residual step is fixed iff its self-generated probe
    was already represented. -/
theorem fixed_iff_generated_present {Ω : Type u} (K : Knowledge Ω) (r : Residual Ω) :
    develop K r = K ↔ K (generatedProbe r) := by
  constructor
  · intro h
    have hpoint := congrFun h (generatedProbe r)
    have hiff : develop K r (generatedProbe r) ↔ K (generatedProbe r) :=
      iff_of_eq hpoint
    exact hiff.mp (generated_present K r)
  · exact fixed_of_generated_present K r

/-- Empty initial observational state. -/
def emptyKnowledge {Ω : Type u} : Knowledge Ω := fun _ => False

/-- Repeated development is driven by an arbitrary residual source.  The local
    developmental law itself contains no enumeration of probes or consequences. -/
def iterate {Ω : Type u} (source : Nat → Residual Ω) : Nat → Knowledge Ω
  | 0 => emptyKnowledge
  | n + 1 => develop (iterate source n) (source n)

/-- Freshness is an external/verifier fact about the next residual, not a
    successor table embedded in `develop`. -/
def FreshAt {Ω : Type u} (source : Nat → Residual Ω) (n : Nat) : Prop :=
  ¬ iterate source n (generatedProbe (source n))

/-- If verified residuals keep generating genuinely new observations, every
    finite developmental step is strict. -/
theorem every_fresh_residual_forces_strict_growth
    {Ω : Type u} (source : Nat → Residual Ω)
    (hfresh : ∀ n, FreshAt source n) :
    ∀ n, develop (iterate source n) (source n) ≠ iterate source n := by
  intro n
  exact strict_of_generated_fresh (iterate source n) (source n) (hfresh n)

/-- Exact ablation/boundary theorem: if at some stage the verifier supplies a
    residual whose generated observation is already represented, that step is
    fixed.  Unbounded development therefore cannot come from the controller
    alone; it requires an unbounded supply of genuinely fresh residuals. -/
theorem stale_residual_cannot_force_growth
    {Ω : Type u} (source : Nat → Residual Ω) (n : Nat)
    (hstale : iterate source n (generatedProbe (source n))) :
    develop (iterate source n) (source n) = iterate source n := by
  exact fixed_of_generated_present (iterate source n) (source n) hstale

/-- Combined certificate: residuals generate their own separators locally, and
    repeated strict development is equivalent to freshness of the generated
    observation at each step rather than to a pre-specified successor ladder. -/
theorem residual_generated_development_certificate
    {Ω : Type u} (source : Nat → Residual Ω)
    (hfresh : ∀ n, FreshAt source n) :
    (∀ n, develop (iterate source n) (source n) ≠ iterate source n) ∧
    (∀ n, ¬ generatedProbe (source n) (source n).left ∧
          generatedProbe (source n) (source n).right) := by
  constructor
  · exact every_fresh_residual_forces_strict_growth source hfresh
  · intro n
    exact generatedProbe_separates (source n)

end ResidualGeneratedProbeGenesis

#check ResidualGeneratedProbeGenesis.generatedProbe_separates
#check ResidualGeneratedProbeGenesis.strict_of_generated_fresh
#check ResidualGeneratedProbeGenesis.fixed_iff_generated_present
#check ResidualGeneratedProbeGenesis.every_fresh_residual_forces_strict_growth
#check ResidualGeneratedProbeGenesis.stale_residual_cannot_force_growth
#check ResidualGeneratedProbeGenesis.residual_generated_development_certificate
