import DevelopmentalRetentionInducesInteractionOrientation

namespace RetentionOrientationAblations

open DevelopmentAsOperationalJoin
open AnonymousInteractionConvergenceKernel
open DevelopmentalRetentionInducesInteractionOrientation

/-- A strict gain yields a stable arrow only if the gained state is preserved
    by the following state.  Returning to the old state cannot satisfy that
    persistence condition. -/
def StableStrictGain (M N P : Memory) : Prop :=
  StrictRetains M N ∧ ImageLe N P

theorem arbitrary_erasure_blocks_stable_orientation {M N : Memory}
    (hGain : StrictRetains M N) :
    ¬ StableStrictGain M N M := by
  intro hStable
  apply hGain.2
  funext e
  apply propext
  exact ⟨hGain.1 e, hStable.2 e⟩

/-- Growth is verifier-licensed only when each newly introduced consequence is
    in the residual generated by the same external interaction. -/
def LicensedStrictGain (W : InteractionWorld) (M N : Memory) : Prop :=
  StrictRetains M N ∧
  ∀ e, N e → ¬ M e → Required W M e

def unlicensedEvidence : Evidence := (Key.k0, false)

def arbitraryUnlicensedGain : Memory :=
  fun e => s0 e ∨ e = unlicensedEvidence

theorem arbitrary_unlicensed_gain_is_strict :
    StrictRetains s0 arbitraryUnlicensedGain := by
  constructor
  · intro e he
    exact Or.inl he
  · intro hEq
    have hNew : arbitraryUnlicensedGain unlicensedEvidence := Or.inr rfl
    have hOld : s0 unlicensedEvidence := by
      rw [hEq]
      exact hNew
    simp [s0, emptyMemory] at hOld

theorem arbitrary_unlicensed_gain_is_not_required :
    ¬ Required serialWorld s0 unlicensedEvidence := by
  intro h
  rcases h with ⟨q, _, _, heq⟩
  have hBool := congrArg Prod.snd heq
  simp [serialWorld, unlicensedEvidence] at hBool

theorem strict_growth_without_external_license_does_not_count :
    ¬ LicensedStrictGain serialWorld s0 arbitraryUnlicensedGain := by
  intro hLicensed
  exact arbitrary_unlicensed_gain_is_not_required
    (hLicensed.2 unlicensedEvidence (Or.inr rfl) (by simp [s0, emptyMemory]))

/-- A second world retains the same two positive responses as `serialWorld`'s
    first two steps, but external interaction exposes them in the opposite
    order.  No order is stored in the final memory itself. -/
def reversePairWorld : InteractionWorld where
  base := fun q => q = Key.k1
  unlock := fun e q => e = e1 ∧ q = Key.k0
  respond := fun _ => true

def r0 : Memory := emptyMemory
def r1 : Memory := step reversePairWorld r0
def r2 : Memory := step reversePairWorld r1

theorem reverse_e1_precedes_e0 :
    AcquisitionPrecedes reversePairWorld r0 e1 e0 := by
  simp [AcquisitionPrecedes, r0, step, develop, join, Required,
    Available, reversePairWorld, emptyMemory, e0, e1]

theorem same_unordered_retained_set : s2 = r2 := by
  funext e
  rcases e with ⟨q, b⟩
  cases q <;> cases b <;>
    simp [s2, s1, r2, r1, r0, s0, step, develop, join, Required, Available,
      serialWorld, reversePairWorld, emptyMemory, e0, e1]

/-- The identical final unordered memory is compatible with opposite licensed
    acquisition orders.  Therefore final retained membership alone cannot
    determine which acquisition came first. -/
theorem unordered_retention_underdetermines_direction :
    s2 = r2 ∧
    AcquisitionPrecedes serialWorld s0 e0 e1 ∧
    AcquisitionPrecedes reversePairWorld r0 e1 e0 := by
  exact ⟨same_unordered_retained_set, serial_e0_precedes_e1,
    reverse_e1_precedes_e0⟩

theorem required_retention_ablations :
    (∀ {M N : Memory}, StrictRetains M N → ¬ StableStrictGain M N M) ∧
    StrictRetains s0 arbitraryUnlicensedGain ∧
    ¬ LicensedStrictGain serialWorld s0 arbitraryUnlicensedGain ∧
    s2 = r2 ∧
    AcquisitionPrecedes serialWorld s0 e0 e1 ∧
    AcquisitionPrecedes reversePairWorld r0 e1 e0 := by
  exact ⟨arbitrary_erasure_blocks_stable_orientation,
    arbitrary_unlicensed_gain_is_strict,
    strict_growth_without_external_license_does_not_count,
    same_unordered_retained_set,
    serial_e0_precedes_e1,
    reverse_e1_precedes_e0⟩

#check arbitrary_erasure_blocks_stable_orientation
#check strict_growth_without_external_license_does_not_count
#check unordered_retention_underdetermines_direction
#check required_retention_ablations

end RetentionOrientationAblations
