import CapabilityGeneratedFutureCarrier
import CapabilityGeneratedFiniteFutureBasis

namespace StageAwareGeneratedFutureBasis

open RequirementLandscapeCompletion
open CapabilityGeneratedFutureInterface
open CapabilityGeneratedFutureExactness
open CapabilityGeneratedFiniteFutureBasis
open FiniteExecutableDistinguishingFuture
open BehavioralRepairVersionSpace
open VerifierDoesNotDeterminePointwiseRequirement

/-- Executable availability is kept explicit for the same reason executable
    repair prediction is explicit: arbitrary type inhabitation is not
    automatically decidable. -/
structure ExecutableCapabilityAvailability (I : Type) (Cap : I → Type) where
  available : I → Bool
  faithful : ∀ i : I, available i = true ↔ generatedReachable Cap i

/-- The verifier-derived requirement landscape is given an executable view,
    without changing its semantic meaning. -/
structure ExecutableRequirementLandscape (I : Type) (Cap : I → Type) where
  semantic : RequirementLandscape I Cap
  required : I → Bool
  faithful : ∀ i : I, required i = true ↔ semantic.required i

/-- The old-stage question list is generated by filtering the finite capability
    carrier by currently executable capability availability. -/
def questionsBefore
    {I : Type} {Cap : I → Type}
    (C : CertifiedFiniteCapabilityIndex I)
    (A : ExecutableCapabilityAvailability I Cap) : List I :=
  C.indices.filter A.available

/-- Completion recomputes executable availability from exactly the two sources
    proved in Cycle 14 step 3: old availability or verifier requirement. -/
def availableAfter
    {I : Type} {Cap : I → Type}
    (A : ExecutableCapabilityAvailability I Cap)
    (R : ExecutableRequirementLandscape I Cap) (i : I) : Bool :=
  A.available i || R.required i

/-- The post-completion question list is therefore generated, not supplied. -/
def questionsAfter
    {I : Type} {Cap : I → Type}
    (C : CertifiedFiniteCapabilityIndex I)
    (A : ExecutableCapabilityAvailability I Cap)
    (R : ExecutableRequirementLandscape I Cap) : List I :=
  C.indices.filter (availableAfter A R)

private theorem unavailable_of_false
    {I : Type} {Cap : I → Type}
    (A : ExecutableCapabilityAvailability I Cap) {i : I}
    (hfalse : A.available i = false) : ¬ generatedReachable Cap i := by
  intro hi
  have htrue : A.available i = true := (A.faithful i).2 hi
  rw [hfalse] at htrue
  contradiction

private theorem unrequired_of_false
    {I : Type} {Cap : I → Type}
    (R : ExecutableRequirementLandscape I Cap) {i : I}
    (hfalse : R.required i = false) : ¬ R.semantic.required i := by
  intro hi
  have htrue : R.required i = true := (R.faithful i).2 hi
  rw [hfalse] at htrue
  contradiction

/-- The mechanically recomputed Boolean availability is faithful to the
    semantic future set obtained from verified completion. -/
theorem availableAfter_faithful
    {I : Type} {Cap : I → Type}
    (A : ExecutableCapabilityAvailability I Cap)
    (R : ExecutableRequirementLandscape I Cap) (i : I) :
    availableAfter A R i = true ↔ generatedReachableAfter R.semantic i := by
  cases ha : A.available i with
  | false =>
      have habs : ¬ generatedReachable Cap i := unavailable_of_false A ha
      cases hr : R.required i with
      | false =>
          have hnreq : ¬ R.semantic.required i := unrequired_of_false R hr
          have hnafter : ¬ generatedReachableAfter R.semantic i := by
            intro hafter
            rcases (generated_after_iff_old_or_residual R.semantic).1 hafter with hold | hres
            · exact habs hold
            · exact hnreq hres.1
          constructor
          · intro h
            simp [availableAfter, ha, hr] at h
          · intro h
            exact False.elim (hnafter h)
      | true =>
          have hreq : R.semantic.required i := (R.faithful i).1 hr
          have habs' : ¬ Nonempty (Cap i) := habs
          constructor
          · intro _
            exact every_required_absence_is_filled R.semantic hreq habs'
          · intro _
            simp [availableAfter, ha, hr]
  | true =>
      have hold : generatedReachable Cap i := (A.faithful i).1 ha
      constructor
      · intro _
        exact old_generated_futures_embed R.semantic hold
      · intro _
        simp [availableAfter, ha]

/-- Before completion the generated list is extensionally exact: membership is
    equivalent to current capability-generated future reachability. -/
theorem mem_questionsBefore_iff
    {I : Type} {Cap : I → Type}
    (C : CertifiedFiniteCapabilityIndex I)
    (A : ExecutableCapabilityAvailability I Cap) (i : I) :
    i ∈ questionsBefore C A ↔ generatedReachable Cap i := by
  simp [questionsBefore, C.covers i, A.faithful i]

/-- After completion the regenerated list is likewise exact. -/
theorem mem_questionsAfter_iff
    {I : Type} {Cap : I → Type}
    (C : CertifiedFiniteCapabilityIndex I)
    (A : ExecutableCapabilityAvailability I Cap)
    (R : ExecutableRequirementLandscape I Cap) (i : I) :
    i ∈ questionsAfter C A R ↔ generatedReachableAfter R.semantic i := by
  simp [questionsAfter, C.covers i, availableAfter_faithful A R i]

/-- Every old generated question remains in the regenerated list. -/
theorem old_questions_embed
    {I : Type} {Cap : I → Type}
    (C : CertifiedFiniteCapabilityIndex I)
    (A : ExecutableCapabilityAvailability I Cap)
    (R : ExecutableRequirementLandscape I Cap) {i : I} :
    i ∈ questionsBefore C A → i ∈ questionsAfter C A R := by
  intro hi
  have hold := (mem_questionsBefore_iff C A i).1 hi
  exact (mem_questionsAfter_iff C A R i).2
    (old_generated_futures_embed R.semantic hold)

/-- A required absent capability is absent from the old generated question set
    and present in the regenerated one. -/
theorem residual_question_is_generated
    {I : Type} {Cap : I → Type}
    (C : CertifiedFiniteCapabilityIndex I)
    (A : ExecutableCapabilityAvailability I Cap)
    (R : ExecutableRequirementLandscape I Cap) {i : I}
    (hreq : R.semantic.required i) (habs : ¬ Nonempty (Cap i)) :
    i ∉ questionsBefore C A ∧ i ∈ questionsAfter C A R := by
  constructor
  · intro hi
    exact habs ((mem_questionsBefore_iff C A i).1 hi)
  · exact (mem_questionsAfter_iff C A R i).2
      (every_required_absence_is_filled R.semantic hreq habs)

/-- The generated post-completion list is sufficient for executable search:
    any newly generated question that separates two candidates supplies a
    witness to the existing verified finite first-difference procedure. -/
theorem generated_separator_is_searchable
    {I : Type} {Cap : I → Type}
    (C : CertifiedFiniteCapabilityIndex I)
    (A : ExecutableCapabilityAvailability I Cap)
    (R : ExecutableRequirementLandscape I Cap)
    (E : ExecutableCapabilitySemantics I)
    {i : I} {R₁ R₂ : Repair I}
    (hafter : generatedReachableAfter R.semantic i)
    (hsep : E.predict R₁ i ≠ E.predict R₂ i) :
    ∃ j,
      firstDifference (E.predict R₁) (E.predict R₂)
        (questionsAfter C A R) = some j := by
  exact firstDifference_complete
    (E.predict R₁) (E.predict R₂) (questionsAfter C A R)
    ⟨i, (mem_questionsAfter_iff C A R i).2 hafter, hsep⟩

/-- Executable ablation of the requirement signal. -/
def erasedExecutableRequirements
    {I : Type} {Cap : I → Type} : ExecutableRequirementLandscape I Cap where
  semantic := erasedLandscape
  required := fun _ => false
  faithful := by
    intro i
    simp [erasedLandscape]

/-- Under ablation, regenerated questions are definitionally the old generated
    question list: no future/question genesis remains. -/
theorem ablation_preserves_question_list
    {I : Type} {Cap : I → Type}
    (C : CertifiedFiniteCapabilityIndex I)
    (A : ExecutableCapabilityAvailability I Cap) :
    questionsAfter C A (erasedExecutableRequirements (I := I) (Cap := Cap)) =
      questionsBefore C A := by
  change C.indices.filter (fun i => A.available i || false) =
    C.indices.filter A.available
  simp

namespace Witness

inductive Idx where
  | old
  | fresh
  | unrelated
  deriving DecidableEq

inductive Existing where | token

abbrev Cap : Idx → Type
  | .old => Existing
  | .fresh => Empty
  | .unrelated => Empty

def C : CertifiedFiniteCapabilityIndex Idx where
  indices := [.old, .fresh, .unrelated]
  covers := by
    intro i
    cases i <;> simp

def A : ExecutableCapabilityAvailability Idx Cap where
  available
    | .old => true
    | _ => false
  faithful := by
    intro i
    cases i with
    | old => exact ⟨Existing.token⟩
    | fresh =>
        intro h
        rcases h with ⟨h⟩
        exact nomatch h
    | unrelated =>
        intro h
        rcases h with ⟨h⟩
        exact nomatch h

def semanticLandscape : RequirementLandscape Idx Cap where
  required
    | .fresh => True
    | _ => False

def R : ExecutableRequirementLandscape Idx Cap where
  semantic := semanticLandscape
  required
    | .fresh => true
    | _ => false
  faithful := by
    intro i
    cases i <;> simp [semanticLandscape]

noncomputable def E : ExecutableCapabilitySemantics Idx := by
  classical
  exact {
    predict := fun repair i => if repair i then true else false
    faithful := by
      intro repair i
      by_cases h : repair i <;> simp [h]
  }

def leftRepair : Repair Idx
  | .old => True
  | .fresh => True
  | .unrelated => False

def rightRepair : Repair Idx
  | .old => True
  | .fresh => False
  | .unrelated => False

private theorem left_old_true : E.predict leftRepair .old = true :=
  (E.faithful leftRepair .old).2 trivial

private theorem right_old_true : E.predict rightRepair .old = true :=
  (E.faithful rightRepair .old).2 trivial

private theorem left_fresh_true : E.predict leftRepair .fresh = true :=
  (E.faithful leftRepair .fresh).2 trivial

private theorem right_fresh_false : E.predict rightRepair .fresh = false := by
  cases h : E.predict rightRepair .fresh with
  | false => rfl
  | true =>
      have hf : rightRepair .fresh := (E.faithful rightRepair .fresh).1 h
      exact False.elim hf

theorem before_questions_exact : questionsBefore C A = [.old] := by
  rfl

theorem after_questions_exact : questionsAfter C A R = [.old, .fresh] := by
  rfl

theorem fresh_is_generated :
    Idx.fresh ∉ questionsBefore C A ∧ Idx.fresh ∈ questionsAfter C A R := by
  exact residual_question_is_generated C A R (i := .fresh) trivial (by
    intro h
    rcases h with ⟨h⟩
    exact nomatch h)

theorem old_scan_sees_no_difference :
    firstDifference (E.predict leftRepair) (E.predict rightRepair)
      (questionsBefore C A) = none := by
  rw [before_questions_exact]
  simp [firstDifference, left_old_true, right_old_true]

theorem regenerated_scan_finds_fresh :
    firstDifference (E.predict leftRepair) (E.predict rightRepair)
      (questionsAfter C A R) = some .fresh := by
  rw [after_questions_exact]
  simp [firstDifference, left_old_true, right_old_true,
    left_fresh_true, right_fresh_false]

theorem ablated_questions_exact :
    questionsAfter C A (erasedExecutableRequirements (I := Idx) (Cap := Cap)) =
      [.old] := by
  rw [ablation_preserves_question_list]
  exact before_questions_exact

end Witness

#check ExecutableCapabilityAvailability
#check ExecutableRequirementLandscape
#check questionsBefore
#check availableAfter
#check questionsAfter
#check availableAfter_faithful
#check mem_questionsBefore_iff
#check mem_questionsAfter_iff
#check old_questions_embed
#check residual_question_is_generated
#check generated_separator_is_searchable
#check ablation_preserves_question_list
#check Witness.before_questions_exact
#check Witness.after_questions_exact
#check Witness.old_scan_sees_no_difference
#check Witness.regenerated_scan_finds_fresh
#check Witness.ablated_questions_exact

end StageAwareGeneratedFutureBasis
