import FailureForcesIdentityCompletion
import FailureForcesCompositionCompletion

namespace VerifiedBoundaryCompletionKernel

open IdentityForcedAsMinimalCompletion
open FailureForcesCompositionCompletion

/-- Purified residual: the old directed substrate cannot realize transport
    between one verifier-certified endpoint pair.  No semantic label such as
    `identity` or `composition` appears at the completion layer. -/
structure FailedEndpointObligation (S : RawDirectedSubstrate) where
  source : S.Obj
  target : S.Obj
  unrealized : ¬ Nonempty (S.Hom source target)

/-- The residual itself determines exactly one demanded endpoint pair. -/
def generatedDemand
    {S : RawDirectedSubstrate} (r : FailedEndpointObligation S) :
    CertifiedTransportDemand S where
  demanded := fun x y => x = r.source ∧ y = r.target

/-- Exact ablation: erase the failure signal while leaving the old substrate unchanged. -/
def erasedDemand (S : RawDirectedSubstrate) : CertifiedTransportDemand S where
  demanded := fun _ _ => False

theorem source_target_is_generated_demand
    {S : RawDirectedSubstrate} (r : FailedEndpointObligation S) :
    (generatedDemand r).demanded r.source r.target := by
  exact ⟨rfl, rfl⟩

/-- The generic free transport completion satisfies the residual. -/
theorem residual_forces_endpoint_filler
    {S : RawDirectedSubstrate} (r : FailedEndpointObligation S) :
    Nonempty
      ((completeTransport S (generatedDemand r)).Hom r.source r.target) := by
  exact satisfyDemand (source_target_is_generated_demand r)

/-- The filler is genuinely new. -/
theorem residual_forces_genuinely_new_endpoint_filler
    {S : RawDirectedSubstrate} (r : FailedEndpointObligation S) :
    (¬ Nonempty (S.Hom r.source r.target)) ∧
    Nonempty
      ((completeTransport S (generatedDemand r)).Hom r.source r.target) := by
  exact ⟨r.unrealized, residual_forces_endpoint_filler r⟩

/-- The purified completion adds no unrelated absent endpoint transport. -/
theorem residual_adds_no_unrelated_transport
    {S : RawDirectedSubstrate} (r : FailedEndpointObligation S)
    {x y : S.Obj}
    (hunrelated : x ≠ r.source ∨ y ≠ r.target)
    (holdNone : ¬ Nonempty (S.Hom x y)) :
    ¬ Nonempty ((completeTransport S (generatedDemand r)).Hom x y) := by
  apply no_new_transport_outside_demand ?_ holdNone
  intro hxy
  rcases hxy with ⟨hx, hy⟩
  rcases hunrelated with hsource | htarget
  · exact hsource hx
  · exact htarget hy

/-- Exact causal ablation: deleting the residual-to-demand link prevents filler genesis. -/
theorem erasing_residual_erases_endpoint_filler
    {S : RawDirectedSubstrate} (r : FailedEndpointObligation S) :
    ¬ Nonempty
      ((completeTransport S (erasedDemand S)).Hom r.source r.target) := by
  apply no_new_transport_outside_demand ?_ r.unrealized
  intro h
  exact h

/-- Failure-relative universal property.  Any interpretation of the old
    transports and the single demanded endpoint uniquely interprets every
    transport in the completion. -/
theorem residual_generated_lift_unique
    {S : RawDirectedSubstrate} (r : FailedEndpointObligation S)
    (H : S.Obj → S.Obj → Type)
    (oldMap : ∀ {x y}, S.Hom x y → H x y)
    (forcedMap : ∀ {x y}, (generatedDemand r).demanded x y → H x y)
    (g : ∀ {x y}, CompletedTransportHom S (generatedDemand r) x y → H x y)
    (hold : ∀ {x y} (h : S.Hom x y),
      g (CompletedTransportHom.old h) = oldMap h)
    (hforced : ∀ {x y} (hxy : (generatedDemand r).demanded x y),
      g (CompletedTransportHom.forced hxy) = forcedMap hxy) :
    ∀ {x y} (h : CompletedTransportHom S (generatedDemand r) x y),
      g h = lift H oldMap forcedMap h := by
  exact lift_unique H oldMap forcedMap g hold hforced

/-- First purified kernel certificate: endpoint failure alone is sufficient to
    generate the exact minimal/free local completion, independently of the
    semantic origin of that endpoint obligation. -/
theorem verified_endpoint_failure_forces_minimal_completion
    {S : RawDirectedSubstrate} (r : FailedEndpointObligation S) :
    ((¬ Nonempty (S.Hom r.source r.target)) ∧
      Nonempty ((completeTransport S (generatedDemand r)).Hom r.source r.target)) ∧
    (¬ Nonempty ((completeTransport S (erasedDemand S)).Hom r.source r.target)) := by
  exact ⟨residual_forces_genuinely_new_endpoint_filler r,
    erasing_residual_erases_endpoint_filler r⟩

/-- Identity genesis compiles into the same generic endpoint-obligation kernel.
    Thus `identity` is not a primitive of the completion operation; it is the
    boundary shape generated by a closed-continuation failure. -/
def fromIdentityFailure
    {S : RawDirectedSubstrate}
    (f : FailureForcesIdentityCompletion.FailedContinuation S) :
    FailedEndpointObligation S where
  source := f.start
  target := f.start
  unrealized := FailureForcesIdentityCompletion.failure_exposes_missing_self_transport f

/-- Composition genesis compiles into exactly the same endpoint-obligation kernel.
    `composition` likewise lives in failure provenance, not in the filler primitive. -/
def fromCompositionFailure
    {S : RawDirectedSubstrate}
    (f : FailureForcesCompositionCompletion.FailedComposition S) :
    FailedEndpointObligation S where
  source := f.source
  target := f.target
  unrealized := f.unrealized

theorem identity_failure_is_endpoint_completion_instance
    {S : RawDirectedSubstrate}
    (f : FailureForcesIdentityCompletion.FailedContinuation S) :
    ((¬ Nonempty (S.Hom f.start f.start)) ∧
      Nonempty
        ((completeTransport S (generatedDemand (fromIdentityFailure f))).Hom
          f.start f.start)) ∧
    (¬ Nonempty
      ((completeTransport S (erasedDemand S)).Hom f.start f.start)) := by
  exact verified_endpoint_failure_forces_minimal_completion (fromIdentityFailure f)

theorem composition_failure_is_endpoint_completion_instance
    {S : RawDirectedSubstrate}
    (f : FailureForcesCompositionCompletion.FailedComposition S) :
    ((¬ Nonempty (S.Hom f.source f.target)) ∧
      Nonempty
        ((completeTransport S (generatedDemand (fromCompositionFailure f))).Hom
          f.source f.target)) ∧
    (¬ Nonempty
      ((completeTransport S (erasedDemand S)).Hom f.source f.target)) := by
  exact verified_endpoint_failure_forces_minimal_completion (fromCompositionFailure f)

#check verified_endpoint_failure_forces_minimal_completion
#check identity_failure_is_endpoint_completion_instance
#check composition_failure_is_endpoint_completion_instance
#check residual_generated_lift_unique

end VerifiedBoundaryCompletionKernel
