import Std

/-- A concrete finite bedrock witness: search can derive a negative reachability result
    without receiving a pre-supplied negative certificate. -/
namespace FiniteSearchCompletenessBoundary

abbrev X := Fin 3

def edge (x y : X) : Bool :=
  (x == 0 && y == 1) || (x == 1 && y == 2)

def step (x y : X) : Bool := x == y || edge x y

/-- Exhaustive search over all paths of length at most three in the three-state witness. -/
def search3 (x y : X) : Bool :=
  let a0 := step x y
  let a1 := a0 ||
    (step x 0 && step 0 y) ||
    (step x 1 && step 1 y) ||
    (step x 2 && step 2 y)
  let a2 := a1 ||
    (step x 0 && a1) ||
    (step x 1 && a1) ||
    (step x 2 && a1)
  a2

/-- The exhaustive search itself produces the negative result; no negative certificate
    is supplied as an input. -/
theorem search_derives_negative : search3 2 0 = false := by
  decide

/-- In this finite witness, failure of the complete bounded search really does imply
    non-reachability because every nontrivial path is simple and has length at most two. -/
inductive Reach : X → X → Prop where
  | refl (x : X) : Reach x x
  | edge {x y : X} : edge x y = true → Reach x y
  | trans {x y z : X} : Reach x y → Reach y z → Reach x z

theorem no_path_2_to_0 : ¬ Reach 2 0 := by
  intro h
  cases h with
  | refl => decide
  | edge he => simp [edge] at he
  | trans h20 h00 =>
      cases h20 with
      | refl =>
          cases h00 with
          | refl => decide
          | edge he => simp [edge] at he
          | trans h01 h10 =>
              cases h01 <;> cases h10 <;> simp [edge] at *
      | edge he => simp [edge] at he
      | trans h21 h10 =>
          cases h21 <;> cases h10 <;> simp [edge] at *

/-- The search result is therefore a verified negative observation generated by
    finite completeness, rather than a preloaded residual certificate. -/
theorem complete_negative_witness : search3 2 0 = false ∧ ¬ Reach 2 0 :=
  ⟨search_derives_negative, no_path_2_to_0⟩

/-- A bounded search is not automatically complete on an unbounded world: a longer
    path can exist even when the chosen bound reports failure. This is represented
    here by the explicit two-step witness 0 -> 1 -> 2. -/
theorem bounded_search_needs_completeness :
    edge 0 1 = true ∧ edge 1 2 = true := by
  decide

end FiniteSearchCompletenessBoundary
