import Std

/- A concrete finite bedrock witness: search can derive a negative reachability result
   without receiving a pre-supplied negative certificate. -/
namespace FiniteSearchCompletenessBoundary

abbrev X := Fin 3

def edge (x y : X) : Bool :=
  (x == 0 && y == 1) || (x == 1 && y == 2)

def step (x y : X) : Bool := x == y || edge x y

/-- Exhaustive search over the concrete three-state witness. -/
def search3 (x y : X) : Bool :=
  step x y ||
  (step x 0 && step 0 y) ||
  (step x 1 && step 1 y) ||
  (step x 2 && step 2 y)

/-- The exhaustive search itself produces the negative result; no negative certificate
    is supplied as an input. -/
theorem search_derives_negative : search3 2 0 = false := by
  decide

/-- Reflexive-transitive reachability generated by the two raw edges. -/
inductive Reach : X → X → Prop where
  | refl (x : X) : Reach x x
  | e01 : Reach 0 1
  | e12 : Reach 1 2
  | trans {x y z : X} : Reach x y → Reach y z → Reach x z

/-- Every generated path is monotone in the finite topological rank. -/
theorem reach_monotone {x y : X} (h : Reach x y) : x.val ≤ y.val := by
  induction h with
  | refl x => exact Nat.le_refl x.val
  | e01 => decide
  | e12 => decide
  | trans hxy hyz ihxy ihyz => exact Nat.le_trans ihxy ihyz

/-- Complete finite search can therefore certify this negative fact. -/
theorem no_path_2_to_0 : ¬ Reach 2 0 := by
  intro h
  have hm := reach_monotone h
  omega

/-- The search result is a verified negative observation generated by finite completeness,
    rather than a preloaded residual certificate. -/
theorem complete_negative_witness : search3 2 0 = false ∧ ¬ Reach 2 0 :=
  ⟨search_derives_negative, no_path_2_to_0⟩

/-- Positive control: the graph really does contain a longer generated continuation. -/
theorem two_step_path_exists : Reach 0 2 := by
  exact Reach.trans Reach.e01 Reach.e12

/-- A one-step search is therefore incomplete for 0 -> 2 even though reachability holds. -/
def search1 (x y : X) : Bool := step x y

theorem bounded_failure_without_completeness_is_not_negative :
    search1 0 2 = false ∧ Reach 0 2 := by
  constructor
  · decide
  · exact two_step_path_exists

/-- The boundary certificate: negative inference is licensed by completeness, not by
    search failure alone. -/
theorem completeness_is_the_missing_boundary :
    (search3 2 0 = false ∧ ¬ Reach 2 0) ∧
    (search1 0 2 = false ∧ Reach 0 2) := by
  exact ⟨complete_negative_witness, bounded_failure_without_completeness_is_not_negative⟩

end FiniteSearchCompletenessBoundary
