import Std
import DevelopmentalCategory

universe u v w z

namespace GeneratedStage

open TypedBehaviouralCongruence
open DevelopmentalCategory

/-- The closure generated by an old developmental stage plus one newly
    licensed morphism. Nothing else is admitted except identities and what is
    forced by composition. -/
inductive GeneratedAllow (C : SmallCategory) (S : Stage C)
    {X₀ Y₀ : C.Obj} (seed : C.Hom X₀ Y₀) :
    {X Y : C.Obj} → C.Hom X Y → Prop
  | old {X Y} (f : C.Hom X Y) (hf : S.allow f) :
      GeneratedAllow C S seed f
  | seed : GeneratedAllow C S seed seed
  | id (X : C.Obj) : GeneratedAllow C S seed (C.id X)
  | comp {X Y Z} (g : C.Hom Y Z) (f : C.Hom X Y)
      (hg : GeneratedAllow C S seed g)
      (hf : GeneratedAllow C S seed f) :
      GeneratedAllow C S seed (C.comp g f)

/-- Adjoining one verifier-licensed morphism produces a lawful developmental
    stage by closing only under the category laws already required of stages. -/
def adjoinStage (C : SmallCategory) (S : Stage C)
    {X Y : C.Obj} (seed : C.Hom X Y) : Stage C where
  allow := GeneratedAllow C S seed
  id_allow := by
    intro Z
    exact GeneratedAllow.id Z
  comp_allow := by
    intro A B D g f hg hf
    exact GeneratedAllow.comp g f hg hf

/-- The generated stage contains every previously accessible continuation. -/
theorem old_extends_adjoin (C : SmallCategory) (S : Stage C)
    {X Y : C.Obj} (seed : C.Hom X Y) :
    Extends C S (adjoinStage C S seed) := by
  intro A B f hf
  exact GeneratedAllow.old f hf

/-- The seed itself is accessible in the generated stage. -/
theorem seed_allowed (C : SmallCategory) (S : Stage C)
    {X Y : C.Obj} (seed : C.Hom X Y) :
    (adjoinStage C S seed).allow seed := by
  exact GeneratedAllow.seed

/-- Universal property: `adjoinStage S seed` is the least composition-closed
    developmental stage extending `S` and containing `seed`. Any competing
    stage with those two properties must contain every generated morphism. -/
theorem adjoin_least (C : SmallCategory) (S T : Stage C)
    {X Y : C.Obj} (seed : C.Hom X Y)
    (hST : Extends C S T) (hseed : T.allow seed) :
    Extends C (adjoinStage C S seed) T := by
  intro A B f hf
  induction hf with
  | old g hg =>
      exact hST g hg
  | seed =>
      exact hseed
  | id Z =>
      exact T.id_allow Z
  | comp g f hg hf ihg ihf =>
      exact T.comp_allow g f ihg ihf

/-- A verifier-licensed separator therefore induces a canonical *minimal*
    regime change and a strict interface refinement. This joins the generated
    stage universal property to the existing developmental quotient theorem. -/
theorem generated_separator_forces_minimal_split
    (C : SmallCategory)
    (A : Action C)
    (Obs : C.Obj → Type z)
    (observe : ∀ X, A.State X → Obs X)
    (S : Stage C)
    {X Y : C.Obj} {x y : A.State X}
    (seed : C.Hom X Y)
    (hold : BehEqAt C A Obs observe S X x y)
    (hsep : observe Y (A.map seed x) ≠ observe Y (A.map seed y)) :
    BehEqAt C A Obs observe S X x y ∧
      ¬ BehEqAt C A Obs observe (adjoinStage C S seed) X x y := by
  exact new_separator_forces_split C A Obs observe
    (old_extends_adjoin C S seed)
    seed hold (seed_allowed C S seed) hsep

end GeneratedStage
