import Std

namespace MinimalSufficientInterface.IdentityCompositionConsequence

universe u v w

/-- Minimal transformation calculus: identity action and compositional action.
No associativity or unit equations on `comp` are assumed. -/
structure Calculus (M : Type u) (X : Type v) where
  one : M
  comp : M → M → M
  act : M → X → X
  one_act : ∀ x, act one x = x
  comp_act : ∀ f g x, act (comp f g) x = act f (act g x)

variable {M : Type u} {X : Type v} {Y : Type w}
variable (K : Calculus M X)

/-- A developmental stage licenses transformations and is closed under identity
and composition. -/
structure Stage where
  allows : M → Prop
  one_mem : allows K.one
  comp_mem : ∀ {f g}, allows f → allows g → allows (K.comp f g)

/-- One stage extends another when every old transformation remains licensed. -/
def Extends (S T : Stage K) : Prop :=
  ∀ f, S.allows f → T.allows f

/-- Behavioural identity at a stage: two states are the same exactly when every
licensed consequence has the same protected observation. -/
def SameAt (observe : X → Y) (S : Stage K) (x y : X) : Prop :=
  ∀ f, S.allows f → observe (K.act f x) = observe (K.act f y)

/-- `SameAt` is observation-compatible because identity itself is licensed. -/
theorem sameAt_observation
    (observe : X → Y) (S : Stage K) {x y : X}
    (h : SameAt K observe S x y) : observe x = observe y := by
  simpa [K.one_act] using h K.one S.one_mem

/-- `SameAt` is invariant under every licensed transformation. -/
theorem sameAt_invariant
    (observe : X → Y) (S : Stage K) {x y : X}
    (h : SameAt K observe S x y) {g : M} (hg : S.allows g) :
    SameAt K observe S (K.act g x) (K.act g y) := by
  intro f hf
  rw [← K.comp_act, ← K.comp_act]
  exact h (K.comp f g) (S.comp_mem hf hg)

/-- `SameAt` is the greatest relation compatible with protected observation and
stable under every licensed transformation. -/
theorem sameAt_greatest_invariant
    (observe : X → Y) (S : Stage K)
    (R : X → X → Prop)
    (hObs : ∀ {x y}, R x y → observe x = observe y)
    (hInv : ∀ {x y}, R x y → ∀ {f}, S.allows f → R (K.act f x) (K.act f y)) :
    ∀ {x y}, R x y → SameAt K observe S x y := by
  intro x y hR f hf
  exact hObs (hInv hR hf)

/-- Extending the consequence language can only refine behavioural identity. -/
theorem extension_refines_identity
    (observe : X → Y) (S T : Stage K) (hST : Extends K S T) :
    ∀ {x y}, SameAt K observe T x y → SameAt K observe S x y := by
  intro x y hT f hf
  exact hT f (hST f hf)

/-- Converse forcing law. If an extension genuinely changes the identity of a
pair, the change cannot be unexplained: there exists a consequence licensed by
the new stage, absent from the old stage, whose protected observation separates
the pair. Thus every strict identity change has an explicit forcing witness. -/
theorem strict_refinement_has_new_forcing_consequence
    (observe : X → Y)
    (S T : Stage K) (hST : Extends K S T) {x y : X}
    (hOld : SameAt K observe S x y)
    (hNew : ¬ SameAt K observe T x y) :
    ∃ f, T.allows f ∧ ¬ S.allows f ∧
      observe (K.act f x) ≠ observe (K.act f y) := by
  classical
  by_contra hNoWitness
  apply hNew
  intro f hfT
  by_contra hSep
  have hfS : S.allows f := by
    by_contra hfS
    exact hNoWitness ⟨f, hfT, hfS, hSep⟩
  exact hSep (hOld f hfS)

/-- A licensed consequence that distinguishes a pair is already sufficient to
forbid their union at that stage. -/
theorem consequence_forces_split
    (observe : X → Y)
    (T : Stage K) (f : M) (hfT : T.allows f)
    {x y : X}
    (hSep : observe (K.act f x) ≠ observe (K.act f y)) :
    ¬ SameAt K observe T x y := by
  intro hSame
  exact hSep (hSame f hfT)

/-- Closure generated by an old stage plus one new seed. -/
inductive Generated (S : Stage K) (seed : M) : M → Prop
  | old {f} : S.allows f → Generated S seed f
  | seed : Generated S seed seed
  | comp {f g} : Generated S seed f → Generated S seed g →
      Generated S seed (K.comp f g)

/-- Least composition-closed stage obtained by adjoining one seed. -/
def adjoin (S : Stage K) (seed : M) : Stage K where
  allows := Generated K S seed
  one_mem := Generated.old S.one_mem
  comp_mem := Generated.comp

/-- The old stage embeds into its one-seed extension. -/
theorem old_extends_to_adjoin (S : Stage K) (seed : M) :
    Extends K S (adjoin K S seed) := by
  intro f hf
  exact Generated.old hf

/-- The new seed is licensed by the generated stage. -/
theorem seed_mem_adjoin (S : Stage K) (seed : M) :
    (adjoin K S seed).allows seed :=
  Generated.seed

/-- `adjoin` is the least stage containing the old stage and the new seed. -/
theorem adjoin_least
    (S T : Stage K) (seed : M)
    (hST : Extends K S T) (hSeed : T.allows seed) :
    Extends K (adjoin K S seed) T := by
  intro f hf
  induction hf with
  | old hOld => exact hST _ hOld
  | seed => exact hSeed
  | comp hf hg ihf ihg => exact T.comp_mem ihf ihg

/-- Verified compositional portal: a newly verified separating consequence,
adjoined by least closure, forces a strict identity refinement. -/
theorem verified_compositional_portal
    (observe : X → Y)
    (S : Stage K) (seed : M) {x y : X}
    (hOld : SameAt K observe S x y)
    (hSep : observe (K.act seed x) ≠ observe (K.act seed y)) :
    SameAt K observe S x y ∧
      ¬ SameAt K observe (adjoin K S seed) x y := by
  exact ⟨hOld,
    consequence_forces_split K observe (adjoin K S seed) seed
      (seed_mem_adjoin K S seed) hSep⟩

/-- Fixed-point criterion: if every candidate consequence already preserves the
current behavioural identity, adjoining it cannot split that pair. -/
theorem sameAt_is_stable
    (observe : X → Y)
    (S : Stage K) {x y : X}
    (hOld : SameAt K observe S x y)
    (seed : M)
    (hSeedPreserves : observe (K.act seed x) = observe (K.act seed y))
    (hClosurePreserves : ∀ f, Generated K S seed f →
      observe (K.act f x) = observe (K.act f y)) :
    SameAt K observe (adjoin K S seed) x y := by
  intro f hf
  exact hClosurePreserves f hf

end MinimalSufficientInterface.IdentityCompositionConsequence
