import Std
import NucleusQuiver

universe u v w x

namespace NucleusFreeCategory

open NucleusQuiver

/-- Finite directed paths freely generated by a quiver. -/
inductive Path (G : NucleusQuiver.{u, v}) : G.Obj → G.Obj → Type (max u v)
  | nil (X : G.Obj) : Path G X X
  | snoc {X Y Z : G.Obj} : Path G X Y → G.Edge Y Z → Path G X Z

namespace Path

/-- Concatenation: first p, then q. -/
def append {G : NucleusQuiver.{u, v}} {X Y Z : G.Obj} :
    Path G Y Z → Path G X Y → Path G X Z
  | .nil _, p => p
  | .snoc q e, p => .snoc (append q p) e

@[simp] theorem append_nil_left {G : NucleusQuiver.{u, v}} {X Y : G.Obj}
    (p : Path G X Y) :
    append (.nil Y) p = p := rfl

@[simp] theorem append_nil_right {G : NucleusQuiver.{u, v}} {X Y : G.Obj}
    (p : Path G X Y) :
    append p (.nil X) = p := by
  induction p with
  | nil => rfl
  | snoc p e ih =>
      simp [append, ih]

theorem append_assoc {G : NucleusQuiver.{u, v}} {W X Y Z : G.Obj}
    (h : Path G Y Z) (g : Path G X Y) (f : Path G W X) :
    append (append h g) f = append h (append g f) := by
  induction h with
  | nil => rfl
  | snoc h e ih =>
      simp [append, ih]

/-- The one-edge path associated to a generating edge. -/
def gen {G : NucleusQuiver.{u, v}} {X Y : G.Obj} (e : G.Edge X Y) :
    Path G X Y :=
  .snoc (.nil X) e

end Path

/-- The canonical free category on a quiver. -/
def category (G : NucleusQuiver.{u, v}) : SmallCategory where
  Obj := G.Obj
  Hom := Path G
  id := Path.nil
  comp := Path.append
  id_comp := by
    intro X Y f
    rfl
  comp_id := by
    intro X Y f
    exact Path.append_nil_right f
  assoc := by
    intro W X Y Z h g f
    exact Path.append_assoc h g f

variable {G : NucleusQuiver.{u, v}} {C : SmallCategory.{w, x}}

/-- Interpret every generated path in a target category. -/
def eval (I : Interpretation G C) {X Y : G.Obj} :
    Path G X Y → C.Hom (I.obj X) (I.obj Y)
  | .nil _ => C.id (I.obj X)
  | .snoc p e => C.comp (I.edge e) (eval I p)

@[simp] theorem eval_nil (I : Interpretation G C) (X : G.Obj) :
    eval I (.nil X) = C.id (I.obj X) := rfl

@[simp] theorem eval_gen (I : Interpretation G C)
    {X Y : G.Obj} (e : G.Edge X Y) :
    eval I (Path.gen e) = I.edge e := by
  simpa [Path.gen, eval] using C.comp_id (I.edge e)

theorem eval_append (I : Interpretation G C)
    {X Y Z : G.Obj} (q : Path G Y Z) (p : Path G X Y) :
    eval I (Path.append q p) = C.comp (eval I q) (eval I p) := by
  induction q with
  | nil =>
      rw [eval_nil]
      exact (C.id_comp (eval I p)).symm
  | snoc q e ih =>
      simp only [Path.append, eval]
      rw [ih]
      exact (C.assoc (I.edge e) (eval I q) (eval I p)).symm

/-- A functorial extension of one interpretation of the primitive quiver. -/
structure Extension (I : Interpretation G C) where
  mapPath : {X Y : G.Obj} → Path G X Y → C.Hom (I.obj X) (I.obj Y)
  map_id : ∀ X, mapPath (.nil X) = C.id (I.obj X)
  map_comp : ∀ {X Y Z} (q : Path G Y Z) (p : Path G X Y),
    mapPath (Path.append q p) = C.comp (mapPath q) (mapPath p)
  map_gen : ∀ {X Y} (e : G.Edge X Y), mapPath (Path.gen e) = I.edge e

/-- The canonical extension obtained by interpreting a path compositionally. -/
def extend (I : Interpretation G C) : Extension I where
  mapPath := eval I
  map_id := eval_nil I
  map_comp := eval_append I
  map_gen := eval_gen I

/-- Uniqueness half of the free-category universal property. -/
theorem extension_unique (I : Interpretation G C) (E : Extension I) :
    ∀ {X Y : G.Obj} (p : Path G X Y), E.mapPath p = eval I p := by
  intro X Y p
  induction p with
  | nil =>
      calc
        E.mapPath (.nil X) = C.id (I.obj X) := E.map_id X
        _ = eval I (.nil X) := (eval_nil I X).symm
  | snoc p e ih =>
      calc
        E.mapPath (.snoc p e) =
            E.mapPath (Path.append (Path.gen e) p) := rfl
        _ = C.comp (E.mapPath (Path.gen e)) (E.mapPath p) :=
            E.map_comp (Path.gen e) p
        _ = C.comp (I.edge e) (eval I p) := by
            rw [E.map_gen e, ih]
        _ = eval I (.snoc p e) := rfl

/-- Free-category universal property in existence-and-uniqueness form:
    every interpretation of the raw directed generators extends, and every
    extension agrees with the canonical one on every generated path. -/
theorem free_universal (I : Interpretation G C) :
    ∃ E : Extension I,
      (∀ {X Y : G.Obj} (p : Path G X Y), E.mapPath p = eval I p) ∧
      ∀ E' : Extension I,
        ∀ {X Y : G.Obj} (p : Path G X Y), E'.mapPath p = E.mapPath p := by
  refine ⟨extend I, ?_, ?_⟩
  · intro X Y p
    rfl
  · intro E' X Y p
    exact extension_unique I E' p

end NucleusFreeCategory
