import Std
import ResidualRegimeBridge
import GeneratedStage
import FactorizationSufficiency
import ResourceIndexedConsequence

universe u v w z

namespace VerifiedDevelopment

open BehaviouralCongruence
open ResidualRegimeBridge

variable {M : Type u} {X : Type v} {O : Type w}
variable (A : ActionMonoid M X) (obs : X → O)

/-- Everything the existing semantic kernel can certify from one verified residual. -/
structure VerifiedStep (B : List M) (c : M) : Prop where
  strict : ∃ x y, EqBy A obs B x y ∧ ¬ EqBy A obs (c :: B) x y
  coarsest : ∀ R : X → X → Prop,
    AdmissibleRepair A obs B c R →
    ∀ x y, R x y → EqBy A obs (c :: B) x y
  blockedBefore : ¬ CanDescend A obs B c
  enabledAfter : CanDescend A obs (c :: B) c
  ablationRestores : ¬ CanDescend A obs B c

theorem residual_yields_verified_step
    (B : List M) (c : M)
    (hρ : Residual A obs B c) : VerifiedStep A obs B c := by
  have h := residual_to_minimal_regime_and_capability A obs B c hρ
  exact {
    strict := h.1
    coarsest := h.2.1
    blockedBefore := h.2.2.1
    enabledAfter := h.2.2.2.1
    ablationRestores := h.2.2.2.2
  }

/-- Failure is deliberately not assumed to manufacture a separator.  This is
    an explicit interface for the cases where protected evidence really does
    expose one. Ambiguous/closure/resource failures may require other moves. -/
def SeparatorOracle (Failure : List M → Prop) : Prop :=
  ∀ B, Failure B → ∃ c, Residual A obs B c

theorem failure_yields_verified_development
    (Failure : List M → Prop)
    (oracle : SeparatorOracle A obs Failure)
    (B : List M) (hFail : Failure B) :
    ∃ c, VerifiedStep A obs B c := by
  rcases oracle B hFail with ⟨c, hρ⟩
  exact ⟨c, residual_yields_verified_step A obs B c hρ⟩

/-- Abstract generated-language model. `Expresses L c` says capability `c` is
    present in the language generated by retained atoms `L`. -/
structure PromotionLanguage (Atom : Type u) (Cap : Type z) where
  Expresses : List Atom → Cap → Prop

/-- Promotion is conservative when retaining an atom never destroys an already
    expressible capability. -/
def PromotionMonotone {Atom : Type u} {Cap : Type z}
    (G : PromotionLanguage Atom Cap) : Prop :=
  ∀ L a c, G.Expresses L c → G.Expresses (a :: L) c

/-- A strict promotion witness is stronger than a ranking improvement: one
    designated future capability is absent before promotion and expressible
    after promotion. -/
structure StrictPromotion {Atom : Type u} {Cap : Type z}
    (G : PromotionLanguage Atom Cap) (L : List Atom) (a : Atom) (c : Cap) : Prop where
  cold : ¬ G.Expresses L c
  warm : G.Expresses (a :: L) c

/-- Any strict promotion witness certifies strict change of the generated
    capability frontier at the witness capability. -/
theorem promotion_changes_expressibility {Atom : Type u} {Cap : Type z}
    (G : PromotionLanguage Atom Cap) (L : List Atom) (a : Atom) (c : Cap)
    (h : StrictPromotion G L a c) :
    ¬ G.Expresses L c ∧ G.Expresses (a :: L) c := by
  exact ⟨h.cold, h.warm⟩

/-- Exact ancestor ablation for generated language: after deleting the promoted
    ancestor and returning to `L`, the descendant capability is unavailable. -/
theorem promotion_ablation_restores_unreachability {Atom : Type u} {Cap : Type z}
    (G : PromotionLanguage Atom Cap) (L : List Atom) (a : Atom) (c : Cap)
    (h : StrictPromotion G L a c) :
    ¬ G.Expresses L c := by
  exact h.cold

/-- Two-generation ancestral compounding.  The first residual certifies a
    lawful first regime change; the verified first product is then promoted as
    an atom, and a strict-promotion witness certifies that a designated second
    capability exists only in the promoted generated language. -/
theorem residual_then_promotion_compounds
    {Cap : Type z}
    (G : PromotionLanguage M Cap)
    (B : List M) (c₁ : M) (c₂ : Cap)
    (h₁ : Residual A obs B c₁)
    (h₂ : StrictPromotion G B c₁ c₂) :
    VerifiedStep A obs B c₁ ∧
    (¬ G.Expresses B c₂ ∧ G.Expresses (c₁ :: B) c₂) := by
  exact ⟨residual_yields_verified_step A obs B c₁ h₁,
    promotion_changes_expressibility G B c₁ c₂ h₂⟩

/-- The older same-action-language two-residual theorem remains useful for the
    pure SPLIT→SPLIT case. -/
theorem two_generation_compounding
    (B : List M) (c₁ c₂ : M)
    (h₁ : Residual A obs B c₁)
    (h₂ : Residual A obs (c₁ :: B) c₂) :
    VerifiedStep A obs B c₁ ∧ VerifiedStep A obs (c₁ :: B) c₂ := by
  exact ⟨residual_yields_verified_step A obs B c₁ h₁,
    residual_yields_verified_step A obs (c₁ :: B) c₂ h₂⟩

theorem ancestor_ablation_restores_first_obstruction
    (B : List M) (c₁ : M) (h₁ : Residual A obs B c₁) :
    ¬ CanDescend A obs B c₁ := by
  exact residual_blocks_old_capability A obs B c₁ h₁

end VerifiedDevelopment
