import Std
import FactorizationSufficiency
import ResidualCompiledSyntaxGenesis

universe u v w z

namespace VerifiedConsequenceToCompiledSyntax

open FactorizationSufficiency
open ResidualInterfaceGenesis
open ResidualDerivedMetaLanguageGenesis
open ResidualCompiledSyntaxGenesis

variable {X : Type u} {Probe : Type v} {V : Type w} {Y : Type z}

/-- The executable state represented by a residual-selected basis.  This is an
    ordinary finite list of observed values, generated from the selected probes. -/
def compiledView
    (observe : Probe → X → V)
    (B : List Probe)
    (x : X) : List V :=
  B.map (fun p => observe p x)

/-- Equality of compiled executable states implies agreement on every selected
    probe.  No decidable equality or finite probe universe is required. -/
theorem compiledView_eq_implies_jointView
    (observe : Probe → X → V)
    (B : List Probe)
    (x y : X)
    (h : compiledView observe B x = compiledView observe B y) :
    ∀ p, p ∈ B → observe p x = observe p y := by
  induction B with
  | nil =>
      intro p hp
      simp at hp
  | cons a as ih =>
      simp [compiledView] at h
      intro p hp
      simp at hp
      rcases hp with rfl | hp
      · exact h.1
      · exact h.2 p hp

/-- Residual-derived sufficiency therefore makes the protected consequence
    constant on every fibre of the generated executable representation. -/
theorem residuals_make_compiled_view_fibre_constant
    (observe : Probe → X → V)
    (target : X → Y)
    (B : List Probe)
    (h : ResidualDeterminesArity observe target B) :
    RespectsFibres (compiledView observe B) target := by
  intro x y hview
  exact h.1 x y (compiledView_eq_implies_jointView observe B x y hview)

/-- Restrict the codomain to states actually generated by the compiled view.
    This gives the exact executable image rather than assuming arbitrary lists
    of values are realizable. -/
def ReachableCompiledState
    (observe : Probe → X → V)
    (B : List Probe) :=
  { r : List V // ∃ x : X, compiledView observe B x = r }

/-- Canonical executable representation into its reachable image. -/
def compiledRepresentation
    (observe : Probe → X → V)
    (B : List Probe) : X → ReachableCompiledState observe B :=
  fun x => ⟨compiledView observe B x, ⟨x, rfl⟩⟩

/-- The generated representation is surjective onto exactly its reachable
    represented states; this is constructive and carries no extra world assumption. -/
theorem compiledRepresentation_surjective
    (observe : Probe → X → V)
    (B : List Probe) :
    Function.Surjective (compiledRepresentation observe B) := by
  intro r
  rcases r.property with ⟨x, hx⟩
  refine ⟨x, ?_⟩
  apply Subtype.ext
  exact hx

/-- Equality in the reachable compiled representation reduces to equality of
    the underlying finite generated view. -/
theorem compiledRepresentation_eq_implies_view_eq
    (observe : Probe → X → V)
    (B : List Probe)
    {x y : X}
    (h : compiledRepresentation observe B x = compiledRepresentation observe B y) :
    compiledView observe B x = compiledView observe B y := by
  exact congrArg Subtype.val h

/-- Central bridge: residual evidence does not merely license an abstract joint
    dependency. It generates an executable finite representation, and the
    protected consequence provably factors through that generated state. -/
theorem residuals_generate_factorizing_representation
    (observe : Probe → X → V)
    (target : X → Y)
    (B : List Probe)
    (h : ResidualDeterminesArity observe target B) :
    FactorsThrough (compiledRepresentation observe B) target := by
  apply respectsFibres_factorsThrough_of_surjective
  · exact compiledRepresentation_surjective observe B
  · intro x y hrep
    apply h.1 x y
    exact compiledView_eq_implies_jointView observe B x y
      (compiledRepresentation_eq_implies_view_eq observe B hrep)

/-- A verified separator in any current representation certifies that the
    protected consequence cannot factor through that representation. -/
theorem separator_certifies_nonfactorization
    {R : Type v}
    (q : X → R)
    (target : X → Y)
    {x y : X}
    (hcollapse : q x = q y)
    (hsep : target x ≠ target y) :
    ¬ FactorsThrough q target := by
  intro hf
  have hrespect := factorsThrough_respectsFibres q target hf
  exact hsep (hrespect x y hcollapse)

/-- End-to-end developmental bridge. A verified future disagreement proves the
    old representation inadequate. Residual structure then determines a basis,
    compiles an executable recursive representation, and restores factorization
    through the generated reachable state. -/
theorem verified_failure_to_generated_factorization
    {R : Type v}
    (q : X → R)
    (observe : Probe → X → V)
    (target : X → Y)
    (B : List Probe)
    {x y : X}
    (hcollapse : q x = q y)
    (hsep : target x ≠ target y)
    (hres : ResidualDeterminesArity observe target B) :
    (¬ FactorsThrough q target) ∧
      FactorsThrough (compiledRepresentation observe B) target := by
  exact ⟨separator_certifies_nonfactorization q target hcollapse hsep,
    residuals_generate_factorizing_representation observe target B hres⟩

end VerifiedConsequenceToCompiledSyntax
